### ISSUE TITLE
Remove the option `ptcl_feedback` in the field push

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#13]
This option was useful in the early stages of the code, when debugging. However, now it is cluttering the code, and making the field push routines unnecessarily long. I would remove it.

**Comment by MKirchen** [comment]
I agree that it makes the code cleaner if we remove ptcl_feedback. Hopefully, we don't need this feature in the future anymore.

I am okay with removing it!

**Comment by RemiLehe** [comment]
If we need it, it is very easy to recreate it directly in the input script: we just set the weights of the particles to 0 before calling the step function. (That way, we also have per-species control.)
