### ISSUE TITLE
Build numba functions for the field push

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#14]
Right now, the field push functions on the CPU are written in numpy, inside of `fields.py`. I think it could be better to have them written in numba, in a separate file. Also, it is a minor point, I would see two advantages to this:
- The functions would be much closer to the GPU functions. Since the GPU functions are not automatically tested, but the CPU functions are, this would make slightly less likely that there is a bug in the GPU functions. (Although it is by no means a guarantee.)
- The file `fields.py` would be shorter and more readable.

**Comment by MKirchen** [comment]
I agree, this makes sense.
