### ISSUE TITLE
Improve printing of MPI processes

### ISSUE THREAD

**Issue by MKirchen** [fbpic/fbpic#156]
Right now, the following code prints information about the number of MPI processes and the number of threads used:
```
    if comm.rank == 0:
        if use_cuda:
            message = "\nRunning fbpic-%s on GPU " %__version__
        else:
            message = "\nRunning fbpic-%s on CPU " %__version__
        message += "with %d proc" %comm.size
        if use_threading and not use_cuda:
            message += " (%d threads per proc)" %numba.config.NUMBA_NUM_THREADS
        message += ".\n"

        print( message )
```

We should change it to the following for better readability:
(Note that I exchanged "proc" with "MPI processes")

```
    if comm.rank == 0:
        if use_cuda:
            message = "\nRunning fbpic-%s on GPU " %__version__
        else:
            message = "\nRunning fbpic-%s on CPU " %__version__
        message += "with %d MPI processes" %comm.size
        if use_threading and not use_cuda:
            message += " (%d threads per MPI process)" %numba.config.NUMBA_NUM_THREADS
        message += ".\n"

        print( message )
```

**Comment by RemiLehe** [comment]
I like this. I agree that the previous printed message was not very explicit. 
Would you like to do a corresponding PR?

One thing to think about though is the case were we do single-proc simulation (esp. in the case where mpi4py is not installed): in this case it might be confusing for the user to see a message suggesting that MPI is used. I am wondering if the best, in the case, is to just print something like this:

- For single-proc:
```
Running fbpic-0.6.2 on CPU (using 4 threads)
``` 
- For multi-proc
```
Running fbpic-0.6.2 on CPU with 2 MPI processes (using 4 threads per MPI process)
```

What do you think?

**Comment by MKirchen** [comment]
yes that makes sense, I'll do a PR
