### ISSUE TITLE
Add 'utilities' folder

### ISSUE THREAD

**Issue by MKirchen** [fbpic/fbpic#159]
It might be nice to move the content of the folder lpa_utils, as well as the files "cuda_utils, mpi_utils, threading_utils..." to a common folder "utilities".

@RemiLehe What do you think?

**Comment by RemiLehe** [comment]
Yes, nice idea! I am okay with putting the `mpi_utils`, `cuda_utils`, etc. in the utilities folder. 

However, I would leave the `lpa_utils` where it is for 2 reasons:
- Moving it would break the API for users (`from fbpic.utilities.lpa_utils import ...`)
- The topics of these files is fairly different from the "house-keeping"/boilerplate that is done in `mpi_utils`, `cuda_utils`, etc.
