### ISSUE TITLE
Remove numba=0.34 restriction

### ISSUE THREAD

**Issue by MKirchen** [fbpic/fbpic#163]
It seems like the threading works fine with numba 0.36 (tested with periodic plasma wave test). We should remove the restriction that checks if numba 0.34 is installed and instead require numba 0.36 for the installation.

**Comment by RemiLehe** [comment]
Agreed! I also tested with numba 0.36 and had no issue either.

**Comment by RemiLehe** [comment]
Note: we should still have a check in `threading_utils.py` that tests whether the numba version is either 0.34 or 0.36 (since 0.35 fails).

**Comment by MKirchen** [comment]
Ill prepare a small PR
