### ISSUE TITLE
New printing functions break when mpi is not installed, for `verbose_level=2`

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#164]
The code breaks when printing the gpu information: 
```
 File "fbpic_script.py", line 92, in <module>
    use_all_mpi_ranks=False, initialize_ions=False, verbose_level=2 )
  File "/global/home/users/rlehe/miniconda3/lib/python3.6/site-packages/fbpic-0.6.2-py3.6.egg/fbpic/main.py", line 291, in __init__
    print_simulation_setup( self, verbose_level=verbose_level )
  File "/global/home/users/rlehe/miniconda3/lib/python3.6/site-packages/fbpic-0.6.2-py3.6.egg/fbpic/print_utils.py", line 224, in print_simulation_setup
    sim.comm.mpi_comm.barrier()
AttributeError: 'NoneType' object has no attribute 'barrier'
```

**Comment by MKirchen** [comment]
Mh.. thats strange, it should be the DummyCommunicator() which has a barrier() method. Ill fix it.

**Comment by RemiLehe** [comment]
Actually, I am wondering: are these barrier really necessary here? I think we could skip them, no?

**Comment by RemiLehe** [comment]
Also, there is also an error when trying to use `Get_library_version`. This is because, when doing single proc simulation, FBPIC sets the `sim.comm.mpi_comm` to `None` (in order to ensure that we never try to call MPI functions in this case).

**Comment by RemiLehe** [comment]
By the way: I'm starting to use those new printing messages in my simulation (esp. with `verbose_level=2`): I really like the new style!

**Comment by MKirchen** [comment]
I think those barriers() are needed.. Otherwise, the other ranks will print their information whenever they want, while the first proc still tries to print the useful information. It will look „unordered“ in the end. However, if you have a better way of doing it, I am happy to make the code cleaner.

**Comment by RemiLehe** [comment]
One way would be to do an mpi gather and have only the first proc print the result...
I'll do a corresponding PR (although it is only a suggestion so far).
