### ISSUE TITLE
Add options in `step` function for profiling the CPU code

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#18]
The module [cProfile](https://docs.python.org/2/library/profile.html#module-cProfile) allows to profile Python execution on the CPU side. In particular, we could add 
```
pr = cProfile.Profile()
pr.enable()
```
at the beginning of the step function, and 
```
pr.disable()
```
at the end. We could then print the results in a separate file for each MPI proc.

This would have several advantages:
- See which functions take most of the time on the CPU.
- See which CPU-side functions take time when running on GPU: this would allow us to avoid surprises and detect functions that perform unexpected memory copies from CPU to GPU.
- See how much time the MPI call take, and what limits the scaling to many MPI cores (at least for the multi-CPU version)

**Comment by MKirchen** [comment]
I have no experience with the cprofiler, but I am in favour with adding this as you proposed. Especially the last point, the MPI profiling, will be interesting to benchmark also for the GPU case as all the communication is CPU based.

**Comment by RemiLehe** [comment]
This was partially solved by the recent changes in the documentation.
