### ISSUE TITLE
Document how to perform multi-CPU / multi-GPU simulations

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#188]
Several users asked about the multi-CPU/multi-GPU version of FBPIC. It would be nice to include a section in the documentation.

In particular, we would need to explain:
- [ ] How the domain decomposition is performed (i.e. only 1d)
- [ ] Why we need to use finite-order (briefly)
- [ ] The implications for the continuity equation

**Comment by MKirchen** [comment]
This has been done in PR #348
