### ISSUE TITLE
Per-species density diagnostics

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#267]
Several users said that it would be useful to have a diagnostic that calculates the density of a given species on a grid (as opposed to having the overall charge density, i.e. the sum of all species).

This could be done by implementing a new diagnostic, e.g. 
```
SpeciesDensityDiagnostic( species, ... )
```
This would require to allocate dedicated arrays inside this object, and maybe reuse the existing deposition functions to efficient fill these arrays on the GPU/CPU. The arrays would then be stored in an openPMD file as a regular field.

The real difficulty is maybe if we wish to do this for back-transformed diagnostics (boosted frame to lab frame)...

**Comment by kookjine** [comment]
Isn't it possible that we just use given macro particle data in openPMD file to calculate the density of a given species, adding an openPMD-viewer method?

**Comment by RemiLehe** [comment]
Yes, that's a good point! This could indeed be done from the macroparticle data (assuming that all the macroparticles have been dumped to a file). And I agree that having the option to do particle histogramming with openPMD-viewer (not only for plotting) would be great!

That being said, if the macroparticle distribution is not quite cylindrically symmetric, then it will be impractical to reconstruct the azimuthal decomposition from the macroparticle data. Also, if fbpic dumps the particle density directly to file (instead of the full macroparticle data), then the size of the data file would be much smaller (in most cases).

So, I think both approaches have their respective advantages.
