### ISSUE TITLE
Save external field data

### ISSUE THREAD

**Issue by kookjine** [fbpic/fbpic#269]
Could we save external field data in openPMD file?

I have been able to check that external B field is well applied to the particles, seeing wiggled bunch. However, sometimes it would be nice to also visualize external fields so we can see how the external fields work in the system. 
 
I wonder if just I don't know how to deal with this or it's not available now due to the design of FBPIC.
It looks that now only self-fields data dumping is available though.

Thank you for reading!

**Comment by RemiLehe** [comment]
Thanks for the suggestion! I see how this could be useful for users.

It might be possible to add this capability in the code without to many changes... I'll try to think about it, and I'll keep you updated if I find an elegant/simple way.

**Comment by kookjine** [comment]
Thank you for considering.
It should be useful for me and hopefully other users also!

**Comment by RemiLehe** [comment]
The external fields can now be saved *on the particles*: see #330.
