### ISSUE TITLE
Missing speed of light in boosted frame timestep calculation

### ISSUE THREAD

**Issue by MKirchen** [fbpic/fbpic#291]
This line:

https://github.com/fbpic/fbpic/blob/4264bfbc6893cbae6820292f580459ab86770fe9/docs/source/example_input/boosted_frame_script.py#L44

should be:

`dt = min( rmax/(2*gamma_boost*Nr)/c, (zmax-zmin)/Nz/c )  # Timestep (seconds) `

**Comment by RemiLehe** [comment]
Wow, good catch! Could you commit the change directly to the `dev` branch?

**Comment by MKirchen** [comment]
Added in commit 21ff219
