### ISSUE TITLE
Allow changing checkpoint saving folder

### ISSUE THREAD

**Issue by pots007** [fbpic/fbpic#304]
Hey, 

Currently, it is possible to change the output folder of normal diagnostics, which is incredibly useful to perform parameter scans within one run script. However, it would be good if one could also set the checkpoint folder. Currently, if one tries to run another simulation in the same runscript with a different resolution, an error about sizes not matching will be given once a checkpoint is about to be written.

I assume this would involve not massive changes in the checkpoint_restart.py file?

Cheers,
Kris

**Comment by RemiLehe** [comment]
@pots007 The issue has been fixed in the `dev` branch of `fbpic`.
This will be available via `pip` in the next release. In the meantime, you can get that feature by installing the `dev` branch from source. (Let me know if you have questions on how to do this.)
