### ISSUE TITLE
test particle species 

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#318]
Just a simple question, is it possible to initialize test particle species which wouldn't give feedback to the fields but can feel the fields?

Many thanks.

**Comment by RemiLehe** [comment]
Thanks for your question and for your interest in the code!

The short answer is that you cannot easily create macroparticles that have **zero feedback**, but you can on the other hand create macroparticles that have such a **negligible feedback** that they are effectively test particles.

More precisely, if you wanted to create macroparticles with zero feedback, you would have to create macroparticles with zero "weight". (While the charge determines how macroparticles feel the fields, the "weight" determines how they give feeback from the fields. The "weight" is the number of physical particles that a given macroparticle represents. Although it is very physical, the PIC algorithm allows the weight to be less than 1, or even 0.)
In principle, you could create macroparticles with zero weight by using [add_new_species](https://fbpic.github.io/api_reference/simulation.html#fbpic.main.Simulation.add_new_species) and setting the argument `n` (density of physical particles represented) to `0`.

However, some time ago, we prevented FBPIC from creating macroparticles with exactly zero weight, mainly for performance reasons. (We did, at the time, recognize that this would prevent the creation of test particles ; see [this link](https://github.com/fbpic/fbpic/pull/223) for more info.)

So, the solution would be to create particles with negligible weight, i.e. use `add_new_species` with a very small value of `n` (e.g. `n=1.e-6`, which would be very small compared to the typical values of `n` for physical, non-test species - typically between 1.e17 and 1.e20 per cubic cm, i.e. between 1.e23 and 1.e26 in SI units, which are the units used in FBPIC.)

Does the above make sense? And does it answer your question and fits your use case?

**Comment by YongMa1988** [comment]
Hi Remi,

Many thanks for the explanation. 
Yes, your solution is exactly what I did, just to give a new species with very low density. And this solved my problem.

**Comment by RemiLehe** [comment]
Great! I'm glad that this works for you.
