### ISSUE TITLE
Unknown "invalid value encountered in double_scalars" error with add_elec_bunch_openPMD

### ISSUE THREAD

**Issue by YCAOsz** [fbpic/fbpic#320]
I encountered this type of error "Weights sum to zero, can't be normalized" after using add_elec_bunch_openPMD to add a file of an electron bunch and blank spaces to a new simulation. 

I tried to modify the np.average to np.ma.average (z=z-np.ma.average(z,weights=w)+z_off) or (z=z-constant+z_off) in the bunch.py file,
 but more errors shows up about "invalid value encountered in double_scalars"
[lowE_boost.e2298984.txt](https://github.com/fbpic/fbpic/files/2788962/lowE_boost.e2298984.txt)
Is this a cuda error? 
Thank you

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

It looks like the particles in the original openPMD file have their weights that summed to 0 (which, in principle should not be the case).

A couple of questions here, in order to help diagnose the problem:
- Would it be possible for you to post the openPMD file that was used?
- If not, could you explain how you generated the openPMD file: was this done by hand, or from a separate simulation, using another code that complies with openPMD?
- Could you post the line of code that you used when calling `add_elec_bunch_openPMD`? (for instance, did you use the argument `select`)?

Thanks in advance for your answers!

**Comment by RemiLehe** [comment]
Thanks for sending the file!

It looks like the openPMD file that you sent contains 0 macroparticles in the `"electrons"` species:
<img width="288" alt="screen shot 2019-01-23 at 4 46 00 pm" src="https://user-images.githubusercontent.com/6685781/51646709-8d3c3280-1f2e-11e9-8649-ce6e64892702.png">
Is that intended? If not, could you double-check the file?

Thanks!

**Comment by YCAOsz** [comment]
Actually, this issue gets more complicated. I created the file I sent you before with this script:  
[lwfa_scriptBlank.py.zip](https://github.com/fbpic/fbpic/files/2792389/lwfa_scriptBlank.py.zip)
But no matter what parameters I choose, it only produces get_fields data but no get_particles data. (Maybe there's no add_laser input?) I checked the h5 file called by this script and it has sensible particle data. 
Other postdocs in the group said the script is okay but they haven't encountered this issue before.

Also, would you mind providing your email? I find it more convenient than Github.

Thank you

**Comment by MKirchen** [comment]
Hey,

once you initialise the Simulation object, it will create an electron species by itself! This will be stored in the `sim.ptcl` list (first entry -> `sim.ptcl[0]`). To solve your problem there are two options:

1) please try to add the following after the simulation object:

`sim.ptcl = []` (this will delete the electron species created by the Simulation object)

**or** 

2) change the diagnostics output to output the correct bunch electron species (sim.ptcl[**1**]) that you added to the Simulation with `add_elec_bunch...` :

```
    # Add diagnostics
    sim.diags = [ FieldDiagnostic( diag_period, sim.fld, comm=sim.comm ),
                ParticleDiagnostic( diag_period, {"bunch" : sim.ptcl[1]},
                                select={"uz" : [1., None ]}, comm=sim.comm ) ]
```

**Comment by MKirchen** [comment]
Btw: We have a Slack channel where you can ask questions / get support - which we prefer over email.

https://slack-fbpic.herokuapp.com/ (use this link to join the Slack channel)

**Comment by MKirchen** [comment]
@YCAOsz Did my solution help? Can we close this issue?
