### ISSUE TITLE
boundary condition in r for fields

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#332]
Hi, I have a simple question about the boundary condition in r direction.
It seems to me that the fields always get reflected from the boundary at rmax. What kind of boundary condition is it by default? Is it possible to set an open boundary or absorption boundary to completely eliminate the reflection?
Many thanks!

**Comment by RemiLehe** [comment]
Hi,
Yes, the boundary condition in `r` is always reflecting for the fields.
There is a branch of FBPIC where we are developing an open boundary, but this is not ready for production so far.
At this point, the best solution for you is probably to try a larger simulation box in `r` (although it is much more expensive).
Does this answer your question?

**Comment by YongMa1988** [comment]
Hi Remi,
Thanks for the information. 
Yes, it answers my question. I look forward to the new branch!
