### ISSUE TITLE
how to run fbpic on specified GPUs?

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#337]
Hi, 

I'm trying to run fbpic on GPU on the Flux cluster at University of Michigan but hasn't succeed so far.
From the documentation page, it seems that the environment settings and the installation of fbpic depends on what kind of GPUs we want to use.

The GPU model here at Umich is a NVidia K20X. cuda is also available, I installed pyculib by myself (although I don't even know if i did it correctly). However, I always have problems when summiting the job. 

The error message I got is attached here. 

Is there anyone have any suggestions?

Many thanks,
Yong

<img width="897" alt="Screen Shot 2019-03-18 at 11 59 02 AM" src="https://user-images.githubusercontent.com/34725295/54545153-7be43500-4977-11e9-8d10-b71cae28c5f7.png">

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

From the output that you sent, it seems that you are having 2 separate (and probably independent) issues:
- FBPIC was unable to load `mpi4py` properly when running on the cluster. 
- FBPIC was unable to load the sorting library on GPU.
I would suggest to focus on the second issue first.

At least in the past, FBPIC ran fine on K20X GPUs. Could you send the output of `conda list`, so that I see which version of each package you are using, and so that I can try to reproduce the issue locally?

**Comment by YongMa1988** [comment]
Hi Remi,

Thank you for the quick reply.
Below is the output of "conda list":
--------------------------------------------------------
[yongm@flux-login3 CP3E18_a12_w30_gpu]$ conda list
# packages in environment at /sw/lsa/centos7/python-anaconda2/created-20170421b:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py27_1  
_r-mutex                  1.0.0               anacondar_1    r
accelerate                2.3.1               np111py27_0  
accelerate_cudalib        2.0                           0  
alabaster                 0.7.11                   py27_0  
anaconda                  custom           py27h4a00acb_0  
anaconda-client           1.6.14                   py27_0  
anaconda-navigator        1.8.7                    py27_0  
anaconda-project          0.8.2            py27h236b58a_0  
appdirs                   1.4.3                     <pip>
appdirs                   1.4.3                    py27_0  
asn1crypto                0.24.0                   py27_0  
astroid                   1.6.5                    py27_0  
astropy                   2.0.7            py27h3010b51_1  
atomicwrites              1.1.5                    py27_0  
attrs                     18.1.0                   py27_0  
babel                     2.6.0                    py27_0  
backports                 1.0              py27h63c9359_1  
backports.csv             1.0.1                    py27_0    bioconda
backports.functools_lru_cache 1.5                      py27_1  
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2  
backports.weakref         1.0rc1                   py27_0  
backports_abc             0.5              py27h7b3c97b_0  
bcbiogff                  0.6.4                      py_1    bioconda
bcftools                  1.8                  h4da6232_3    bioconda
bcolz                     1.2.1            py27h637b7d7_0  
beautifulsoup4            4.6.0            py27h3f86ba9_1  
bedtools                  2.27.1               he941832_2    bioconda
binutils_impl_linux-64    2.28.1               had2808c_3  
binutils_linux-64         7.2.0               had2808c_27  
biopython                 1.68                     py27_0    bioconda
bitarray                  0.8.2            py27h14c3975_0  
bkcharts                  0.2              py27h241ae91_0  
blas                      1.1                    openblas    conda-forge
blat                      36                            0    bioconda
blaze                     0.11.3           py27h5f341da_0  
bleach                    1.5.0                    py27_0  
blosc                     1.14.3               hdbcaa40_0  
bokeh                     0.13.0                   py27_0  
boost                     1.67.0           py27h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto                      2.48.0           py27h9556ac2_1  
boto3                     1.7.45                   py27_0  
botocore                  1.10.45                  py27_0  
bottle                    0.12.13                  py27_0    conda-forge
bottleneck                1.2.1            py27h21b16a3_0  
brewer2mpl                1.4.1                     <pip>
bx-python                 0.8.1            py27h355e19c_1    bioconda
bz2file                   0.98                     py27_0  
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
cdecimal                  2.3              py27h14c3975_3  
certifi                   2018.4.16                py27_0    conda-forge
cffi                      1.11.5           py27h9745a5d_0  
chardet                   3.0.4            py27hfa10054_1  
chrpath                   0.16                          0  
click                     6.7              py27h4225b90_0  
cloudpickle               0.5.3                    py27_0  
clyent                    1.2.2            py27h7276e6c_1  
colorama                  0.3.9            py27h5cde069_0  
coloredlogs               10.0                     py27_0  
colormath                 3.0.0                      py_2    conda-forge
conda                     4.5.5                    py27_0    conda-forge
conda-env                 2.6.0                h36134e3_1    anaconda
configparser              3.5.0            py27h5117587_0  
contextlib2               0.5.5            py27hbf4c468_0  
coverage                  4.5.1            py27h14c3975_0  
cryptography              2.2.2            py27h14c3975_0  
cudatoolkit               9.0                  h13b8566_0  
curl                      7.60.0               h84994c4_0  
cutadapt                  1.16                     py27_2    bioconda
cvxopt                    1.2.0           py27_blas_openblas_200  [blas_openblas]  conda-forge
cycler                    0.10.0           py27hc7354d3_0  
cyordereddict             0.2.2                    py27_0    bioconda
cython                    0.28.3           py27h14c3975_0  
cytoolz                   0.9.0.1          py27h14c3975_0  
cyvcf2                    0.8.4            py27h355e19c_3    bioconda
dask                      0.18.1                   py27_0  
dask-core                 0.18.1                   py27_0  
datashape                 0.5.4            py27hf507385_0  
dbus                      1.10.20                       0  
decorator                 4.3.0                    py27_0  
deepTools                 2.5.3                     <pip>
distributed               1.22.0                   py27_0  
docutils                  0.14             py27hae222c1_0  
emcee                     2.2.1                    py27_3    conda-forge
entrypoints               0.2.3            py27h502b47d_2  
enum34                    1.1.6            py27h99a27e9_1  
et_xmlfile                1.0.1            py27h75840f5_0  
expat                     2.2.5                he0dffb1_0  
fastcache                 1.0.2            py27h14c3975_2  
fftw                      3.3.8                h14c3975_0  
flask                     1.0.2                    py27_1  
flask-cors                3.0.6                    py27_0  
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8.1                         0    conda-forge
funcsigs                  1.0.2            py27h83f16ab_0  
functools32               3.2.3.2          py27h4ead58f_1  
functools_lru_cache       1.5                           0  
future                    0.16.0                   py27_1  
futures                   3.2.0            py27h7b459c0_0  
gcc_impl_linux-64         7.2.0                habb00fd_3  
gcc_linux-64              7.2.0               h550dcbe_27  
gdal                      1.9.2                         0    bioconda
gemini                    0.20.1           py27hacb5245_1    bioconda
geneimpacts               0.3.6                    py27_2    bioconda
gensim                    1.0.1               np111py27_0    anaconda
geos                      3.6.2                heeff764_2  
get_terminal_size         1.0.0                haa9412d_0  
gettext                   0.19.8.1             hd7bead4_3  
gevent                    1.0.2                    py27_0    bioconda
ggplot                    0.11.5                    <pip>
glib                      2.55.0                        0    conda-forge
glpk                      4.57                          0    bioconda
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py27h4cf3fa8_2  
gobject-introspection     1.55.0           py27h3a3fb3b_0    conda-forge
grabix                    0.1.8                         3    bioconda
graphite2                 1.3.11               h16798f4_2  
greenlet                  0.4.13           py27h14c3975_0  
grin                      1.2.1                    py27_4  
gsl                       2.4             blas_openblas_0  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
gurobi                    7.5.2                    py27_0    gurobi
gxx_impl_linux-64         7.2.0                hdf63c60_3  
gxx_linux-64              7.2.0               h550dcbe_27  
h5py                      2.8.0            py27ha1f6525_0  
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.2               hba1933b_1  
heapdict                  1.0.0                    py27_2  
html5lib                  0.9999999                py27_0  
htseq                     0.9.1            py27h24bf2e0_1    bioconda
htslib                    1.7                           0    bioconda
humanfriendly             4.12.1                   py27_0  
hypothesis                3.57.0           py27h24bf2e0_0  
iced                      0.4.0                     <pip>
icu                       58.2                 h9c2bf20_1  
idna                      2.7                      py27_0  
imageio                   2.3.0                    py27_0  
imagesize                 1.0.0                    py27_0  
inheritance               0.1.2                      py_1    bioconda
iopro                     1.7.2              np111py27_p0  
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.8.2                    py27_0  
ipyparallel               6.2.1                    py27_0  
ipython                   5.7.0                    py27_0  
ipython-cluster-helper    0.6.1                    py27_0    bioconda
ipython_genutils          0.2.0            py27h89fb69b_0  
ipywidgets                7.2.1                    py27_0  
isort                     4.3.4                    py27_0  
itsdangerous              0.24             py27hb8295c1_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py27_0  
jedi                      0.12.0                   py27_1  
jemalloc                  4.5.0                         0    bioconda
jinja2                    2.10             py27h4114e70_0  
jmespath                  0.9.3            py27h7df6b23_0  
joblib                    0.12                     py27_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py27h7ed5aa4_0  
jupyter                   1.0.0                    py27_4  
jupyter_client            5.2.3                    py27_0  
jupyter_console           5.2.0            py27hc6bee7e_1  
jupyter_core              4.4.0            py27h345911c_0  
keras                     2.2.0                         0  
keras-applications        1.0.2                    py27_0  
keras-base                2.2.0                    py27_0  
keras-preprocessing       1.0.1                    py27_0  
kiwisolver                1.0.1            py27hc15e7b5_0  
krb5                      1.14.2               hcdc1b81_6  
lazy-object-proxy         1.3.1            py27h682c727_0  
libboost                  1.65.1               habcd387_4  
libcurl                   7.60.0               h1ad7b7a_0  
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libgpuarray               0.7.6                h14c3975_0  
libiconv                  1.15                 h63c8f33_5    anaconda
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               hb9fc6fc_0  
libpq                     9.6.6                h4e02ad2_0  
libprotobuf               3.5.2                h6f1eeef_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                hdf63c60_3  
libthrift                 0.9.3                         1  
libtiff                   4.0.9                he85c1e1_1  
libtool                   2.4.6                h544aabb_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
linecache2                1.0.0            py27hc477507_0  
llvmlite                  0.15.0                   py27_0  
locket                    0.2.0            py27h73929a2_1  
lxml                      4.2.2            py27hf71bdeb_0  
lzo                       2.10                 h49e0be7_2  
lzstring                  1.0.3                    py27_0    conda-forge
macs2                     2.1.0                         0    bioconda
mako                      1.0.7            py27h3d58d4b_0  
markdown                  2.6.11                   py27_0  
markupsafe                1.0              py27h97b2822_1  
matplotlib                2.2.2            py27h0e671d2_0  
matplotlib-venn           0.11.5                   py27_0    conda-forge
mccabe                    0.6.1            py27h0e7c7be_1  
mercurial                 4.6.1            py27h14c3975_0  
metis                     5.1.0                hf484d3e_4  
mistune                   0.8.3            py27h14c3975_1  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py27_3  
mmtf-python               1.0.2                    py27_0    bioconda
mock                      2.0.0            py27h0c0c831_0  
mongo-driver              0.7.1                         0  
more-itertools            4.2.0                    py27_0  
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
mpmath                    1.0.0            py27h9669132_2  
msgpack-python            0.5.6            py27h6bb024c_0  
multipledispatch          0.5.0                    py27_0  
multiqc                   1.6a0            py27h24bf2e0_1    bioconda
mysql                     5.7.20               h55eaa98_0  
mysql-connector-c         6.1.6                         2    bioconda
navigator-updater         0.2.1                    py27_0  
nbconvert                 5.3.1            py27he041f76_0  
nbformat                  4.4.0            py27hed7f2b2_0  
ncurses                   6.0                  h9df7e31_2  
netifaces                 0.10.4                   py27_1    bioconda
networkx                  2.0              py27hfc23926_0  
nltk                      3.3.0                    py27_0  
nose                      1.3.7            py27heec2199_2  
notebook                  5.5.0                    py27_0  
numba                     0.30.1              np111py27_0  
numexpr                   2.6.5                    py27_0    conda-forge
numpy                     1.11.3          py27_blas_openblas_203  [blas_openblas]  conda-forge
numpydoc                  0.8.0                    py27_0  
ocl-icd                   2.2.9                h470a237_4    conda-forge
odo                       0.5.1            py27h9170de3_0  
olefile                   0.45.1                   py27_0  
openblas                  0.2.20                        8    conda-forge
openblas-devel            0.2.20                        7  
openpyxl                  2.4.0                    py27_0    bioconda
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                     py27_0  
pandas                    0.23.1           py27h637b7d7_0  
pandoc                    2.2.1                h629c226_0  
pandocfilters             1.4.2            py27h428e1e5_1  
pango                     1.41.0               hd475d92_0  
parso                     0.2.1                    py27_0  
partd                     0.3.8            py27h4e55004_0  
path.py                   11.0.1                   py27_0  
pathlib2                  2.3.2                    py27_0  
patsy                     0.5.0                    py27_0  
pbcore                    1.2.10                   py27_2    bioconda
pbr                       4.0.4                    py27_0  
pcre                      8.39                          1  
pep8                      1.7.1                    py27_0  
pepr                      1.1.24                   py27_1    bioconda
pexpect                   4.6.0                    py27_0  
pickleshare               0.7.4            py27h09770e1_0  
pigz                      2.4                  h84994c4_0  
pillow                    5.1.0            py27h3deb7b8_0  
pip                       10.0.1                   py27_0  
pip                       9.0.3                     <pip>
pixman                    0.34.0               hceecf20_3  
pluggy                    0.6.0            py27h1f4f128_0  
ply                       3.11                     py27_0  
prompt_toolkit            1.0.15           py27h1b593e1_0  
protobuf                  3.5.2            py27hf484d3e_0  
psutil                    5.4.6            py27h14c3975_0  
psycopg2                  2.7.4            py27hb7f436b_0  
ptyprocess                0.6.0                    py27_0  
py                        1.5.3                    py27_0  
py-boost                  1.65.1           py27hf484d3e_4  
py2bit                    0.2.1                     <pip>
pybedtools                0.7.10                   py27_2    bioconda
pyBigWig                  0.3.4                     <pip>
pycairo                   1.13.3           py27h44fc0e4_1  
pycodestyle               2.4.0                    py27_0  
pycosat                   0.6.3            py27ha4109ae_0  
pycparser                 2.18             py27hefa08c5_1  
pycrypto                  2.6.1            py27h14c3975_8  
pycuda                    2017.1.1                  <pip>
pycurl                    7.43.0.2         py27hb7f436b_0  
PyDSTool                  0.90.2                    <pip>
pyfasta                   0.5.2                    py27_0    bioconda
pyflakes                  2.0.0                    py27_0  
pygments                  2.2.0            py27h4a8b6f5_0  
pygobject                 3.28.2                   py27_0    conda-forge
pygpu                     0.7.6            py27h3010b51_0  
pylint                    1.9.2                    py27_0  
pymc                      2.3.7                    py27_0    conda-forge
pympler                   0.5              py27h8aa4898_0  
pyodbc                    4.0.23           py27hf484d3e_0  
pyopencl                  2018.1.1                 py27_2    conda-forge
pyopenssl                 18.0.0                   py27_0  
pyparsing                 2.2.0            py27hf1513f8_1  
pyqt                      5.6.0                    py27_2  
pysam                     0.14.1           py27hae42fb6_1    bioconda
pysocks                   1.6.8                    py27_0  
pytables                  3.4.4            py27h02b9ad4_0  
pytest                    3.6.2                    py27_0  
python                    2.7.14              ha6fc286_23    anaconda
python-crfsuite           0.9.5            py27h6bb024c_0  
python-dateutil           2.7.3                    py27_0    anaconda
python-lzo                1.11                     py27_0    conda-forge
python-snappy             0.5.2            py27hf484d3e_0  
pytools                   2017.4                    <pip>
pytools                   2018.5.2                   py_0    conda-forge
pytz                      2018.4                   py27_0  
pyvtk                     0.5.18                   py27_0    conda-forge
pywavelets                0.5.2            py27hecda097_0  
pyyaml                    3.12             py27h2d70dd7_1  
pyzmq                     17.0.0           py27h14c3975_1  
qt                        5.6.2                         7    conda-forge
qtawesome                 0.4.4            py27hd7914c3_0  
qtconsole                 4.3.1            py27hc444b0d_0  
qtpy                      1.4.2                    py27_0  
r                         3.4.2                h65d9972_0    r
r-base                    3.4.2                haf99962_0    r
r-boot                    1.3_20           r342ha5ac741_0    r
r-class                   7.3_14           r342h4797347_4    r
r-cluster                 2.0.6            r342hcb72a25_0    r
r-codetools               0.2_15           r342hc9ffb9b_0    r
r-foreign                 0.8_69           r342hbd6b6bb_0    r
r-kernsmooth              2.23_15          r342hdc3efa4_4    r
r-lattice                 0.20_35          r342h0f762c2_0    r
r-mass                    7.3_47           r342hd8605c9_0    r
r-matrix                  1.2_11           r342h3a55fe1_0    r
r-mgcv                    1.8_22           r342h176cc83_0    r
r-nlme                    3.1_131          r342h7f704e8_0    r
r-nnet                    7.3_12           r342ha98c111_0    r
r-recommended             3.4.2                h1751db4_0    r
r-rpart                   4.1_11           r342hd35cc14_0    r
r-spatial                 7.3_11           r342hff2a1d0_4    r
r-survival                2.41_3           r342hac888f2_0    r
readline                  7.0                  ha6073c6_4    anaconda
reportlab                 3.4.0                    py27_0  
requests                  2.14.2                   py27_0  
rope                      0.10.7           py27hfe459b0_0  
rseqc                     2.6.4            py27hf8a1672_2    bioconda
ruamel_yaml               0.15.40          py27h14c3975_2  
ruby                      2.2.3                         0    bioconda
s3transfer                0.1.13                   py27_0  
samtools                  1.7                           1    bioconda
scandir                   1.7              py27h14c3975_0  
scikit-image              0.14.0           py27hf484d3e_1  
scikit-learn              0.19.1          py27_blas_openblas_201  [blas_openblas]  conda-forge
scikit-sparse             0.4.3                    py27_0    conda-forge
scipy                     1.1.0           py27_blas_openblas_200  [blas_openblas]  conda-forge
scons                     3.0.1                    py27_1  
seaborn                   0.8.1            py27h633ea1e_0  
send2trash                1.5.0                    py27_0  
setuptools                39.2.0                   py27_0  
shapely                   1.6.4            py27h0c48222_0  
sharedmem                 0.3.5            py27h24bf2e0_1    bioconda
simplegeneric             0.8.1                    py27_2  
simplejson                3.8.1                    py27_0    bioconda
singledispatch            3.4.0.3          py27h9bcb476_0  
sip                       4.19.8           py27hf484d3e_0  
six                       1.11.0           py27h5f960f1_1  
smart_open                1.5.7                    py27_0  
snakeviz                  0.4.2            py27hf4b41a6_0  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1            py27h44e2768_0  
sortedcollections         1.0.1                    py27_0  
sortedcontainers          2.0.4                    py27_0  
spectra                   0.0.11                     py_0    conda-forge
sphinx                    1.7.5                    py27_0  
sphinx_rtd_theme          0.4.0                    py27_0  
sphinxcontrib             1.0              py27h1512b58_1  
sphinxcontrib-websupport  1.1.0                    py27_1  
spyder                    3.2.8                    py27_0  
sqlalchemy                1.2.8            py27h14c3975_0  
sqlite                    3.20.1               hb898158_2  
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2  
statsmodels               0.9.0            py27h3010b51_0  
subprocess32              3.5.2            py27h14c3975_0  
suitesparse               4.5.6           blas_openblas_200  [blas_openblas]  conda-forge
swig                      3.0.12               h38cdd7d_3  
sympy                     1.1.1            py27hc28188a_0  
system                    5.8                           2  
tbb                       2018.0.4             h6bb024c_1    anaconda
tblib                     1.3.2            py27h51fe5ba_0  
tensorflow                1.3.0                         0  
tensorflow-base           1.3.0            py27h0dbb4d0_1  
tensorflow-tensorboard    1.5.1            py27hf484d3e_1  
terminado                 0.8.1                    py27_1  
testpath                  0.3.1            py27hc38d2c4_0  
theano                    1.0.2            py27h6bb024c_0  
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                    py27_0  
tornado                   5.0.2                    py27_0  
traceback2                1.4.0            py27h153c7c5_0  
traitlets                 4.3.2            py27hd6ce930_0  
twobitreader              3.1.4                    py27_0    bioconda
typing                    3.5.2.2                  py27_0    bioconda
ucsc-bedclip              366                  h5eb252a_0    bioconda
ucsc-bigwigaverageoverbed 366                  h5eb252a_0    bioconda
ucsc-bigwigsummary        366                  h5eb252a_0    bioconda
ucsc-bigwigtobedgraph     366                  h5eb252a_0    bioconda
unicodecsv                0.14.1           py27h5062da9_0  
unidecode                 1.0.22                   py27_0  
unittest2                 1.1.0            py27h1e968a4_0  
unixodbc                  2.3.6                h1bed415_0  
urllib3                   1.12                     py27_0    bioconda
wcwidth                   0.1.7            py27h9e3e1ab_0  
werkzeug                  0.14.1                   py27_0  
wheel                     0.31.1                   py27_0  
widgetsnbextension        3.2.1                    py27_0  
wrapt                     1.10.11          py27h04f6869_0  
xlrd                      1.1.0            py27ha77178f_1  
xlsxwriter                1.0.5                    py27_0  
xlwt                      1.3.0            py27h3d85d97_0  
xopen                     0.3.2                      py_1    bioconda
xorg-kbproto              1.0.7                         1    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.5                         0    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-libxt                1.1.5                         0    conda-forge
xorg-renderproto          0.11.1                        1    conda-forge
xorg-xextproto            7.3.0                         1    conda-forge
xorg-xproto               7.0.31                        6    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
yt                        3.4.1            py27h3010b51_0  
zeromq                    4.2.5                h439df22_0  
zict                      0.1.3            py27h12c336c_0  
zlib                      1.2.11               ha838bed_2  
zope                      1.0                      py27_0  
zope.interface            4.5.0            py27h14c3975_0

**Comment by RemiLehe** [comment]
Ok, thanks! Actually sorry for not being very precise: but could you send the output of 
```
source activate fbpic
conda list
```

**Comment by YongMa1988** [comment]
Here it is:


<img width="673" alt="Screen Shot 2019-03-18 at 1 43 28 PM" src="https://user-images.githubusercontent.com/34725295/54551162-e8653100-4983-11e9-9019-787374f74f7b.png">

**Comment by RemiLehe** [comment]
OK, thanks. I'll try to reproduce your issue, and I'll keep you updated.

**Comment by YongMa1988** [comment]
@RemiLehe Many thanks!

**Comment by RemiLehe** [comment]
Hey, it looks like you installed `pyculib` from `pip`, and thus I am guessing that you followed the instructions for Summit, here: https://fbpic.github.io/install/install_summit.html

However, these instructions are for a very specific machine (Summit has OpenPower CPUs instead of Intel CPUs, and as a consequence several packages cannot be installed with `conda`, which makes the installation process more complicated.)

For your cluster at University of Michigan, I would recommend to use these generic intructions: 
https://fbpic.github.io/install/install_local.html
or maybe these instructions (which are quite similar):
https://fbpic.github.io/install/install_lawrencium.html#installation-of-fbpic
(i.e. I guess that the Lawrencium cluster is much closer to the one you have at U. Michigan)

Could you try the above, in an entirely new `conda` environment?

**Comment by YongMa1988** [comment]
@RemiLehe Hi Remi, you are right, I did follow the instructions for summit except for I cannot module load spectrum-mpi and py-mpi4py because they are not available on Flux.
Thank you very much for the suggestions, i will keep you updated.

**Comment by YongMa1988** [comment]
@RemiLehe Hi Remi,
Thanks again for your help, the second method works for me.

Below is exactly what I did:

1. wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
2. bash Miniconda3-latest-Linux-x86_64.sh -p /home/yongm/miniconda3
3. source .bashrc
4. conda create -n FBPIC python=3
5. [yongm@flux-login3 ~]$ conda activate FBPIC
6. (FBPIC) [yongm@flux-login3 ~]$ conda install -c conda-forge numba scipy h5py mkl mpi4py
7. (FBPIC) [yongm@flux-login3 ~]$ conda install -c conda-forge cudatoolkit=8 pyculib
8. (FBPIC) [yongm@flux-login3 ~]$ pip install fbpic

I submitted my job without deactivating the 'FBPIC' environment (I guess I should move 'conda activate FBPIC' into the script), the job submission script looks like this:
#!/bin/sh
#PBS -S /bin/sh
#PBS -N testGPU
#PBS -l nodes=1:gpus=2,mem=16gb,walltime=00:22:59:00,qos=flux
#PBS -M yongm@umich.edu
#PBS -m abe
#PBS -j oe
#PBS -V
#PBS -A engin_fluxg
#PBS -q fluxg

export FBPIC_ENABLE_GPUDIRECT=1

export OUTPUTDIR=~/fbpicGPU
cd ${OUTPUTDIR}
python *.py

**Comment by RemiLehe** [comment]
Great! I think the above makes sense.
Now that the issue with a single MPI rank is fixed, you might want to check that the code works with multiple MPI ranks (with the above code, it seems that only one of the 2 GPUs that are on the node is used.) i.e. running
```
mpirun -np 2 python *.py
```
instead of 
```
python *.py
```
Also, I would recommend to use `export FBPIC_ENABLE_GPUDIRECT=0` initially ; just to check that everything runs ok already in this case.

**Comment by YongMa1988** [comment]
Hi Remi,

Thanks for the suggestions.
I just had two quick tests. 

First, with `export FBPIC_ENABLE_GPUDIRECT=0` it still runs, although I don't know if it is faster or not.

Second, `mpirun -np 2 python *.py` with `export FBPIC_ENABLE_GPUDIRECT=1`. It turns out that it runs even slower than simply do `python *.py` for my specific input file. I attached the screen shots here below for the two cases:

1. `python *.py`
<img width="363" alt="Screen Shot 2019-03-19 at 9 00 11 PM" src="https://user-images.githubusercontent.com/34725295/54654373-61ec4480-4a94-11e9-80ba-80c61649d353.png">

2. `mpirun -np 2 python *.py`
<img width="381" alt="Screen Shot 2019-03-19 at 10 06 52 PM" src="https://user-images.githubusercontent.com/34725295/54654401-729cba80-4a94-11e9-958d-9c20afc70bee.png">

**Comment by RemiLehe** [comment]
OK, thanks.
Yes, I have also observed similar behavior on other cases: depending on the size of the problem, it may always be advantageous to split it across different GPUs. Note that, if splitting the problem across GPU is not faster, you can still use the 2 GPUs to do two entirely separate simulations (e.g. as part of a parameter scans), as explained here: https://fbpic.github.io/advanced/parameter_scans.html
And what you observed with `FBPIC_ENABLE_GPUDIRECT` is also consistent with observations from other users: depending on the MPI implementation installed, it may or may not be faster to enable GPUDirect.

Since it looks like you solved your installation problems, do you think we could close this issue?

**Comment by YongMa1988** [comment]
Hi Remi,
Many thanks for the comments. I will let you know if I have more issues.
Best!
