### ISSUE TITLE
Positively charged beam in FBPIC

### ISSUE THREAD

**Issue by alexey-petrenko** [fbpic/fbpic#358]
Dear Remi, 

I was wondering if it's possible to define a positively charged beam in FBPIC?
I'd like to try FBPIC for some proton-driven PWFA simulations (in the context of AWAKE).

Thanks!

Best regards,
/Alexey

**Comment by soerenjalas** [comment]
We have added this feature. It is implemented in the dev branch and will be available soon with the new release.
