### ISSUE TITLE
how to post-process the results of the fbpic simulation?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#359]
@MKirchen ,
      I have completed the example named of `lwfa_script.py`  in the `fbpic` code, and now I want to postprocess the simulation results. According to the manual [here](https://fbpic.github.io/how_to_run.html#visualizing-the-simulation-results), I have installed the `openpmd_viewer` to visualizing the simulation results, but I think it is not convenient，so, I want to   post-process the simulation results by the MATLAB code. And my code is in below:
![11](https://user-images.githubusercontent.com/31507149/58236773-375d8700-7d76-11e9-8767-bead140eef82.jpg)
and the running result is below:
![12](https://user-images.githubusercontent.com/31507149/58236841-5bb96380-7d76-11e9-90ab-e3e17d0ef0a7.jpg)

But on the other hand, I also used the `openpmd_viewer` to visualizing the result:
![13](https://user-images.githubusercontent.com/31507149/58237015-c10d5480-7d76-11e9-967d-4acc11bf9397.jpg)

By comparing these two cases, it can be found that the results post-processed by the MATLAB seems to have a global translation and cannot display completely. Do you know what the problem is? and do you have some post-process script files by the matlab or other programs ? Thank you !

**Comment by soerenjalas** [comment]
Hi @QJohn2017,

Fbpic works in quasi-cylindrical geometry. This means that the fields are decomposed into independent modes. The field grid in Fbpic goes from 0 to rmax. The hdf5 output files contain these raw decomposed fields. OpenPMD-viewer combines the modes to return the 3D information (z, r, theta).
We highly recommend the use of OpenPMD-viewer, but if you want to use your own methods the relevant code for the field reconstruction can be found  [here](https://github.com/openPMD/openPMD-viewer/blob/master/opmd_viewer/openpmd_timeseries/data_reader/field_reader.py) in the method `read_field_circ`.

**Comment by QJohn2017** [comment]
Okay, I will try later. here i have some other questions:
1，in the input file `lwfa_script.py`, there is a parameter `Nm = 2 `, does the parameter `Nm` represents the azimuthal modes ? and what is the relationship between the `Nm` and the polarization of laser?
 2，also in the input file `lwfa_script.py`, what is the relationship of the parameter `p_zmin` and `ramp_start`? In the example file, the `p_zmin=25um`, this represents that the plasma begins from 25um position, but the `ramp_start=30um`, this represents that the plasma begins from 30um position, This seems contradictory.
3，Does the FBPIC code  always works on 3D modes? how can I set 2D simulation in the input file?

**Comment by soerenjalas** [comment]
1. Yes Nm is the number of azimuthal modes. A simulation running with 1 mode is completely cylindrically symmetric. Adding a second modes allows to model for example a linearly polarised laser.

 2. `p_zmin` is the minimum position where particles are initialised at the beginning of the simulation. The plasma density is then modelled according to the function that is passed to the simulation object as `dens_func`. In the example file the density functions returns 0 for z positions smaller than `ramp_start`. Therefore, the plasma starts at `z=ramp_start`

3. FBPIC only runs in quasi-cylindrical geometry.

Please also refer to the [FBPIC documentation](https://fbpic.github.io) where these things are explained in more detail.

**Comment by QJohn2017** [comment]
May I think that Nm=1 represents a radial polarized or azimuthal  polarized laser pulse, and Nm =2 represents a linearly-polarized Gaussian laser pulse, and Nm=3 represents a linearly-polarized Laguerre-Gauss laser pulse (which with TEM02) ? 
If I want to set a linearly-polarized laser pulse by `add_laser` function, but I set `Nm=1` in the input file, what could happen ?  An error?

**Comment by soerenjalas** [comment]
The number of modes determines what kind of fields can be modelled in the simulation. As stated above a `Nm=1` simulation supports only fully symmetric fields whereas more modes allow fields with more complex azimuthal dependency. In order to simulate a linearly polarised laser at least 2 modes are required.
Running a simulation with too few modes does not lead to an error or a warning so caution is required.

Please also refer to the [original publication](https://doi.org/10.1016/j.jcp.2008.11.017) of fourier decomposition in PIC codes.

More information on the laser initialisation in FBPIC can be found in the documentation [here](https://fbpic.github.io/api_reference/lpa_utilities/laser.html).

As this discussion gets a little bit off topic I will close this issue for now.
