### ISSUE TITLE
Checkpoints not working with use_all_mpi_ranks = True

### ISSUE THREAD

**Issue by soerenjalas** [fbpic/fbpic#36]
Hi,
Currently it is not possible to use `use_all_mpi_ranks=True` and use checkpoints.
The problem is that `use_all_mpi_ranks=True` causes the Simulation object to set `self.mpi_comm=None`. However, the checkpoint routines try to call `sim.comm.mpi_comm.Barrier()`, which is not defined. This is used there to wait for rank 0 while it's creating directories and checking files.

I'm not too familiar with this MPI stuff but I think we could either create a communicator even when using use_all_mpi_ranks = True, or have every rank check its own files and create its own directory.

**Comment by RemiLehe** [comment]
Thanks for reporting this!
That's an easy fix ; I'm preparing the pull request right now.
