### ISSUE TITLE
fbpic running error

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#373]
Hi, when I update the fbpic to version 0.13, and then run the code, erros occurred, which has been showed in 
[slurm-11625711.txt](https://github.com/fbpic/fbpic/files/3291304/slurm-11625711.txt). 
Then I restalled the fbpic, but not works. lastly, I reinstalled the fbpic version back to 0.12, it also doesn't work.  I tried several times, but all failed.
So, I don't know how to fix this problem. Thank you !

**Comment by RemiLehe** [comment]
Thanks for reporting that error!
I looks like FBPIC had issues when writing the HDF5 files in the `diags` folder.
Could you try to remove the `diags` folder (`rm -rf diags`) and launch the simulation again?

**Comment by QJohn2017** [comment]
Okay, when I removed the `disgs` files and luanch the simulation again, it works.  Thank you ! By the way, I want to ask which `mpirun ` version do you use in `fbpic` code simulation ?
