### ISSUE TITLE
how to set the MKL_NUM_THREADS and NUMBA_NUM_THREADS in fbpic simulation

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#374]
Hi, I have a self-built centos server, and its imformation loads below: 
```
[siom@localhost lwfa]$ grep 'core id' /proc/cpuinfo | sort -u | wc -l
10
[siom@localhost lwfa]$ grep 'physical id' /proc/cpuinfo | sort -u | wc -l
4
[siom@localhost lwfa]$ grep 'core id' /proc/cpuinfo | sort -u | wc -l
10
[siom@localhost lwfa]$ grep 'processor' /proc/cpuinfo | sort -u | wc -l
40
[siom@localhost lwfa]$ dmidecode -s processor-version
/dev/mem: Permission denied
[siom@localhost lwfa]$ sudo dmidecode -s processor-version
[sudo] password for siom:
 Intel(R) Xeon(R) CPU E7- 4850 @ 2.00GHz
 Intel(R) Xeon(R) CPU E7- 4850 @ 2.00GHz
 Intel(R) Xeon(R) CPU E7- 4850 @ 2.00GHz
 Intel(R) Xeon(R) CPU E7- 4850 @ 2.00GHz
[siom@localhost lwfa]$

```
Now, I want to run the fbpic code on it, so how can I set the `MKL_NUM_THREADS and NUMBA_NUM_THREADS` to improve the computation efficient?

**Comment by MKirchen** [comment]
This CPU has 10 physical cores, so for each CPU you should set the number of threads to 10.
If you have more than one CPU on a single node, use 1 MPI process per CPU - as I have explained you before.

Of course, it can also make sense to scan the number of threads and test with how many threads FBPIC runs fastest, however - as I explained you before - setting the number of threads to the number of physical cores almost always is the best choice.

To find the number of physical cores for your CPU, you can just google the name of the CPU.
In your case googling `Intel(R) Xeon(R) CPU E7- 4850 @ 2.00GHz`, leads you to the Intel page that has all the details about your CPU [Intel(R) Xeon(R) CPU E7- 4850 @ 2.00GHz](https://ark.intel.com/content/www/us/en/ark/products/53574/intel-xeon-processor-e7-4850-24m-cache-2-00-ghz-6-40-gt-s-intel-qpi.html).

**Comment by QJohn2017** [comment]
Thank you very much ! I have 4 CPUs, Is it said that I can set my script as follows?
```
# !bin/sh
export MKL_NUM_THREADS=10
export NUMBA_NUM_THREADS=10
mpirun -n 4 python lwfa_script.py
```

**Comment by MKirchen** [comment]
Yes, this is correct.

For more information, please read again carefully the newest version of the online documentation:

https://fbpic.github.io/how_to_run.html

**Comment by QJohn2017** [comment]
Okay, I got it, thank you !
