### ISSUE TITLE
Error running FBPIC in multiple CPUs

### ISSUE THREAD

**Issue by abonatto** [fbpic/fbpic#377]
Dear FBPIC Developers,

In order to run FBPIC in multiple CPUs, I'm asking for 4 CPUs using --cpu_bind=socket in the cluster I'm using (SCARF). Moreover, in my script I have set use_all_mpi_ranks=True, and n_order=32. However, when I run it ( srun -n 4 python passive_fb014_3_3.py ), I'm receiving errors related to opening the data000...h5 file in 3 of the 4 processes (one of the processes keep running). Do you have a suggestion of how to solve this?

Regards.

Alex 

OUTPUTS:
`(fbpic) [scarf@cn465 FB014_3_3]$ srun -n 4 python passive_fb014_3_3.py 
cpu-bind=MASK - cn465, task  0  0 [9621]: mask 0xffff set
cpu-bind=MASK - cn465, task  1  1 [9622]: mask 0xffff set
cpu-bind=MASK - cn465, task  2  2 [9623]: mask 0xffff set
cpu-bind=MASK - cn465, task  3  3 [9624]: mask 0xffff set

FBPIC (0.13.0)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
MPICH Version:	3.2.1
MPICH Release date:	Fri Nov 10 20:21:01 CST 2017
MPICH Device:	ch3:nemesis
MPICH configure:	--prefix=/home/vol07/scarf/anaconda2/envs/fbpic --disable-dependency-tracking --enable-cxx --enable-fortran
MPICH CC:	x86_64-conda_cos6-linux-gnu-cc -I/home/vol07/scarf/anaconda2/envs/fbpic/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix  -O2
MPICH CXX:	x86_64-conda_cos6-linux-gnu-c++ -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH F77:	x86_64-conda_cos6-linux-gnu-gfortran -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH FC:	x86_64-conda_cos6-linux-gnu-gfortran  -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2

CUDA available: No
Compute architecture: CPU
CPU multi-threading enabled: Yes
Threads: 16
FFT library: MKL

PSATD stencil order: 32
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: reflective
Guard region size: 63 cells
Damping region size: 64 cells
Injection region size: 31 cells
Particle exchange period: every 14 step
Boosted frame: False

FBPIC (0.13.0)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
MPICH Version:	3.2.1
MPICH Release date:	Fri Nov 10 20:21:01 CST 2017
MPICH Device:	ch3:nemesis
MPICH configure:	--prefix=/home/vol07/scarf/anaconda2/envs/fbpic --disable-dependency-tracking --enable-cxx --enable-fortran
MPICH CC:	x86_64-conda_cos6-linux-gnu-cc -I/home/vol07/scarf/anaconda2/envs/fbpic/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix  -O2
MPICH CXX:	x86_64-conda_cos6-linux-gnu-c++ -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH F77:	x86_64-conda_cos6-linux-gnu-gfortran -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH FC:	x86_64-conda_cos6-linux-gnu-gfortran  -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2

CUDA available: No
Compute architecture: CPU
CPU multi-threading enabled: Yes
Threads: 16
FFT library: MKL

PSATD stencil order: 32
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: reflective
Guard region size: 63 cells
Damping region size: 64 cells
Injection region size: 31 cells
Particle exchange period: every 14 step
Boosted frame: False

FBPIC (0.13.0)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
MPICH Version:	3.2.1
MPICH Release date:	Fri Nov 10 20:21:01 CST 2017
MPICH Device:	ch3:nemesis
MPICH configure:	--prefix=/home/vol07/scarf/anaconda2/envs/fbpic --disable-dependency-tracking --enable-cxx --enable-fortran
MPICH CC:	x86_64-conda_cos6-linux-gnu-cc -I/home/vol07/scarf/anaconda2/envs/fbpic/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix  -O2
MPICH CXX:	x86_64-conda_cos6-linux-gnu-c++ -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH F77:	x86_64-conda_cos6-linux-gnu-gfortran -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH FC:	x86_64-conda_cos6-linux-gnu-gfortran  -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2

CUDA available: No
Compute architecture: CPU
CPU multi-threading enabled: Yes
Threads: 16
FFT library: MKL

PSATD stencil order: 32
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: reflective
Guard region size: 63 cells
Damping region size: 64 cells
Injection region size: 31 cells
Particle exchange period: every 14 step
Boosted frame: False

FBPIC (0.13.0)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
MPICH Version:	3.2.1
MPICH Release date:	Fri Nov 10 20:21:01 CST 2017
MPICH Device:	ch3:nemesis
MPICH configure:	--prefix=/home/vol07/scarf/anaconda2/envs/fbpic --disable-dependency-tracking --enable-cxx --enable-fortran
MPICH CC:	x86_64-conda_cos6-linux-gnu-cc -I/home/vol07/scarf/anaconda2/envs/fbpic/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix  -O2
MPICH CXX:	x86_64-conda_cos6-linux-gnu-c++ -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH F77:	x86_64-conda_cos6-linux-gnu-gfortran -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2
MPICH FC:	x86_64-conda_cos6-linux-gnu-gfortran  -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/vol07/scarf/anaconda2/envs/fbpic/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mpich-mpi_1559872707922/work=/usr/local/src/conda/mpich-3.2.1 -fdebug-prefix-map=/home/vol07/scarf/anaconda2/envs/fbpic=/usr/local/src/conda-prefix -O2

CUDA available: No
Compute architecture: CPU
CPU multi-threading enabled: Yes
Threads: 16
FFT library: MKL

PSATD stencil order: 32
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: reflective
Guard region size: 63 cells
Damping region size: 64 cells
Injection region size: 31 cells
Particle exchange period: every 14 step
Boosted frame: False

Calculating initial space charge field...
Calculating initial space charge field...
Calculating initial space charge field...
Calculating initial space charge field...
Done.

Done.

Done.

Done.

Traceback (most recent call last):
  File "passive_fb014_3_3.py", line 287, in <module>
    sim.step( N_step )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/main.py", line 408, in step
    diag.write( self.iteration )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/generic_diag.py", line 140, in write
    self.write_hdf5( iteration )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/field_diag.py", line 119, in write_hdf5
    fullpath, iteration, time, Nz, zmin, dz, dt )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/field_diag.py", line 252, in create_file_empty_meshes
    f = self.open_file( fullpath )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/generic_diag.py", line 117, in open_file
    f = h5py.File( fullpath, mode="a" )
  File "/home/vol07/scarf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/vol07/scarf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/work3/cse/scarf/fbpic/FB014_3_3/diags/hdf5/data00000000.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
Just-In-Time compilation (up to one minute) ...srun: error: cn465: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "passive_fb014_3_3.py", line 287, in <module>
    sim.step( N_step )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/main.py", line 408, in step
    diag.write( self.iteration )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/generic_diag.py", line 140, in write
    self.write_hdf5( iteration )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/field_diag.py", line 119, in write_hdf5
    fullpath, iteration, time, Nz, zmin, dz, dt )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/field_diag.py", line 252, in create_file_empty_meshes
    f = self.open_file( fullpath )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/generic_diag.py", line 117, in open_file
    f = h5py.File( fullpath, mode="a" )
  File "/home/vol07/scarf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/vol07/scarf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/work3/cse/scarf/fbpic/FB014_3_3/diags/hdf5/data00000000.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
Just-In-Time compilation (up to one minute) ...srun: error: cn465: task 3: Exited with exit code 1
Traceback (most recent call last):
  File "passive_fb014_3_3.py", line 287, in <module>
    sim.step( N_step )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/main.py", line 408, in step
    diag.write( self.iteration )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/generic_diag.py", line 140, in write
    self.write_hdf5( iteration )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/field_diag.py", line 119, in write_hdf5
    fullpath, iteration, time, Nz, zmin, dz, dt )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/field_diag.py", line 252, in create_file_empty_meshes
    f = self.open_file( fullpath )
  File "/home/vol07/scarf/anaconda2/envs/fbpic/lib/python2.7/site-packages/fbpic-0.13.0-py2.7.egg/fbpic/openpmd_diag/generic_diag.py", line 117, in open_file
    f = h5py.File( fullpath, mode="a" )
  File "/home/vol07/scarf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/vol07/scarf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/work3/cse/scarf/fbpic/FB014_3_3/diags/hdf5/data00000000.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
Just-In-Time compilation (up to one minute) ...srun: error: cn465: task 2: Exited with exit code 1`

**Comment by soerenjalas** [comment]
Hi,
it seems that somehow you have 4 individual simulations running (see ´MPI processes used: 1´ in the verbose output). I suspect that this is some unwanted behavior of your MPI setup. Could you double check that you indeed pass `use_all_mpi_ranks=True` to the simulation object?

If that is the case could you test what happens if you don't pass the cpu-binds to srun?
Right now you are using the MPI library that comes with anaconda. The MPI from anaconda does not use the `srun` command but `mpirun`. Depending on the clusters setup it might help to run `mpirun -n 4 python passive_fb014_3_3.py`.

If your cluster provides an MPI installation you might want to use that. This is also how we run the code on other systems (e.g. JUWELS). You can find an instruction on how to set up the code in that case [here (JUWELS)](https://fbpic.github.io/install/install_juwels.html) or [here (COMET)](https://fbpic.github.io/install/install_comet.html)

**Comment by abonatto** [comment]
Dear Sören,

Using mpirun instead of srun was enough to solve the problem. I was using srun because it's recommended in the cluster I'm using but, as you pointed out, since I'm using anaconda (instead of a MPI module provided by the cluster), it makes sense to used mpirun instead.

Thank you very much for your support.

Regards.

Alex
