### ISSUE TITLE
pip-only install

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#379]
Is it possible to install `fbpic` (and all it's dependencies) without using `conda`?

**Comment by RemiLehe** [comment]
Hey, I had never tried before, but I just did some tests and it seems that it works (at least on my local machine).

For CPU, you can simply do:
```
pip install numba scipy h5py mkl fbpic
```

For GPU, you need to first install `cuda` separately (e.g. with `apt-get install`) and then
```
pip install numba scipy h5py cupy-cuda101 fbpic
```
Notice that, in that case, you do not need the `conda` `cudatoolkit` package: `numba` seems to be able to detect the `cuda` distribution. (Again, this worked on my local machine, but I am not sure how robust that is.)

**Comment by berceanu** [comment]
Yes, I was interested in the GPU version especially. It's good to hear the underlying toolkit is auto-detected.
