### ISSUE TITLE
Issues with boosted frame

### ISSUE THREAD

**Issue by yongm1988** [fbpic/fbpic#382]
Hi, 

I'm trying to play with the boosted frame but I got some issues.
My input script is based on the example: https://fbpic.github.io/example_input/boosted_frame_script.html
with some modifications. 

I got this error message after it just started:
![image](https://user-images.githubusercontent.com/38574190/61471035-0f426c80-a950-11e9-87bb-ba0795db2d1e.png)

Any idea why?

**Comment by RemiLehe** [comment]
Thanks for reporting this issue.
Could you send the input script that produces this error? (Or a modified version of it that reproduces the same issue)

Thanks in advance!

**Comment by RemiLehe** [comment]
For future reference: The issue was resolved in private discussions.
@yongm1988 solved the problem by upgrading to the latest version of FBPIC (0.13).
