### ISSUE TITLE
Particle_data does not save E/r and B/t at particles positions in FBPIC particle diagnostic

### ISSUE THREAD

**Issue by abonatto** [fbpic/fbpic#390]
Dear Developers,

I am using the following diagnostics,
```
ParticleDiagnostic(diag_period, {"beam": beam},
                                particle_data=["position", "momentum", "weighting",
                                "E", "B", "gamma"], comm=sim.comm)
```
However, when I try to get E_r and B_theta,
```
pEr, pBt = ts.get_particle(['E/r', 'B/t'], iteration=iter, species='beam')
```
I get the following message:
```
OpenPMDException: The argument `var_list` is missing or erroneous.
It should be a list of strings representing species record components.
 The available quantities for species 'beam' are:
 - B/x
 - B/y
 - B/z
 - E/x
 - E/y
 - E/z
 - charge
 - gamma
 - id
 - mass
 - x
 - y
 - z
 - ux
 - uy
 - uz
 - w
Please set the argument `var_list` accordingly.
```
Since Er and B_theta are available in FBPIC, would it be possible to also save them when particle_data includes  E and B in **fbpic.openpmd_diag.ParticleDiagnostic**?

Cheers,

Alex

**Comment by MKirchen** [comment]
Hi, thanks for you question. As you probably know, particles in FBPIC are defined/stored in Cartesian coordinates, thus the particle fields written by the diagnostics are Ex, Ey, Ez, Bx, ... and so on. If you want to have Er and B_theta, then you need to calculate them from the Cartesian particle data. It is currently not possible (or planned) to directly write Er / B_theta to the diagnostics. Is there any significant advantage for you if we would include this in the code?

**Comment by abonatto** [comment]
Dear @MKirchen,

Thank you for your answer. Yes, I understand. However, I thought that, since FBPIC does have Er and Bt (which are available when using field diagnostics), it would be possible to have them also written in particle diagnostics by using the same algorithms you already use to write the cartesian components of the fields (of course, I can be totally wrong, since I have no knowledge of how the software is structured!). Having Er and Bt available (at the particles positions) would be great to track the transverse, focusing/defocusing force (Er - c*Bt) for a selected set of particles. I opened this issue because I thought it could be something missing, but now it is clear tom me that not writing Er and Bt are a design choice. Therefore I am closing it.

Cheers,

Alex.
