### ISSUE TITLE
Weird electron density structure with ionization turned on 

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#396]
Hi Remi,

As I mentioned to you at APSDPP, I saw weird plasma density structure near the boundary of the box when I use neutral hydrogen as target. Here I attached a snapshot to illustrate that. I plotted the ionized electron density and the laser E fields. It seems that the E fields are fine even if I enhanced the fields by limiting the color scale.
The detailed evolution of the electron density and the input deck can be found in the zipped file.

I need to mention that there wasn't such kind of structure with pre-ionized plasma.

Thanks,
Yong
 
![comp7500](https://user-images.githubusercontent.com/34725295/67887915-9217bd80-fb22-11e9-8023-995e5cf1f4ab.png)
[Archive.zip](https://github.com/fbpic/fbpic/files/3790629/Archive.zip)

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this issue!
I'll have a close look at it in the next few days.
