### ISSUE TITLE
Number of modes for ionization injection

### ISSUE THREAD

**Issue by titoiride** [fbpic/fbpic#412]
I have a couple of simple (I hope) questions:

- I'm running a laser-plasma acceleration simulation in a regime in which I'm pretty confident no self (bubble) injection should occour. On the other hand, there's a dopant atom in the gas jet that produces ionization injection. From your experience, do you have any suggestion on the minimum number of azimuthal modes needed to well simulate the process? On the guidelines there's some tip about the bubble injection (min 3 modes), but I was hoping that for the ionization injection I could use one less mode.

- Is there a way to identify from which atomic level a given particle in the diagnostic phase space is extracted?

Thank you for you help and for the great work, I'm really enjoying using fbpic!

**Comment by soerenjalas** [comment]
Hi,
Concerning point 1, I think for most (non-super fancy) problems 2 modes should be okay to use. I haven't seen the same issues as with self-injection so far. But the safe way is to simulate both settings and check if there are major differences.

Point 2: You can tell fbpic to use one particle species per ionization level. Here is a brief example how to do that. You can find a short documentation here (https://fbpic.github.io/api_reference/particles.html#fbpic.particles.fbpic.particles.Particles.Particles.make_ionizable)


```python

# Initialize the simulation object
sim = Simulation( Nz, zmax, Nr, rmax, Nm, dt, zmin=zmin,
        boundaries='open', n_order=n_order, use_cuda=use_cuda )
# Remove auto-generated electron species
sim.ptcl=[]
# Add the gas ions
# and the electrons (from the pre-ionized Hydrogen)
atoms_Ne = sim.add_new_species( q=0, m=20.*m_p, n=n_gas,
    dens_func=dens_func_Ne, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin)
elec = sim.add_new_species( q=-e, m=m_e, n=n_gas,
    dens_func=dens_func_e, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin)

# Add new species for each ionization level
elec_Ne = [sim.add_new_species( q=-e, m=m_e ) for i in range(10)]

# Activate ionization of Ne ions.
# Store the created electrons in the dedicated electron species for each level that
# does not contain any macroparticles initially
atoms_Ne.make_ionizable( 'Ne', 
                        target_species={0:elec_Ne[0],
                                        1:elec_Ne[1],
                                        2:elec_Ne[2],
                                        3:elec_Ne[3],
                                        4:elec_Ne[4],
                                        5:elec_Ne[5],
                                        6:elec_Ne[6],
                                        7:elec_Ne[7],
                                        8:elec_Ne[8],
                                        9:elec_Ne[9]} )
# Add diagnostics
sim.diags = [
            FieldDiagnostic( diag_period, sim.fld, comm=sim.comm ),
            ParticleDiagnostic( diag_period,
                {"electrons": elec,
                "elecNe0":elec_Ne[0],
                "elecNe1":elec_Ne[1],
                "elecNe2":elec_Ne[2],
                "elecNe3":elec_Ne[3],
                "elecNe4":elec_Ne[4],
                "elecNe6":elec_Ne[6],
                "elecNe7":elec_Ne[7],
                "elecNe8":elec_Ne[8],
                "elecNe9":elec_Ne[9],},
                comm=sim.comm, select={'uz':[1, None]} ),
            ]
```

**Comment by titoiride** [comment]
Thank you again for the help, you've been really clear!

**Comment by soerenjalas** [comment]
Glad I could help!
