### ISSUE TITLE
Problems with enabling multi-threading

### ISSUE THREAD

**Issue by rogerpnunes** [fbpic/fbpic#436]
Hi,

First of all, thank you for your attention.

I am experiencing some problems when enabling multi-threading in a simulation. If I turn it off, the simulation runs fine. If I run the simulation in a GPU, no problems in the same way. If I use many GPUs or CPUs and set many MPI, I have not found also problems. However, if I turn the multi-threading option on, the problem appears. It seems that all initial conditions are set, since the first file is written in the diags folder. But right after or during the compilation of the main loop of the simulation, an error occur. Please see the log attached. [log.txt](https://github.com/fbpic/fbpic/files/4359150/log.txt)

What can be happening?

Thank you again,

Roger

**Comment by MKirchen** [comment]
Hi Roger,

really sorry for the late reply! 

I think the issue you are seeing is not directly related to FBPIC but comes from numba.
It is probably related or even the same issue as the one reported here: numba/numba#5156

Are you using Python 3.8? If so, can you check if the error disappears with Python < 3.8?

Thanks,
Manuel

**Comment by rogerpnunes** [comment]
Hi Manuel,

Thank you for your reply. I will read the issue you have sent. 

I am using Python 3.7.3. See right below.

Thank you again,
 
--
Roger Pizzato Nunes
rogerpn@gmail.com


Iniciando @ Wed Mar 25 08:48:35 -03 2020


****************************


sdumont1077
sdumont1077


****************************


Python 3.7.3


****************************



FBPIC (0.15.1)

MPI available: Yes
MPI processes used: 2
MPI Library Information:
Open MPI v4.0.2, package: Open MPI root@99c0a0fe-62fd-4ef2-7914-f5df42e40380 Distribution, ident: 4.0.2, repo rev: v4.0.2, Oct 07, 2019^@
CUDA available: No
Compute architecture: CPU
CPU multi-threading enabled: Yes
Threads: 12

**Comment by MKirchen** [comment]
Okay, Could you maybe try to run the minimal example that was posted in the issue and check if you get the same error?

**Comment by rogerpnunes** [comment]
Hi Manuel,

Yes. You will find attached 2 files, containing the logs of the executions related to the example you have mentioned, ran with the parallel option true and false.

The first file, *464.out (True case) reports the problem. The second file (False case), *466.out, presents no problem.

I am already using a Python version that is lower than 3.8 (I load Anaconda3, which uses the previously mentioned version of Python). Have I to downgrade even more the Python version?

Thanks for your assistance,

--
Roger Pizzato Nunes
rogerpn@gmail.com

**Comment by MKirchen** [comment]
Hey, I think using Python < 3.8 should be fine (according to the Issue). Could you maybe in addition tell me which version of numba you are using (it might be good to test an older version of numba)? It would also be helpful if you could run the diagnostic command `numba -s` and post the output here.

**Comment by rogerpnunes** [comment]
Hi Manuel,

I have located the problem, which was related with the Python version as you mentioned.

The problem was in my local conda environment, in which I have, some time ago, installed a Python version that was greater  than 3.8. 

In my slurm script, I was first loading an Anaconda module with python version 3.7.3 provided by the cluster, but right after, I was also activating my local Anaconda environment, with the incompatible python version.

Downgrading the python version in my local Anaconda environment has solved the problem.

Many thanks for your precise identification of the problem.

--
Roger Pizzato Nunes
rogerpn@gmail.com

**Comment by MKirchen** [comment]
Great, good that you could solve it!
