### ISSUE TITLE
mpi4py from defaults channel

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#447]
The installation instructions recommend `conda install -c conda-forge mpi4py`, however, this pulls in:

```
    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    certifi-2020.4.5.1         |   py37hc8dfbb8_0         151 KB  conda-forge
    conda-4.8.3                |   py37hc8dfbb8_1         3.0 MB  conda-forge
    mpi-1.0                    |          openmpi           4 KB  conda-forge
    mpi4py-3.0.3               |   py37hbfacf26_1         647 KB  conda-forge
    openmpi-4.0.3              |       hdf1f1ad_1         3.9 MB  conda-forge
    openssl-1.1.1g             |       h516909a_0         2.1 MB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    ------------------------------------------------------------
```

whereas `conda install -c defaults mpi4py` does

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mpi-1.0                    |            mpich          13 KB
    mpi4py-3.0.3               |   py37h028fd6f_0         541 KB
    mpich-3.3.2                |       hc856adb_0         3.8 MB
    ------------------------------------------------------------
                                           Total:         4.4 MB
```

Since both install `mpi4py-3.0.3`, should we still recommend installation from the `conda-forge` channel?

**Comment by RemiLehe** [comment]
Good point! I think that either of these commands will work, but the second one is indeed probably faster to install.

In any case, I think I would wait for `mpi4py-3.1.0` to be released, before changing the documentation. `mpi4py-3.1.0` will be very useful because it will have direct support of GPU-to-GPU MPI communications: 
https://github.com/fbpic/fbpic/pull/440

**Comment by cbontoiu** [comment]
Hello,

As of January 2020 I assume ```mpi4py 3.1``` was not yet released so we cannot run the code with ```export FBPIC_ENABLE_GPUDIRECT=1```. The typical ```lwfa_script.py``` example runs in 1 min and 30 secs. I was trying to check whether I can speed up even more but I obtained the error ```In order to use GPU Direct, you need to install mpi4py>=3.1```

**Comment by MKirchen** [comment]
GPUDirect can be made available when manually installing the dev branch of mpi4py, e.g. according to

`pip install git+https://bitbucket.org/mpi4py/mpi4py.git --no-cache-dir`
