### ISSUE TITLE
Probems using fbpic

### ISSUE THREAD

**Issue by lucy2231** [fbpic/fbpic#456]
Good afternoon, I'm sorry to bother you with such technicals problems but I don't find any help and I need to use FBIC for my work
I'm trying to install it, I guess it's almost done : I manage to run the file lwfa_script.py, but I don't understand how I can visualize results or even get a file with the data of the simulations...
I also tried to use the command "openPMD_notebook" but I get this error : "NameError: name 'openPMD_notebook' is not defined" (the package openmd is download, I checked)

If someone had the time to help me I would be really gratefull !

**Comment by soerenjalas** [comment]
Hi,
when `lwfa_script.py` runs properly it should create the folder diags/hdf5 which contains hdf5 files with the simulation output. 
Concerning openPMD, it looks like you are trying to run openPMD_notebook from within a python shell or a notebook. However, it is a terminal command that generates and starts a jupyter notebook template to give you a jumpstart at inspecting the files.

If you already have a notebook running you can import openPMD-viewer via
```python
from openpmd_viewer import OpenPMDTimeSeries
```
and load and inspect your data wir 
```
d = OpenPMDTimeSeries('./diags/hdf5/')
d.slider()
```

You can find more examples on how to use openPMD-viewer [here](https://github.com/openPMD/openPMD-viewer/tree/master/tutorials).

**Comment by lucy2231** [comment]
Thank you so much ! I finally managed to use this !
