### ISSUE TITLE
why the longitudinal accelerating filed Ez have so many oscillation terms?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#457]
Hi, when I do the LWFA simulation, and I found that the longitudinal accelerating field Ez have many oscillation terms like below:
![image](https://user-images.githubusercontent.com/31507149/85645920-96a26f00-b6cd-11ea-8349-62cb786b65e5.png)
![image](https://user-images.githubusercontent.com/31507149/85645959-ac179900-b6cd-11ea-8302-0731eba9264e.png)

Becuase the plasma channel I used in simulation is mismatching and the laser has a large oscillation amplitude, so , If I want to mitigate the serious oscillation of longitudinal Ez, how can I do in simulation? Is it necessary to increase the order of the filed solver ? such as increase `n_order ` ?

**Comment by MKirchen** [comment]
If you suspect that these oscillations are of unphysical nature (which might very well not be the case), try to increase the resolution and see if they decrease. You can use the default order `n_order=32`. It is unlikely that a higher (or lower) order would change the observed oscillations.
