### ISSUE TITLE
Iteration number reset when restarting a simulation

### ISSUE THREAD

**Issue by syoffe** [fbpic/fbpic#464]
When restarting a simulation with a total number of steps `N` from a checkpoint at iteration `n`, although the output dumps continue from iteration `n`, the progress bar starts again from `0` and tries to run a further `N` steps.

For example, I ran a simulation with 350,000 steps and due to maximum run time on the HPC scheduler I was forced to restart from iteration 250,000. I was therefore expecting the final 100,000 steps to be performed. I had not changed my `N_steps` variable to account for the steps already taken. The output dumps continued to be numbered from 250,000, but the progress bar started from 0 again. Instead of ending once the simulation and output reached 350,000, it continued to 450,000 (when the progress bar said iteration 200000/350000) before I killed the job.

**Comment by soerenjalas** [comment]
As an easy fix for this you correct `N_steps` with `sim.iteration`, i.e. `N_steps -= sim.iteration`.

**Comment by MKirchen** [comment]
Hey @syoffe, What you describe is expected behaviour from the way the code works, although we (@RemiLehe) might discuss if we should improve on this. In any case, I would suggest to use fix proposed by @soerenjalas.

**Comment by syoffe** [comment]
Hi @soerenjalas and @MKirchen, thanks for your replies and suggestions. I understand this is expected behaviour, and I'm happy to implement the change as suggested by @soerenjalas into my own work. However, I don't think that this behaviour is obvious to a user performing a restart, so perhaps a comment in the documentation would help. When performing a restart, I would expect everything about the simulation to continue from the checkpoint reached. Cheers!
