### ISSUE TITLE
FBPIC running on cpu on greatlakes cluster despite use_cuda=True

### ISSUE THREAD

**Issue by andrefantoine** [fbpic/fbpic#465]
Since the most recent update of FBPIC (v0.17),

Issue number 1) I have had an issue where the greatlakes system (University of Michigan HPC cluster) does not run the process unless I load the proper modules before submitting the script (an issue I did not have beforehand).
**See link below**

Issue number 2) Even with use_cuda = True and the partition in the submission script set to GPU FBPIC persists to run on cpu.

[example1.txt](https://github.com/fbpic/fbpic/files/4954085/example1.txt)

**Comment by MKirchen** [comment]
Hey Andre, 

Looking at the error that you posted (Issue 1), I would propose that you first make sure that you have the most recent version of cupy installed everywhere and that your python interpreter also uses it; e.g. by running "`import cupy; print(cupy.__version__)`". It could be that in some configuration, the cluster loads an old cupy version that is not the one that you installed.

This could then also be related to Issue 2. I suspect that FBPIC does not recognize a GPU or working numba/cupy installation. You can use the parameter "`verbose_level=2`" when creating the Simulation() object. This will print additional information when running the simulation, that might help you. 

You can also try to manually check if `numba` and `cupy` work correctly. Please have a look at the header of this file: `https://github.com/fbpic/fbpic/blob/dev/fbpic/utils/cuda.py`, to see how FBPIC checks if cuda is installed properly.

Finally, it seems that you problem is not related to FBPIC but to you software setup. 
I am afraid I cannot help you more at this point.

**Comment by andrefantoine** [comment]
Hi,

Thanks for the advice, I recreated my venv and the issue seemed to be that fbpic works with numba v0.49 instead of numba v0.50. But it seems to be using GPUs again.

**Comment by RemiLehe** [comment]
Hi,
Yes, FBPIC 0.17.0 imposed restrictions on the versions of numba that you can use for a run with GPU (basically: lower than numba 0.50).
However, I released a minor fix in the new version FBPIC 0.17.1 just now, which allows it to run with numba 0.50 and lower. As usual, you can get the new version with:
```
pip install --upgrade fbpic
```
