### ISSUE TITLE
Potential issue with particle momentum when using particle_diag

### ISSUE THREAD

**Issue by mjvstreeter** [fbpic/fbpic#466]
Hello,
I encountered an issue where frequently using the particle diagnostics to output the momenta of a species appeared to have the effect of slowing down the particles. 

I think the problem might be caused by the *= operator, which might be changing the values which are used by the simulation process.
Starting from line 501 of particle_diag.py:
```
# If this is the momentum, multiply by the proper factor
        # (only for species that have a mass)
        if quantity in ['ux', 'uy', 'uz']:
            if species.m>0:
                scale_factor = species.m * constants.c
                quantity_one_proc *= scale_factor
        if self.comm is not None:
            quantity_all_proc = self.comm.gather_ptcl_array(
                quantity_one_proc, n_rank, Ntot )
        else:
            quantity_all_proc = quantity_one_proc

        # Return the results
        return( quantity_all_proc )

```
I propose changing 
```
quantity_one_proc *= scale_factor
``` 
to 
```
quantity_one_proc = quantity_one_proc*scale_factor
```
which then doesn't affect the value used in the ongoing simulation.

**Comment by mjvstreeter** [comment]
This is not a bug in FBPIC. I created it with a custom diagnostic that I made and so it won't occur for anyone else. Sorry for the false alarm!

**Comment by RemiLehe** [comment]
OK, thanks for letting us know :)
