### ISSUE TITLE
Issue with ionization in boosted frame

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#468]
Hi,

I had an issue when I was trying to run ionization injection simulations in boosted frame. 
As you can see from the plot I attached here, in the first case where the nitrogen density is low, everything looks normal. But when I increased the nitrogen density by a factor of 100, as in case II, the results seem to be unreasonable.
I have also attached the input files for both cases (and the only difference between the two is the nitrogen density).
I wonder if this is because each macroparticle represents too many physical particles in the high nitrogen density case?
Could anyone tell me how to prevent it happening or how to set parameters for simulations with ionization in the boosted frame properly?

Many thanks!
Yong

![ionization_boosted](https://user-images.githubusercontent.com/34725295/88361560-6e974180-cd47-11ea-82f9-019843fba1d6.png)

[InputDecks.zip](https://github.com/fbpic/fbpic/files/4970224/InputDecks.zip)

**Comment by MKirchen** [comment]
Hey,

so there are a few things that seem problematic in your input script.
1) You have a resolution of 10 cells per micron only in the longitudinal direction. This should be at least 20, or ideally >40, especially when running boosted frame simulations with a large gamma_boost factor.
2) Your gamma_boost factor of 10 is already quite high for your physics setup. It should be fine, however it always makes sense to start testing your setup with a lower factor like 5.
3) As far as I can see from looking at your input script, you forgot to add the pre-ionized electrons from the first 5 levels of Nitrogen to the electron species. This would cause your plasma to be non-charge-neutral in the beginning, which might explain the instability that you see. Could you please carefully check and (potentially) correct that?


Here is an example from the documentation (ionization_script.py) that should make it clear:

```
    # Add the Helium ions (pre-ionized up to level 1),
    # the Nitrogen ions (pre-ionized up to level 5)
    # and the associated electrons (from the pre-ionized levels)
    atoms_He = sim.add_new_species( q=e, m=4.*m_p, n=n_He,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )
    atoms_N = sim.add_new_species( q=5*e, m=14.*m_p, n=n_N,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )
    # Important: the electron density from N5+ is 5x larger than that from He+
    n_e = n_He + 5*n_N
    elec = sim.add_new_species( q=-e, m=m_e, n=n_e,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )

    # Activate ionization of He ions (for levels above 1).
    # Store the created electrons in the species `elec`
    atoms_He.make_ionizable( 'He', target_species=elec, level_start=1 )

    # Activate ionization of N ions (for levels above 5).
    # Store the created electrons in a new dedicated electron species that
    # does not contain any macroparticles initially
    elec_from_N = sim.add_new_species( q=-e, m=m_e )
    atoms_N.make_ionizable( 'N', target_species=elec_from_N, level_start=5 )```

**Comment by YongMa1988** [comment]
Thank you very much for the quick reply! @MKirchen 
I will make the changes accordingly and update the results if necessarily.

**Comment by YongMa1988** [comment]
Hello, I can confirm that adding the pre-ionized electrons from Nitrogen to the electron species to maintain change neutrality  solved my issue. @MKirchen Thanks again!
