### ISSUE TITLE
How to diagnose multiple density distributions in boosted frame simulations?

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#472]
Hi,

I wonder how to diagnose multiple density distributions in boosted frame simulations? Fox example, how to output the density distribution for 'plasma_elec', 'plasma_ions' and 'bunch' in the example input deck?
It seems that only 'rho' is allowed in the field types of the 'BackTransformedFieldDiagnostic' function.

Many thanks,
Yong

**Comment by RemiLehe** [comment]
Thanks for this question, and sorry for the late reply.

Unfortunately, there currently no easy way to output the individual density distributions in boosted-frame simulations. (In lab-frame simulations, on the other hand, one can use `ParticleChargeDensityDiagnostic`, as you may already know.)

Implementing per-species density diagnostics for boosted-fame simulations would require quite a bit of work, so I am not sure whether it will be available soon. One alternative is to dump all the macroparticles, via `BackTransformedParticleDiagnostic` and then to reconstruct the density in post-processing.

**Comment by YongMa1988** [comment]
Hi Remi,
Many thanks for the suggestion!
Best,
Yong
