### ISSUE TITLE
Error while running the test script

### ISSUE THREAD

**Issue by faranirshad** [fbpic/fbpic#481]
Hello all, 

I recently started using fbpic code and was running into an error trying to run the code on a GPU in one of our Linux computers (Tesla V100). The traceback is given below and I also attach the output of the conda list for a description of the packages installed in this conda environment. 

(fbpic2) Faran.Irshad@gar-cn-laka01:/project/agkarsch/Faran/fbpic/runs/11$ python lwfa_script.py

FBPIC (0.17.1)

Running on GPU

Initializing laser pulse on the mesh...
Done.

Traceback (most recent call last):
  File "lwfa_script.py", line 148, in <module>
    sim.step( N_step )
  File "/home/f/Faran.Irshad/anaconda3/envs/fbpic2/lib/python3.8/site-packages/fbpic/main.py", line 407, in step
    self.comm.damp_EB_open_boundary( fld.interp )
  File "/home/f/Faran.Irshad/anaconda3/envs/fbpic2/lib/python3.8/site-packages/fbpic/boundaries/boundary_communicator.py", line 850, in damp_EB_open_boundary
    cuda_damp_EB_left[dim_grid, dim_block](
  File "/home/f/Faran.Irshad/anaconda3/envs/fbpic2/lib/python3.8/site-packages/fbpic/utils/cuda.py", line 331, in call_kernel
    numba_kernel.entry_name)
AttributeError: 'Dispatcher' object has no attribute 'entry_name'

the output of the conda list is as follows:-

(fbpic2) Faran.Irshad@gar-cn-laka01:/project/agkarsch/Faran/fbpic/runs/11$ conda list
# packages in environment at /home/f/Faran.Irshad/anaconda3/envs/fbpic2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py38_0
cudatoolkit               10.0.130                      0
cupy-cuda100              7.8.0                    pypi_0    pypi
fastrlock                 0.5                      pypi_0    pypi
fbpic                     0.17.1                   pypi_0    pypi
h5py                      2.10.0           py38hd6299e0_1
hdf5                      1.10.6               hb1b8bf9_0
intel-openmp              2020.2                      254
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libllvm10                 10.0.1               hbcb73fb_5
libstdcxx-ng              9.1.0                hdf63c60_0
llvmlite                  0.34.0           py38h269e1b5_4
mkl                       2020.2                      256
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.1.0            py38h23d657b_0
mkl_random                1.1.1            py38h0573a6f_0
mpi                       1.0                     openmpi
mpi4py                    3.0.3            py38h246a051_1    conda-forge
ncurses                   6.2                  he6710b0_1
numba                     0.51.2           py38h0573a6f_1
numpy                     1.19.1           py38hbc911f0_0
numpy-base                1.19.1           py38hfa32c7d_0
openmpi                   4.0.2                hb1b8bf9_1
openssl                   1.1.1g               h7b6447c_0
pip                       20.2.2                   py38_0
python                    3.8.5                h7579374_1
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  h7b6447c_0
scipy                     1.5.2            py38h0b6359f_0
setuptools                49.6.0                   py38_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h62c20be_0
tbb                       2020.2               hfd86e86_0
tk                        8.6.10               hbc83047_0
wheel                     0.35.1                     py_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3

I also made sure that there is no other file in the output folder(dir output attached)

(fbpic2) Faran.Irshad@gar-cn-laka01:/project/agkarsch/Faran/fbpic/runs/11$ dir
lwfa_script.py

Any help in resolving this issue would be appreciated. Thanks

**Comment by MKirchen** [comment]
Hey,

I still need to look into this in detail, but from a quick analysis it seems that maybe `numba 0.51.0` introduced this issue.
Could you try to downgrade to `numba 0.50.0` and see if the issue persists?

Thanks,
Manuel

**Comment by faranirshad** [comment]
Hey 

Thanks for the quick response. So I tried this fix and downgrading seemed to work for my case. Thanks for the help. :)

Regards,
Faran

**Comment by RemiLehe** [comment]
@faranirshad Thanks for reporting this issue! 

It has now been fixed in the latest version of FBPIC (version `0.18.0`). If you update your local version of FBPIC with:
```
pip install --upgrade fbpic
```
then you should be able to run on GPU with the latest version of numba (currently `0.51.2`).

**Comment by faranirshad** [comment]
@RemiLehe No problem. Thanks for the update.
