### ISSUE TITLE
How to set the N_boosted_diag, N_lab_diag and write_period in boosted frame?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#487]
Hi, I am the first time to use the boost frame in LWFA simulation by FBPIC.  Here is my input file
[boosted_script.zip](https://github.com/fbpic/fbpic/files/5493663/boosted_script.zip)

The density I used is `0.8e18cm-3`, and the simulation length is 6.2e-2m, and I set the follows:
`gamma_boost = 20.
N_boosted_diag = 20+1
N_lab_diag = 195+1
write_period = 200
`
But the results in boosted frame and lab frame looks abnormal:
![image](https://user-images.githubusercontent.com/31507149/98230413-11419c00-1f96-11eb-98a1-d8d14fd3cf71.png)
![image](https://user-images.githubusercontent.com/31507149/98230662-5bc31880-1f96-11eb-8444-3129a9431c13.png)

Is anything I set wrong in simulation? or the `N_boosted_diag` and `N_lab_diag` parameter I set  uncorrectly? Thank you !

**Comment by MKirchen** [comment]
The simulation looks unstable. It is likely that the setup of the simulation is wrong. The issue does not seem to be related to the output diagnostics.

Please try to carefully revise the input script, making sure that you follow the same steps as in the example boosted frame script.
