### ISSUE TITLE
Boosted frame - Instability

### ISSUE THREAD

**Issue by OscarJakobssonResearch** [fbpic/fbpic#492]
Dear developers, 

When running boosted-frame simulation with open boundaries the simulation becomes unstable after a while. The plots below show the laser envelope and Ez. The small perturbation behind the main laser in the first plot is due to electron injection. After some propagation the laser deteriorates rapidly. This happens for 2 and 3 modes and for reflective and absorbing boundaries. Since this does not occur in un-boosted simulations I am assuming there is something wrong with the input script. Any help would be much appreciated. 

Thanks, 
Oscar

FBPIC v.018.0 was used for these tests.
![LaserEvelope_000000001](https://user-images.githubusercontent.com/55784067/99154428-9ff59d80-26a7-11eb-8985-a9201a8c3bfa.png)
![LaserEvelope_000000004](https://user-images.githubusercontent.com/55784067/99154431-a1bf6100-26a7-11eb-915a-deb1a86c689b.png)

![Ez_000000001](https://user-images.githubusercontent.com/55784067/99154284-8b64d580-26a6-11eb-869e-dcbcce2237d2.png) ![Ez_000000004](https://user-images.githubusercontent.com/55784067/99154288-8dc72f80-26a6-11eb-9096-d06f0403c39c.png)

[FilesBoostedInstability.zip](https://github.com/fbpic/fbpic/files/5541280/FilesBoostedInstability.zip)

**Comment by MKirchen** [comment]
Hey, thanks for posting your issue. First question: Do you also have the corresponding images for the un-boosted simulation for comparison?

**Comment by OscarJakobssonResearch** [comment]
Hi, 

We made a minimal working example for one of our simulations that had this issue. Having run the un-boosted version it seems that the same feature is there as well though. Good thing, the boosted and un-boosted look the same. I don't think this is the expect behaviour though. I have attached the un-boosted script. 




![LaserEvelope_000397756](https://user-images.githubusercontent.com/55784067/100347746-c12a8800-2fdd-11eb-8b7e-bb24c670ce47.png)
![LaserEvelope_001591024](https://user-images.githubusercontent.com/55784067/100347675-a2c48c80-2fdd-11eb-97d8-e44753b1822a.png)

![Ez_000397756](https://user-images.githubusercontent.com/55784067/100347753-c4257880-2fdd-11eb-81f6-fe6d340a4904.png)
![Ez_001591024](https://user-images.githubusercontent.com/55784067/100347682-a6f0aa00-2fdd-11eb-986f-3d646516ec3e.png)


[test_script.zip](https://github.com/fbpic/fbpic/files/5602749/test_script.zip)

**Comment by hightower8083** [comment]
With @Andreas we've saw something similar in a long distance propagation boosted-frame case -- the laser leaked its energy to some sort of THz wave (see attached field + evolution of laser spectrum in um). At that time, we've attributed it to a possible spatially unresolved SRS, but we did not check the non-boosted case (you may ping @Andreas in Slack).

![PastedGraphic-1](https://user-images.githubusercontent.com/22051570/100449758-c6a6d180-30b4-11eb-9fe3-dda126dcd301.png)

![anim_3e17](https://user-images.githubusercontent.com/22051570/100450059-49c82780-30b5-11eb-90ae-447f25839641.gif)

**Comment by RemiLehe** [comment]
@OscarJakobssonResearch Thanks for reporting this and for checking that the boosted and un-boosted simulation show the same phenomenon.

I guess that, at this point, there is no firm evidence that this is an numerical artifact rather than a real physical effect. Would you be able to run the same simulation at e.g. 2x higher/coarser resolution? If the deterioration of the laser is significantly different (e.g. amplitude/wavelength of the deteriorated laser changes significantly) as you change the resolution, then I guess this would support the hypothesis that this is a numerical artifact.

**Comment by MKirchen** [comment]
@OscarJakobssonResearch Did you gain more insight on this? Can we close this issue?

**Comment by OscarJakobssonResearch** [comment]
Ah, apologies for the late replay. 
Yes. Thank you for your help. 
Closing the issues now.
