### ISSUE TITLE
how to diagnose the plasma density in boosted frame?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#493]
Hi, developers,
      In lab frame, we can diagnose the plasma density, but in boosted frame, this seems to be not avilable. Because I have a plasma channel setting in the plasma density function in the script file. When I run in lab frame, I can confirm that this plasma channel is valid because I can diagnose the plasma density by openPMD, it shows a parabolic curve:
![image](https://user-images.githubusercontent.com/31507149/99799702-0f6b0180-2b6e-11eb-97cb-dae71ff76ef1.png)

But when running in the boosted frame, I use the same method (the same as to that used in lab frame case) to diagnose the plasma density, it shows a strange curve, which is not the parabolic:
![image](https://user-images.githubusercontent.com/31507149/99799747-27428580-2b6e-11eb-879d-5eff29d4a625.png)
Stranger still, the density value in the two picture above is quite different. 
So , is the plasma density diagnostic not avilable in the boosted frame?

**Comment by MKirchen** [comment]
Hey,

please note that rho by default is the charge density in the simulation, whereas in the lab frame you can also output the particle density (ParticleDensityDiagnostic). For a charge neutral plasma, the parabolic channel will not be visible in the charge density (rho).

In the boosted frame, we always model a charge neutral plasma, i.e. we have to include both, electrons and ions in the simulation. In this case, the parabolic channel is not visible in the charge density.
In the lab frame, we can often also simulate the (approximately exact) physics without the ions and thereby save some computational costs. In this case, the parabolic plasma channel should be visible in the charge density.

**Comment by QJohn2017** [comment]
Okay, thank you very much !
