### ISSUE TITLE
Is it able to set a inital energy distribution of the driven beam in PWFA ?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#499]
Hi, I want to do a beam driven wakefield acceleration simulation, and the driven beam I want to set has an initial energy and density   distribution. I used the function `fbpic.lpa_utils.bunch.add_particle_bunch` according to the guide documents https://fbpic.github.io/api_reference/lpa_utilities/beam.html, where the driven beam's density can be set just like the plasma density. But the lorentz factor can only be a constant and can not be a function of `(x, y, z)`. So, is there any way to set a Lorentz factor distribution function of (x, y, z) ?

**Comment by RemiLehe** [comment]
Thanks for your interest in the code.
I would recommend to use the function [add_particle_bunch_from_arrays](https://fbpic.github.io/api_reference/lpa_utilities/beam.html#fbpic.lpa_utils.bunch.add_particle_bunch_from_arrays): in this case, you can build the beam distribution that you want by hand, using `numpy` arrays, and then you can pass it to FBPIC (through `add_particle_bunch_from_arrays`) at the beginning of the simulation.

**Comment by QJohn2017** [comment]
Okay, thank you very much! I have tried it by using the function ` add_particle_bunch_from_arrays`, and it works for me, thank you again !
