### ISSUE TITLE
the injection looks weird in boosted frame

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#503]
Hi, When I run the LWFA in boost frame, the gamma =5, but the injection of electron looks weird:
![image](https://user-images.githubusercontent.com/31507149/102838862-29805400-443a-11eb-836b-f5e0fe1e2c27.png)
The first injection is normal and its sptial distribution is smooth, but the second injection looks intermittent and  tremble violently. Is this normal in FBPIC simulation?

**Comment by MKirchen** [comment]
Sorry, for the late answer.

What you observe is self-injection from transverse wavebreaking. 
The corresponding structure of the injected beam is not necessarily unusual.

However, it can be quite challenging to correctly model this injection process with any particle-in-cell code.
Getting physically meaningful results typically requires very high resolutions and careful convergence tests.
Especially in the boosted frame, self-injection can be over- or underestimated - in particular because the speedup comes at the price of a reduction in total number of macroparticles representing the plasma (this number decreases ~gamma^2).

**Comment by QJohn2017** [comment]
Thank you for your reply!@MKirchen
According to your perception, is this weird self-injection just caused by the  algorithm of the PIC code? It's possible that self-injection doesn't actually happen or the injection may not be like this, right ?
Actually, I have tried to increase the azimuthal mode to 3, and I also increase the precision of simulation box, that is 0.025um per cell in longitudinal and 0.15um per cell in transverse, and the Nm=3,  gamma_boost=5. But the simulation result is still the same:
![image](https://user-images.githubusercontent.com/31507149/109748290-96bb1d00-7c13-11eb-8a69-06b746880f39.png)

Furthermore, you also said that the  self-injection sometimes is over- or underestimated in boosted frame because a reduction in total number of macroparticles , is that means the simulated electron charge in lab frame is should be larger than that in boosted frame ? and If I simulated in boosted frame, the actual electron charge should be multiplied by gamma^2 ? Thank you very much !

**Comment by MKirchen** [comment]
Hey,

1) The self-injection is not a numerical artifact. Your wakefield looks quite nonlinear (strong blowout). Therefore it is not unlikely that wavebreaking occurs. However, **correctly** modelling this process requires typically requires a high resolution and enough macroparticle statistics. You should run convergence tests and compare with a lab frame simulation.


2) No you do not have to multiply by gamma^2. All the quantities are correctly initialized and transformed back to the lab frame when using the BackTransformed diagnostics.

**Comment by QJohn2017** [comment]
Thank you for your suggestions @MKirchen . I don't know how much precision it takes to make the result converge, because the length I simulated is long to 6 cm, so ,I can't compare the result with lab frame simulation. I tried to increase the precision like the above I mentioned, but the results are all the same. I don't mean that self-injection should not occured, I just want to eliminate the weird injection results. So, Besides improving the accuracy, do you have any other feasible suggestions for my long distance simulation?

**Comment by MKirchen** [comment]
We observed in the past that the asymmetric injection can occur when the laser is cut at the right edge of the simulation box. Therefore, you could check if the results change if you leave more space between the right edge of the box and the centroid of the laser.

**Comment by QJohn2017** [comment]
@MKirchen , Thank you very much !  When I increase the space between the right edge of the box and the laser front, the asymmetric injection decreased much ! Thank you agian, I now closed this issue.
