### ISSUE TITLE
fbpic install on ppc64 (IBM power9) architecture (Bede HPC system)

### ISSUE THREAD

**Issue by abonatto** [fbpic/fbpic#504]
Dear Developers,

I understand that this is not an fbpic issue (my apologies in advance, if the question is not suitable for this session), but I would like to ask you if you are aware of any successful fbpic install on a ppc64 architecture.

We recently got access to the new Bede GPU HPC system (https://n8cir.org.uk/supporting-research/facilities/nice/hardware/), built upon IBM Power9 processors and Nvidia V100 GPUs, in which we intend to install and use fbpic. However, when trying to install it on Bede, we realized that -- although cuda and fftw modules are available to be loaded -- there are no pyfftw and cupy distributions available for the ppc64 architecture (we tried to install them by using conda/conda-forge, and pip).

Since this is the first time I am trying to install fbpic on a non-x86 architecture, any information you can provide about this matter will be really appreciated.

Kind Regards,

Alex

**Comment by abonatto** [comment]
Update:

By loading gcc/8.4.0 and cuda/10.2.89 modules, by using pip I managed to install cupy from source. Regarding pyFFTW, I opened an issue on their github (https://github.com/pyFFTW/pyFFTW/issues/300), and I received some directions, which I will try and update you later about the outcome.

**Comment by RemiLehe** [comment]
Thanks for raising this issue, and for the update.
We did install fbpic on the Summit supercomputer, which has a ppc64 architecture. You can find the instructions [here](https://fbpic.github.io/install/install_summit.html). Unfortunately, each cluster is different (especially because of different available module). In particular, in the case of Summit, `fftw` and `cupy` where already available in modules.

**Comment by abonatto** [comment]
Thanks for this info, @RemiLehe.

after loading the following modules on Bede,

```
module load cuda/10.2.89 gcc/8.4.0 openmpi/4.0.5 fftw/3.3.8
```

I tried to install pyfftw by using pip (`pip install pyfftw --user`), and I had the following error,
```
...
Build pyFFTW with support for FFTW with
  double precision + openMP
  single precision + openMP
  long precision + openMP
  building 'pyfftw.pyfftw' extension
  error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
...
```
After a quick search, I found that it could be solved by installing cython, which I did (`pip install cython --user`) and managed to have pyfftw successfully installed. However, when I try to use it in python (`import pyfftw`), I get the following error,

```
>>> import pyfftw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/.../.local/lib/python3.8/site-packages/pyfftw/__init__.py", line 18, in <module>
    from .pyfftw import (
ImportError: /users/abonatto/.local/lib/python3.8/site-packages/pyfftw/pyfftw.cpython-38-powerpc64le-linux-gnu.so: undefined symbol: omp_get_thread_num
```
which seems to be related to OpenMP. I tried loading / using an `llvm/11.0.0` module which is also available , with no success. I will keep investigating how to solve this issue (if you have any guess, please let me know).

**Comment by abonatto** [comment]
Update 2:

By setting the environment variable `PYFFTW_USE_PTHREADS = True`, in order to use posix threads, and forcing pip to recompile pyfftw from source,
```
pip install --user --force-reinstall --ignore-installed --no-binary :all: pyfftw
```
I managed to have pyfftw working on Bede (https://github.com/pyFFTW/pyFFTW/issues/300). However, I am now experiencing cuda errors:

```
FBPIC (0.19.1)

Running on GPU 

Initializing laser pulse on the mesh...
Done.

Just-In-Time compilation (up to one minute) ...Traceback (most recent call last):
  File "lwfa_script.py", line 148, in <module>
    sim.step( N_step )
  File "/.../fbpic/lib/python3.8/site-packages/fbpic/main.py", line 446, in step
    self.deposit('rho_prev', exchange=(use_true_rho is True))
  File "/.../fbpic/lib/python3.8/site-packages/fbpic/main.py", line 628, in deposit
    species.deposit( fld, 'rho' )
  File "/.../fbpic/lib/python3.8/site-packages/fbpic/particles/particles.py", line 887, in deposit
    deposit_rho_gpu_linear[
  File "/.../fbpic/lib/python3.8/site-packages/fbpic/utils/cuda.py", line 361, in call_kernel
    numba_kernel = cuda.jit()(self.python_func) \
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/compiler.py", line 844, in specialize
    kernel = self.compile(argtypes)
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/compiler.py", line 863, in compile
    kernel.bind()
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/compiler.py", line 604, in bind
    self._func.get()
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/compiler.py", line 480, in get
    ptx = self.ptx.get()
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/compiler.py", line 450, in get
    ptx = nvvm.llvm_to_ptx(self.llvmir, opt=3, arch=arch,
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 515, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/.../fbpic/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (208, 17): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION
```
Cupy has been compiled from source, after loading a cuda/10.2.89 module. I will keep trying to solve (as usual, any suggestion will be appreciated).

**Comment by RemiLehe** [comment]
Thanks for the update.
This issue seems similar to [this one](https://github.com/fbpic/fbpic/issues/458).
Could you try to downgrade to `numba 0.49` to see if it fixes the issue?

**Comment by abonatto** [comment]
Dear @RemiLehe,

After downgrading numba (0.49.1), fbpic is now working on Bede! Thanks for your support.

**Comment by RemiLehe** [comment]
Great! Thanks for the update!
