### ISSUE TITLE
Radial boundary conditions: reflective vs open

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#511]
Changing the boundary conditions for `r` from `"open"` to `"reflective"` seems to alter the LWFA simulation results, even when considering a relatively large box. Also surprisingly, the runtime for the `"reflective"` case is 7% longer than the `"open"` case.

Here is a comparison of the 2D electron charge vs (energy, z) histogram for the two cases. All other parameters are identical, including the seed for the random number generator.

![hist2d_open](https://user-images.githubusercontent.com/4405658/107154149-0d992900-697a-11eb-8d32-ddb33d55f8f3.png)
![hist2d_reflective](https://user-images.githubusercontent.com/4405658/107154151-0f62ec80-697a-11eb-965d-53fd564efeb6.png)

The top plot is for `"open"` BC, while the bottom one shows the `"reflective"` case. Notice how the ~210 MeV main peak of the  `"reflective"` case splits in two and moves to lower energy in the `"open"` case.

**Comment by berceanu** [comment]
For completeness, here are the time evolutions of the `rho` and `E` fields during the two runs.

Reflective case:
https://user-images.githubusercontent.com/4405658/107154266-b051a780-697a-11eb-8256-8984b74ecc5f.mp4

Open case:
https://user-images.githubusercontent.com/4405658/107154291-d0816680-697a-11eb-82c5-3cc40f87b6ee.mp4

**Comment by berceanu** [comment]
And the two `Python` [scripts](https://gist.github.com/berceanu/4b368a42f27d93a2ec2d19d3defbe66c).

**Comment by RemiLehe** [comment]
Thanks for reporting this issue, and sorry for the late reply.
It seems that having some plasma close to the absorbing open boundary is usually somewhat unstable (this has also been observed by other people, and in other PIC codes as well - including Cartesian PIC codes). To my knowledge, this instability is not really understood (e.g. there is no corresponding stability theory that explains it).
At this point, one work-around consists in leaving some space with no plasma, close to the boundary (i.e. in FBPIC, by using `p_rmax` to initialize the plasma only up to a certain radius).

**Comment by enrico5** [comment]
I found that sometimes increasing `n_damp` works better than increasing the space with no plasma. For example, using `n_damp={'z': 64, 'r': 256}` as parameter to `Simulation`.

**Comment by MKirchen** [comment]
Thanks @enrico5 for the suggestion. 

@berceanu : It would be interesting to know if increasing `n_damp` helps in your case. If so, we might consider to increase the default value. Also, please let us know wether or not the suggestions of @RemiLehe helped.

**Comment by berceanu** [comment]
Yes, using `p_rmax` at about 90% of `rmax` completely solved the issue. I didn't try increasing `n_damp` yet.

**Comment by MKirchen** [comment]
Okay great! If you don't have any further questions, feel free to close this issue.
