### ISSUE TITLE
MPS support

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#512]
If my understanding is correct, NVIDIA's [MPS](https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf) would allow multiple CUDA applications to share the resources of a single GPU, on modern architectures. Would this be possible with `fbpic`?

**Comment by RemiLehe** [comment]
Thanks for the question.
In fact, even with the current version of `fbpic`, you can already run several simulations on the same GPU. (e.g. if you have a single GPU and launch several simulations - or launch a [parameter scan with several MPI ranks](https://fbpic.github.io/advanced/parameter_scans.html) -, then the simulations will all use that single GPU simultaneously.)

My understanding of MPS is that it reduces some of the overheads that may occur in this configuration. However, it is not clear to me that these overheads are really important for `fbpic` use cases. Therefore, we never really invest time in investigating how to use MPS.

Does that answer your question?
