### ISSUE TITLE
Segfault when enabling hyper-threading on DGX-2

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#513]
`fbpic 0.19.0` gives a reproducible segfault every time I enable hyper-threading on the DGX-2. 

```
FBPIC (0.19.0)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
Open MPI v4.0.5, package: Open MPI conda@661d468a338a Distribution, ident: 4.0.5, repo rev: v4.0.5, Aug 26, 2020
CUDA available: Yes
Compute architecture: GPU (CUDA)
CUDA GPUDirect (MPI) enabled: No
FBPIC selected a Tesla V100-SXM3-32GB GPU with id 0

PSATD stencil order: infinite
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: open
Guard region size: 64 cells
Damping region size: 64 cells
Injection region size: 32 cells
Particle exchange period: every 14 step
Boosted frame: False

Initializing laser pulse on the mesh...
OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
[thor:20143] *** Process received signal ***
[thor:20143] Signal: Segmentation fault (11)
[thor:20143] Signal code: Address not mapped (1)
[thor:20143] Failing at address: 0x528
Segmentation fault (core dumped)
```

The simulation runs fine when disabling HT, either from BIOS or via https://serverfault.com/a/967597/616139.

script [here](https://gist.github.com/berceanu/4b368a42f27d93a2ec2d19d3defbe66c)

**Comment by berceanu** [comment]
Without HT and `verbose_level=2`

```
FBPIC (0.19.0)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
Open MPI v4.0.5, package: Open MPI conda@661d468a338a Distribution, ident: 4.0.5, repo rev: v4.0.5, Aug 26, 2020
CUDA available: Yes
Compute architecture: GPU (CUDA)
CUDA GPUDirect (MPI) enabled: No
FBPIC selected a Tesla V100-SXM3-32GB GPU with id 0

PSATD stencil order: infinite
Particle shape: linear
Longitudinal boundaries: open
Transverse boundaries: open
Guard region size: 64 cells
Damping region size: 64 cells
Injection region size: 32 cells
Particle exchange period: every 14 step
Boosted frame: False

Initializing laser pulse on the mesh...
OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Done.

|                                   | 353/63487, 1:34:42 left, 63 ms/step
```

**Comment by berceanu** [comment]
When running with
```
export FBPIC_DISABLE_THREADING=1
export MKL_NUM_THREADS=1
export NUMBA_NUM_THREADS=1
export OMP_NUM_THREADS=1
```
the issue doesn't appear, so it seems to be threading-related indeed.

**Comment by RemiLehe** [comment]
Thanks for reporting this issue. 
This is interesting. I am assuming this comes from one of our dependencies (e.g. maybe `numba` or MPI), but it would be nice to isolate it, so that we can report it directly to them. 

Could you try to run the CUDA tests from `numba`, in order to see if you get the same error?
```
python -m numba.runtests numba.cuda.tests
```

Also, could you try to uninstall `mpi4py` and rerun the above FBPIC simulation, to see whether MPI is the source of the segfault?

**Comment by berceanu** [comment]
I ran the `numba` tests.

```
Ran 665 tests in 127.593s

FAILED (failures=20, errors=1, skipped=7)
```

**Comment by berceanu** [comment]
Running without `mpi4py` results in the same segfault.

**Comment by RemiLehe** [comment]
Sorry for the late reply!
This is interesting: some `numba` tests do fail, but not with the same segfault...
At this point, it is unclear to me how to debug this. Since you do have a work-around (i.e. setting the threading-related environment variables, as you mentioned above), I would suggest to simply use this.

**Comment by MKirchen** [comment]
You might want to try changing the threading layer, e.g. to TBB, as the issue seems to be related to OpenMP.
For details check: https://numba.pydata.org/numba-doc/latest/user/threading-layer.html
