### ISSUE TITLE
add_particle_bunch() function with nonuniform distribution

### ISSUE THREAD

**Issue by rogerpnunes** [fbpic/fbpic#518]
Hi all,

I was trying to implement a beam with some specific dens(r,z) function. Everything work fine for the beam density when I inspect the results. However, when I analyze the particle's spatial positions, it can be perceived that they are equally spaced, creating a regular distribution in space. I have read in manual that add_particle_bunch() generates "Uniform particle distribution with weights according to density function." In this way, the following question arises: is it possible to change this same function to generate a "**NON**uniform particle distribution with weights according to density function."?

Many thanks for your attention,

Roger Pizzato Nunes

**Comment by MKirchen** [comment]
Hey @rogerpnunes,

There are usually two preferred ways to initialize a bunch. Both are valid for generating a non-uniform beam.

1) Initialize an equally spaced (uniform) distribution of macroparticles and **set their weights to resemble a non-uniform distribution**.
2) Directly create a non-uniform distribution of particles **where all particles have the same weight**. (An example for this would be the function `add_particle_bunch_gaussian()`, which creates a 3D Gaussian beam distribution where all particles have equal weights)

You chose option 1 and by specifying `dens(r,z)` you obtained a non-uniform beam, which should be fine. Be sure, however, to always take the weight of the particles into account during the post-analysis.

You could also chose option 2. This would require you to pre-create the non-uniform particle distribution and use the function  `add_particle_bunch_from_arrays()` to add it to the simulation. This function would also allow you to combine a non-uniform particle distribution with non-uniform weights, in case you really need that.

**Comment by rogerpnunes** [comment]
Hi Manuel,

Many thanks for your reply.

OK. I would like to remove the regular aspect I have obtained using option 1 when I use the particles’ coordinates in a plot. Please, see the image attached. I think if I use a random (which is quasi-uniform) distribution os particles (creating random values for r and z) with a dens(r,z) function for weighting, the shells observed in the attached figure can be removed.

Thank you again.

--
Roger Pizzato Nunes
***@***.***

**Comment by MKirchen** [comment]
Hey @rogerpnunes,

Unfortunately, the image seems to be missing. Please try to post it directly on the github webpage. Maybe I have an idea for a better plotting solution.

Anyways, the solution that you proposed should work. 

You can also have a look at the code of `add_particle_bunch_gaussian()` ([link](https://github.com/fbpic/fbpic/blob/273e1e4e4d998828901024b3577fd49a4da00e1e/fbpic/lpa_utils/bunch.py#L114)) to get inspiration for how to create a customized non-uniform distribution with equal weights.

**Comment by rogerpnunes** [comment]
Hi Manuel,

Please find attached the figure. 
[x_y_00000000.pdf](https://github.com/fbpic/fbpic/files/6118626/x_y_00000000.pdf). Please, let me know if you can see it now.

Many thanks again,

Roger

**Comment by MKirchen** [comment]
I see. Ideally you could try to plot the phase space as a 2D histogram (and passing the weights) instead of a scatter plot.
A scatter plot will also only be "correct" if the particles weights are all equal.

However, if you just want to get a plot without discrete features, you can of course try to use the random approach you proposed. For that you could modify the particle positions right after you created the bunch.

For example, to multiply the x coordinate with 3, one has to do the following:
```
bunch = add_particle_bunch()
bunch.x *= 3
```

**Comment by rogerpnunes** [comment]
OK. I understood. I will try to modify the particles' coordinates from a regular to random dispersion, changing the spatial coordinates of the bunch object. This tip is fine. When I have the results, I will give a feedback here.

Many thanks.

Roger

**Comment by MKirchen** [comment]
I will close this issue for now.
