### ISSUE TITLE
How to plot the figure in the issue #511?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#519]
Hi @RemiLehe and @berceanu,

I want to know how to plot the figure in issue #511, which is  2D electron charge vs (energy, z) histogram? Can you teach me? Thank you very much !

**Comment by berceanu** [comment]
Hi @QJohn2017 , not sure this qualifies as an `fbpic` issue per se, but if you're interested, you could have a look [in this repo](https://github.com/berceanu/signac-driven-fbpic/blob/d4d8e8b963cd65fee509ba7496d9ba8f1c9aea60/signac/src/project.py#L431) for instance.

**Comment by QJohn2017** [comment]
@berceanu okay, thank you for your reply! I have already draw it out ! But  thanks for the advice all the same.

**Comment by berceanu** [comment]
Awesome, feel free to close the issue if you have no further questions.
