### ISSUE TITLE
Laser Classes

### ISSUE THREAD

**Issue by soerenjalas** [fbpic/fbpic#52]
To have a more flexible way of initializing laser beams in a simulation we could introduce laser classes which are passed to the antenna or the direct initialization.

I would propose something like this:

In profiles.py define classes like

```python
class GenericLaser(object)
def __init__(a0, w0, lambda, boost, ...):
# The class contains all information about the laser.
    self.a0 = a0
    self.w0 = w0
    self.lambda = lambda
def profile(z,r,t):
# A function that only depends on time and space coordinates
    return E
```

These objects would then be passed to `LaserAntenna()` or `add_laser()` as  a parameter `laser` where then laser.profile(z,r,t) would be called.
For a user it would look like this

```python
sim = Simulation(...)
laser = FancyLaserClassIMade(a0=12345)
add_laser(sim, laser=laser)
step(10000)
```

The benefit of this would be that I think it declutters the code a little since all laser parameters only live in profiles.py and that the user can define a custom laser in his input script. Plus, as all the laser information is stored in an object it could be used for e.g. a simulation preview plot etc.

**Comment by MKirchen** [comment]
Just a quick comment:

We want to have a function sim.add_laser(LaserObject, method="antenna", boost=BoostConverter),
where "boost" is optional. In the ideal case, the boost object would be attached to sim (e.g. sim.boost = BoostConverter) and sim.add_laser would then use this boost converter by default to boost any laser that is added to the simulation.

**Comment by MKirchen** [comment]
Should we close this issue? @RemiLehe

**Comment by RemiLehe** [comment]
Yes, it is now implemented (in a slightly different form) in the `dev` branch.
