### ISSUE TITLE
Increase output frequency of BackTransformed diagnostics at a specific moment of simulation

### ISSUE THREAD

**Issue by APicksleyLaser** [fbpic/fbpic#526]
Hi fbpic team,
Is it possible to increase the output frequency of BackTransformed diagnostics at a specific moment of the simulation? For example, like achieved in pull request #34 ? Could the iteration_min and iteration_max args be added to BackTransformed classes too?
Alex

**Comment by MKirchen** [comment]
Hey,

there is no direct way to do this at the moment, but you can get there by (1) creating a diagnostic object with a high output frequency and (2) removing the outputs (_snapshots_) that you don't need.

When you created a BackTransformed diagnostics `diag`, you can access a list of the different snapshots via `diag.snapshots`. From this list, you can remove all the snapshots that you do not need.

For example, to remove the first three snapshot of the list, you could do `del diag.snapshots[:3]`.

**Comment by APicksleyLaser** [comment]
This works well, thanks!
