### ISSUE TITLE
Incompatibility with Cupy 9

### ISSUE THREAD

**Issue by lauridsj** [fbpic/fbpic#531]
FBPIC does not work with the newest version of Cupy (9.0.0). Apparently, the cuBLAS call is the problem; it gives the following error: 

```
Traceback (most recent call last):
  File "test_linear_wakefield.py", line 345, in <module>
    test_linear_wakefield( Nm=1, show=show )
  File "test_linear_wakefield.py", line 116, in test_linear_wakefield
    sim.step(N_step, correct_currents=correct_currents)
  File "/beegfs/desy/group/lux-users/simulations/laurids/miniconda3/lib/python3.8/site-packages/fbpic/main.py", line 410, in step
    fld.interp2spect('E')
  File "/beegfs/desy/group/lux-users/simulations/laurids/miniconda3/lib/python3.8/site-packages/fbpic/fields/fields.py", line 328, in interp2spect
    self.trans[m].interp2spect_scal(
  File "/beegfs/desy/group/lux-users/simulations/laurids/miniconda3/lib/python3.8/site-packages/fbpic/fields/spectral_transform/spectral_transformer.py", line 177, in interp2spect_scal
    self.dht0.transform( self.spect_buffer_r, spect_array )
  File "/beegfs/desy/group/lux-users/simulations/laurids/miniconda3/lib/python3.8/site-packages/fbpic/fields/spectral_transform/hankel.py", line 192, in transform
    cublas.dgemm(self.blas, 0, 0, self.Nr, 2*self.Nz, self.Nr,
  File "cupy_backends/cuda/libs/cublas.pyx", line 854, in cupy_backends.cuda.libs.cublas.dgemm
  File "cupy_backends/cuda/libs/cublas.pyx", line 863, in cupy_backends.cuda.libs.cublas.dgemm
  File "cupy_backends/cuda/libs/cublas.pyx", line 394, in cupy_backends.cuda.libs.cublas.check_status
cupy_backends.cuda.libs.cublas.CUBLASError: CUBLAS_STATUS_INVALID_VALUE
```

Here is the official upgrade guide from cupy: [https://docs.cupy.dev/en/stable/upgrade.html#cupy-v9](https://docs.cupy.dev/en/stable/upgrade.html#cupy-v9)
I don't see anything there that could be the cause of this issue in terms of deprecations etc right now.

As an aside, Cupy 9 introduces a JIT compilation API similar to Numba (see the example [here](https://medium.com/cupy-team/cupy-v9-is-here-27e9cbfbf7e5)). I have not looked at it in detail, but it might be worth to check out; in the long term, maybe we can move away from Numba entirely.

**Comment by lauridsj** [comment]
I investigated this issue further, and the offending code is indeed the cuBLAS call in the Hankel transform:  (https://github.com/fbpic/fbpic/blob/dev/fbpic/fields/spectral_transform/hankel.py)

```
cuda_copy_2dC_to_2dR[self.dim_grid, self.dim_block]( F, self.d_in )
            # Call cuBLAS gemm kernel
            cublas.dgemm(self.blas, 0, 0, self.Nr, 2*self.Nz, self.Nr,
                         1, self.d_M.data.ptr, self.Nr,
                            self.d_in.data.ptr, self.Nr,
                         0, self.d_out.data.ptr, self.Nr)
            # Convert F-order, real `d_out` to the C-order, complex `G`
            cuda_copy_2dR_to_2dC[self.dim_grid, self.dim_block]( self.d_out, G )
```

Apparently, something in Cupy's internal API changed. However, when staring at this, I wondered why we don't simply use `cupy.dot` for the matrix multiplication (similar how we use `np.dot` in the CPU case)? This would make the code a lot simpler and should be equally fast since Cupy already uses cuBLAS under the hood.

**Comment by MKirchen** [comment]
We intentionally use the low-level call. During the initial implementation, we noticed that `cupy.dot` a lot slower due to overhead.

**Comment by lauridsj** [comment]
I actually checked the runtimes right now - cupy.dot seems to be equally fast for me; the difference is less then a ms per step. Maybe the slow overhead still comes from the times when the arrays were defined using numba?

**Comment by MKirchen** [comment]
Thanks for checking! Maybe they reduced some overhead in cupy (As far as I remember, we tested performance with cupy arrays). Still, just from experience, I would favor keeping the low-level call. However, if we cannot easily fix it, we can definitely consider using the high-level call instead.

**Comment by lauridsj** [comment]
Sure, sounds good!

**Comment by RemiLehe** [comment]
I did some more tests, in particular looking at `cupy`'s intermediate `git` tags between the official releases. It seems that the error happens between `9.0.0a2` and `9.0.0b1`.

**Comment by RemiLehe** [comment]
Hm, I am guessing that the issues is due to this PR:
https://github.com/cupy/cupy/pull/4263

**Comment by RemiLehe** [comment]
I tried to fix this with [this commit](https://github.com/RemiLehe/fbpic/commit/a0d073636f2a9f7a368a4fc56d09239f7569ef06), but it does not seem to work...

**Comment by RemiLehe** [comment]
Ah, it's just that I did not apply the same change to the inverse_transform.
I think that [this branch](https://github.com/RemiLehe/fbpic/tree/try_fix_cupy) now works with cupy 9.0 ... but not with cupy 8.X.

**Comment by MKirchen** [comment]
Hey @RemiLehe, yes @lauridsj and me came to the same conclusion during an offline discussion yesterday. Thanks for testing this already. As a side note to your commit: I guess we should pre-create cupy arrays for 1 and 0 during initialization to get the best performance. Concerning compatibility, should we just try to support both by checking for the cupy version when we create the variables before passing them?

**Comment by RemiLehe** [comment]
Yes, I fully agree with the above (both pre-creating the arrays for 1 and 0, and checking the cupy version). Would you have time to create a corresponding PR? Otherwise I could do it this evening.

**Comment by MKirchen** [comment]
Yes, I can prepare a PR

**Comment by RemiLehe** [comment]
Closed by https://github.com/fbpic/fbpic/pull/532
