### ISSUE TITLE
plot of E with the respect to z

### ISSUE THREAD

**Issue by mehdiabedi1234** [fbpic/fbpic#535]
Dear all,
I have a question. How can I have a plot  for LWFA including Electric field (E) with respect to Z  (i.e., vertical axis= E & horizontal= z)

**Comment by lauridsj** [comment]
Hi, thanks for your question!

You can use openpmd_viewer to retrieve the longitudinal electric field, like so:
```
from openpmd_viewer import OpenPMDTimeSeries
import matplotlib.pyplot as plt

ts = OpenPMDTimeSeries('./your_sim/diags/hdf5/') # open the simulation

Ez, meta = ts.get_field("E", "z", iteration=10) # retrieve the Ez field

Ez_axis = Ez[len(meta.r)//2,:] # take a lineout on the axis

plt.plot(meta.z, Ez_axis) # plot the field using matplotlib
plt.show()
```

I hope this helps!

Cheers,
Laurids

**Comment by RemiLehe** [comment]
Note that there is also a little short-cut to do this, in recent versions of `openPMD-viewer`:
```
from openpmd_viewer import OpenPMDTimeSeries

ts = OpenPMDTimeSeries('./your_sim/diags/hdf5/') # open the simulation

ts.get_field( "E", "z", iteration=10, slice_across='r', plot=True ) # generates the plot directly
```

**Comment by mehdiabedi1234** [comment]
> Hi, thanks for your question!
> 
> You can use openpmd_viewer to retrieve the longitudinal electric field, like so:
> 
> ```
> from openpmd_viewer import OpenPMDTimeSeries
> import matplotlib.pyplot as plt
> 
> ts = OpenPMDTimeSeries('./your_sim/diags/hdf5/') # open the simulation
> 
> Ez, meta = ts.get_field("E", "z", iteration=10) # retrieve the Ez field
> 
> Ez_axis = Ez[len(meta.r)//2,:] # take a lineout on the axis
> 
> plt.plot(meta.z, Ez_axis) # plot the field using matplotlib
> plt.show()
> ```
> 
> I hope this helps!
> 
> Cheers,
> Laurids
Dear Laurids:
Thank you for your help. It works, successfully.
Kind regards,

**Comment by mehdiabedi1234** [comment]
> Note that there is also a little short-cut to do this, in recent versions of `openPMD-viewer`:
> 
> ```
> from openpmd_viewer import OpenPMDTimeSeries
> 
> ts = OpenPMDTimeSeries('./your_sim/diags/hdf5/') # open the simulation
> 
> ts.get_field( "E", "z", iteration=10, slice_across='r', plot=True ) # generates the plot directly
> ```

Dear RemiLehe:
Many thanks for your answer.
Cheers

**Comment by RemiLehe** [comment]
Glad that this helped :)
