### ISSUE TITLE
Custom laser profiles

### ISSUE THREAD

**Issue by mehdiabedi1234** [fbpic/fbpic#536]
Dear All,
I saw there are below shaped laser profiles in FBPIC, including, Gaussian profile, Laguerre-Gauss profile, Donut-like Laguerre-Gauss profile, Flattened Gaussian profile, Few-cycle profile. I have a question: How can I add other shaped laser beams in FBPIC? For example, Bessel beam, cosh-Gaussian laser beam and so on. I have so many thanks for your help in advanced.
Kind regards,
Mehdi

**Comment by RemiLehe** [comment]
Hi @mehdiabedi1234 
Please see [this section](https://fbpic.github.io/api_reference/lpa_utilities/laser.html#creating-your-own-custom-laser-profile) of the documentation. You would essentially create a Python class **inside your input script** that represents the laser profile (using a similar syntax as [this class](https://github.com/fbpic/fbpic/blob/dev/fbpic/lpa_utils/laser/laser_profiles.py#L104)), and you would then pass an instance of this class to `add_laser_pulse`.

Does that make sense?

**Comment by mehdiabedi1234** [comment]
> Hi @mehdiabedi1234
> Please see [this section](https://fbpic.github.io/api_reference/lpa_utilities/laser.html#creating-your-own-custom-laser-profile) of the documentation. You would essentially create a Python class **inside your input script** that represents the laser profile (using a similar syntax as [this class](https://github.com/fbpic/fbpic/blob/dev/fbpic/lpa_utils/laser/laser_profiles.py#L104)), and you would then pass an instance of this class to `add_laser_pulse`.
> 
> Does that make sense?

Dear Dr. Remil Lehe:
Thank you for your quickly response. I've used your help.
Cheers,
Mehdi
