### ISSUE TITLE
run / compilation error (on Ubuntu 20.4)

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#543]
Dear Developers,

This is the first time I am trying to install and use FBPIC. On my first attempt I got some compilation error. 

Please, find attached the error report in the file FBPIC_running_error.txt. 

Installation procedure I followed:

======================================================

(1) Anaconda installation

downloaded 64-Bit(x86) Installer → for Linux

sha256sum /home/naveen/Downloads/Anaconda3-2021.05-Linux-x86_64.sh

bash ~/Downloads/Anaconda3-2021.05-Linux-x86_64.sh 

source ~/.bashrc

conda init

conda config --set auto_activate_base False

(2) Installation of FBPIC code

conda install numba scipy h5py mkl

conda install -c conda-forge mpi4py

pip install fbpic

======================================================

Any help to fix the compilation error is appreciable. 

Thank you.

[FBPIC_running_error.txt](https://github.com/fbpic/fbpic/files/6827249/FBPIC_running_error.txt)

**Comment by ncpathak** [comment]
Sorry in my previous message the FBPIC_running_error.txt file is empty. Please, find attached the error file once again.

Thank you.

[FBPIC_running_error.txt](https://github.com/fbpic/fbpic/files/6827314/FBPIC_running_error.txt)

**Comment by ncpathak** [comment]
With few more attempts I am able to run the test script but still looks like not a smooth running of the test simulation. 

The message is:

FBPIC (0.20.3)

Running on CPU with 2 MPI processes (16 threads per process) 

Initializing laser pulse on the mesh...
Done.

Traceback (most recent call last):
  File "lwfa_script.py", line 134, in <module>
    restart_from_checkpoint( sim )
  File "/home/naveen/.local/lib/python3.8/site-packages/fbpic/openpmd_diag/checkpoint_restart.py", line 135, in restart_from_checkpoint
    check_restart( sim, iteration, checkpoint_dir )
  File "/home/naveen/.local/lib/python3.8/site-packages/fbpic/openpmd_diag/checkpoint_restart.py", line 196, in check_restart
    raise RuntimeError('The directory %s, which is '
RuntimeError: The directory ./checkpoints, which is required to restart a simulation, does not exis

**Comment by lauridsj** [comment]
Hi @ncpathak, thanks for your question!

I unfortunately can't help you with your first error since I do not have an Ubuntu test system available. Regarding your second error: Can you check that, in your input script, `use_restart` is set to `False`? This flag should only be set when restarting a simulation, i.e. when the simulation has already run to a certain point and produced checkpoints to restart from.

**Comment by ncpathak** [comment]
Thank you so much for your useful suggestion. Now I set  "use_restart = False" . The test run seems to be working now ... (it is running on my desktop). 

Thank you once again.
