### ISSUE TITLE
Absolute charge calculation

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#545]
Dear all,

Could you please give some idea how to calculate the total amount of the self-injected charge in the LWFA simulation. 

Thank you.

**Comment by lauridsj** [comment]
Hi @ncpathak, thanks for your question!

Using openpmd_viewer, you can filter your charge by forward particle momentum, which then excludes particles from the wake. E.g., to get only charge with uz > 100 (approx. equal to gamma > 50):

```
from openpmd_viewer import OpenPMDTimeSeries
import numpy as np
from scipy.constants import e
import matplotlib.pyplot as plt

ts = OpenPMDTimeSeries("path/to/diags")

x,z,w = ts.get_particle(['x', 'z', 'w'], iteration=ts.iterations[-1], select={'uz': [100, None]}) # get the particles
np.sum(w) * e # calculate the charge, in C
```

You can also plot your beam by doing `plt.hist2d(z, x, weights=w, bins=100)`.

Hope this helps!
Cheers, Laurids

**Comment by ncpathak** [comment]
Dear Laurids,

Thank you so much for your help. I will follow your suggestions. 
Thank you once again.
