### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by kookjine** [fbpic/fbpic#547]
Dear developers,

Recently I am having trouble while running fbpic.
I keep having error message below when I run fbpic with slurm job scheduler. 

[pikachu03:222189] *** Process received signal ***
[pikachu03:222189] Signal: Segmentation fault (11)
[pikachu03:222189] Signal code: Address not mapped (1)
[pikachu03:222189] Failing at address: 0x1f0
/var/spool/slurmd/job03401/slurm_script: line 12: 222189 Segmentation fault      python lwfa_script.py

This message is from running example code of fbpic documentation, so relatively small simulation.
For both CPU and GPU simulations, I have same error messages.
It seems there exist some conflict between cluster and fbpic.
I guess this problem came up after I installed WARPX in my system, but not sure because this problem doesn't go away even after reinstalling entire anaconda package..
I tested with WARP to see if it's only cluster problem. 
WARP still works fine in the system using slrum job scheduler ..
I have no idea what's the problem. 

Do you have any idea about my issue?

Thanks a lot for reading,
Kook-Jin

**Comment by MKirchen** [comment]
Hey, 

Thanks for your question.
Since you get a segmentation fault, it's very difficult for us to predict the root cause of your issue.
It does not seem to be directly related to FBPIC, but might come from some incompatibility of the underlying software packages. Did you try to get in contact with the maintainers of the cluster? They probably can help you the best.

**Comment by MKirchen** [comment]
Maybe one suggestion to try: If your cluster supports interactive jobs, you could try to first launch and connect to an interactive session and then try to start the FBPIC simulation. Also, you should confirm that the correct Python distribution is used when launching the FBPIC simulation. You could try to submit a job that executes `which python` which should output the path to your anaconda distribution.

**Comment by kookjine** [comment]
Hi, 

FBPIC works fine interactively in login node.
The problem happens when I use job scheduler for using computing nodes.
It was working fine until last week and I didn't change anaconda distribution.
Maybe the problem is purely from this cluster..

Thank you for replying!

**Comment by kookjine** [comment]
I will close this report in a day in the case that someone is interested.

**Comment by MKirchen** [comment]
If it works on the login node but not on the compute node then there is maybe just a difference in the software environment that is loaded by the compute node. As I said before, you could investigate if the same python distribution is used when running on the compute node, and also wether or not the same software modules are loaded.

**Comment by kookjine** [comment]
Ah, yes. As you said I put the command 'which python' when submitting the job.
It gives same path (to anaconda package) as I run in login node.
