### ISSUE TITLE
Discrepancy in plasma density

### ISSUE THREAD

**Issue by dmargarone** [fbpic/fbpic#549]
Hi guys,

Hope you all are well and having great time. 

I used the LWFA test script given in the documentation (https://fbpic.github.io/example_input/lwfa_script.html). The maximum plasma density used in this script is:  n_e = 4.e18*1.e6 # Density (electrons.meters^-3)

However, when I used this script to make some test, I found that the maximum plasma density is 6.46e18 cm^-3, instead of the given value of 4.0e18 cm^-3. 

In the script (https://fbpic.github.io/example_input/lwfa_script.html), I change "a0=0" because I only want to see the plasma density profile. 

I made the 1D line plot along r=0 (as suggested to me yesterday). Please, see the attached file.

I used the conversion from "rho" to plasma density ("Ne") as: Ne = (rho / 1.6e-19)*1.0e-6 (cm^-3).
[rho = density * charge]

Please, could you let me know why there is a discrepancy in the maximum plasma density.

Thank you.
DM

[plasma_density.pdf](https://github.com/fbpic/fbpic/files/6921297/plasma_density.pdf)

**Comment by dmargarone** [comment]
Hi,

I always get "1.6159276316779284" times higher value of the plasma density than what I set. Do you have any idea why it is so ?

For example, for n_e = 5.e18*1.e6 # Density (electrons.meters^-3), I get 8.079638158389642e+24
and for n_e = 5.e18*1.e6, I get 1.6159276316779284e+24. 

I use the function:

# The density profile
ramp_start = 30.e-6
ramp_length = 40.e-6

def dens_func( z, r ):
    """Returns relative density at position z and r"""
    # Allocate relative density
    n = np.ones_like(z)
    # Supress density before the ramp
    n = np.where( z<ramp_start, 0., n )
    # Make linear ramp
    n = np.where( (z>=ramp_start) & (z<=ramp_start+ramp_length), (z-ramp_start)/ramp_length, n )        
    return(n)

Thanks.

**Comment by hightower8083** [comment]
I think this is related to the fact that you are looking at a slice at `r=0` and this particular cylindrical cell is kinda special. If you look at the 2D rho slice you'll see that values exactly on axis are a bit higher, which is due to a particular coefficients during projection (look [here](https://github.com/fbpic/fbpic/blob/1867a4f216baf4269f2314ab4388e92ae9a3b201/fbpic/fields/interpolation_grid.py#L85-L116) for details). If you look at a couple cells off the axis all values should be fine.  It is not supposed to produce any physical artefacts, and if you use cubic shapes it'll get less visible.

**Comment by dmargarone** [comment]
Hi,

If it is about laser pulse, I may accept what you said. For laser pulse it strictly depends on resolution. Moreover, you said that it will not produce any physical artifact ... this is again not true. In normal situations, in LWFA the most important interaction region is close to the axis (r=0, in cylindrical geometry). If we don't get anything correct along the axis it will seriously produce unphysical results. If I set plasma with density 5.e+18 cm^-3 in the input script, I get 8.0e+18 cm^-3 value from the simulations, and for the fixed laser parameters the physical process runs very differently in these two plasma densities. 

Anyways, I also check the density distribution with higher resolution : 
lambda / 24 along the propagation direction and lambda / 8 along the transverse direction and 
p_nz = 4         # Number of particles per cell along z
p_nr = 4         # Number of particles per cell along r
p_nt = 4         # Number of particles per cell along theta

However, there is no improvement in the result. 

Later, I also tried to see how it works with uniform plasma density distribution ... no ramp .... but again the outcome is the same. Higher density then what is given in the input.

**Comment by dmargarone** [comment]
Even for more higher resolution of : 
lambda / 48 along the propagation direction and lambda / 16 along the transverse direction and
p_nz = 4 # Number of particles per cell along z
p_nr = 4 # Number of particles per cell along r
p_nt = 4 # Number of particles per cell along theta

The value is 1.6 times higher than what it should be. Also, unlike to your expectation, it is independent of the "radial coordinate (r)". Please, see the attached figure.

[density_discrepancy.pdf](https://github.com/fbpic/fbpic/files/6943687/density_discrepancy.pdf)

**Comment by RemiLehe** [comment]
@dmargarone Hm, that is indeed unexpected. Could you post the exact input script that you are using, in order to obtain the last figure that you posted? This would allow us to reproduce this issue and investigate it.

**Comment by dmargarone** [comment]
Hi,

Please, see the attached script file and plotting file. 

[lwfa_script.pdf](https://github.com/fbpic/fbpic/files/6944200/lwfa_script.pdf)
[rho_plot.pdf](https://github.com/fbpic/fbpic/files/6944201/rho_plot.pdf)

**Comment by RemiLehe** [comment]
@dmargarone Thanks. I see this line your plotting script:
```
rho_cm3 = ((-rho/1.0e-19)*1.0e-6)
```
It looks like you are trying to divide the density `rho` by the electron charge. But in that case, I think that the value should be around `1.6e-19` (or even better `scipy.constants.e`) rather than `1.0e-19`. Could this explain the discrepancy of `1.6` that you are observing?

**Comment by dmargarone** [comment]
Hi,

Oh my God ... this was the mistake actually. Now, the plasma density looks perfectly fine. Even though I check the script several times, but I never noticed that I made a mistake, which is keeping me puzzling from almost 5 days. 

I apologize for this blunder and very thankful to you for pointing it out. 

Thank you once again for this wonderful project. 

Lots of love and best wishes to all of you.
DM
