### ISSUE TITLE
FBPIC Post Processing

### ISSUE THREAD

**Issue by sadia1997** [fbpic/fbpic#550]
I want to learn the post processing of FBPIC. I have done simulations and want to extract information. I want to create 3D pictures and extract field and density profiles.

**Comment by RemiLehe** [comment]
Hi @sadia1997,

For 3D visualization, you can have a look at [this link](https://fbpic.github.io/advanced/3d_visualization.html).

Regarding the extraction of the fields, I would recommend to have a look at [this tutorial](https://github.com/openPMD/openPMD-viewer/blob/dev/tutorials/1_Introduction-to-the-API.ipynb).

If you have additional, specific questions on how to use `openPMD-viewer`, you can open a corresponding issue on the [openPMD-viewer Github issues](https://github.com/openPMD/openPMD-viewer/issues).
