### ISSUE TITLE
Selecting injected particles 

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#551]
Dear All,

I have a small question about selecting the injected particle positions. I run the simulation in cylindrical geometry by specifying the "z" and "r" extent of the simulation window. 

From simulation result, we get the electron density (from "get_field" option) and particle distribution information (from "get_particle" option).  For " electron density (rho)", we get the distribution in "z-r" coordinates, whereas, for particles we get the distribution in "x-y-z" coordinates. 

Could you please elaborate how the x and y positions are calculated ?

My aim is to understand how by looking at the "rho" I can select the electrons distributed between specific range. For example, in the attached figure between :

1840 μm < z < 1855 μm   and -5 μm < r < 5 μm  ( Please, see the attached figure). 

Thank you.

[fbpic_result.pdf](https://github.com/fbpic/fbpic/files/6997002/fbpic_result.pdf)

**Comment by RemiLehe** [comment]
Thanks for your question.

Yes, in FBPIC (and other quasi-3D PIC codes), the fields are internally computed on a z-r grid, while the motion of the particles is internally still computed in Cartesian coordinates (x, y, z). See for instance [this paper](https://www.sciencedirect.com/science/article/pii/S0021999108005950) for more details.

As a consequence of this internal representation of fields and particles, we also output the data in the same coordinate system (i.e. z-r for fields, x-y-z for particles).

Regarding your question on selection, if you are using `openPMD-viewer`, you could do the following:
```python
x, y, z, ux, uy, uz = ts.get_particle( ['x', 'y', 'z', 'ux', 'uy', 'uz'] )
selection_criterion = (z > 1840e-6) & (z < 1855e-6) & ( np.sqrt( x**2 + y**2 ) < 5e-6 )
x_selected = x[ selection_criterion ]
y_selected = y[ selection_criterion ]
z_selected = z[ selection_criterion ]
ux_selected = ux[ selection_criterion ]
uy_selected = uy[ selection_criterion ]
uz_selected = uz[ selection_criterion ]
```

**Comment by ncpathak** [comment]
Dear Remi,

Thank you for the reference paper, detailed explanation and help. 

Best wishes.
