### ISSUE TITLE
Dual stage LWFA simulation case

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#553]
Dear All,

I would like to perform a two-stage LWFA simulation. The aim is to get the electron beam from the 1st-stage and then injecting it into the 2nd stage. The concept is nearly similar to the one given in the article : https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.123.054801

My case is without quadrupole and chicane, only pure two stage LWFA. 

Let us assume that an electron bunch is obtained from the 1st-stage with bunch parameters are described by its position and / or momentum: (x,y,z,ux,uy,uz) or (ux,uy,uz).

My query is: how to make the simulation set-up for the second stage, where this electron bunch is injected as an external beam ?

Thank you.

**Comment by RemiLehe** [comment]
Thanks for your question and your interest in the code!

If you are able to load the position and momenta (and weights) of the external electron bunch as `numpy` arrays, then you can inject it in a FBPIC simulation with the function [add_particle_bunch_from_arrays](https://fbpic.github.io/api_reference/lpa_utilities/beam.html#fbpic.lpa_utils.bunch.add_particle_bunch_from_arrays).

Alternatively, you could potentially simulation both stages as a single FBPIC simulation...

Does that answer your question?

**Comment by ncpathak** [comment]
Dear Remi,

Thank you for your help.  

Considering the user friendly environment of the code, I would like to extend my understanding to simulate more complex problems with FBPIC in very near future.  Therefore, I think at first I should try to simulate with the "add_particle_bunch_from_arrays" and get some experience with it. I will read about it and I will try to use it for the two-stage LWFA. If there will be any problem, I may need your help again. 

Running dual stage problem in a single simulation is relatively simple solution, but I would prefer to gain more experience with the available functionality of the code. 

For the moment, I will keep this issue open and will close it at the later stage after partially solving my problem.

Thank you once again for your kind help.

**Comment by RemiLehe** [comment]
Sounds good! Thanks again for your interest in the code!

**Comment by ncpathak** [comment]
I forget to make one request in the code. Please, if possible allow to add the externally injected beam as a specie (for example, external beam). So that it can be separated from the plasma electrons. This will be important to study the evolution of the injected beam parameters. 

Thank you.

**Comment by MKirchen** [comment]
Hey,

The function will return a new species that contains only the beam electrons:

`beam_species = add_particle_bunch_from_arrays()`

Hope that helps,
Manuel

**Comment by ncpathak** [comment]
Dear Manuel,

Thank you for your swift help. I did exactly as you suggested:

beam_species = add_particle_bunch_from_arrays(sim, q=e, m=m_e, x=xb, y=yb, z=zb, ux=uxb, uy=uyb, uz=uzb, w=wb, boost=None, direction='forward', z_injection_plane=None, initialize_self_field=True)

but when I used :

ts = OpenPMDTimeSeries(datapath)
print(ts.avail_species) 

it only display electrons.

Please, could you suggest where I am doing wrong ....

Thank you.

**Comment by MKirchen** [comment]
Hey,

Maybe you forgot to add the species to the output diagnostics?

In your input script you can define a ParticleDiagnostic that outputs both species like this:

`ParticleDiagnostic( diag_period, {"electrons" : elec, "beam" : beam_species}, ...)`

**Comment by ncpathak** [comment]
Dear Manuel,

Thank you. Now, I can see both the species.
