### ISSUE TITLE
"diags" and "checkpoints" path

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#555]
Dear All,

I would like to know about how to define "diags" and "checkpoints" directory using a specified path, rather than the default path of 'current working directory'. This is quite useful when running the code in some computing facility, where the home directory is limited in space and data saving is recommended in other dedicated directory. 

Just like the functionality to add an external electron beam from array (from fbpic.lpa_utils.bunch import add_particle_bunch_from_arrays), I can see that there also exist a functionality to add specific output diags and checkpoints path: https://fbpic.github.io/api_reference/checkpoint_restart.html

However, I am bit confused how to use it for both "diags" and "checkpoints". Please, could you suggest me the correct way of setting the desired path.

Thank you.

**Comment by RemiLehe** [comment]
Hi @ncpathak 

Sorry for the late reply!

Regarding checkpoints: you can pass the argument `checkpoint_dir` to the [function `set_periodic_checkpoint`](https://fbpic.github.io/api_reference/checkpoint_restart.html#setting-checkpoints).

Regarding the diagnostics: you can pass the argument `write_dir` to [the `FieldDiagnostics` or `ParticleDiagnostics` object](https://fbpic.github.io/api_reference/diagnostics.html#field-diagnostic).

Note that it the path for the checkpoint and the regular diagnostics should be different (they can both be within the same high-capacity folder on your cluster, e.g. `$SCRATCH`). (On the other hand, you can pass the exact same path for both `FieldDiagnostics` or `ParticleDiagnostics`.)

Does that answer your question?

**Comment by ncpathak** [comment]
Dear Remi,

Thank you for suggesting the way. I will follow your suggestion, and if there is any problem I may get back to you.

Thank you.
