### ISSUE TITLE
using GPU

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#556]
Dear All,

I am trying to run the code on GPU. I have no previous experience of using GPU. 

The cluster has GPU：NVIDIA A100 8 units

Whenever I am trying to run the code using GPU, it's always end up running with CPU's only. May be I am missing something.

Please, find attached the output of "conda list". 

I need some help / suggestions to be able to run the code with GPU. 

Thank you.

[conda_list.pdf](https://github.com/fbpic/fbpic/files/7140618/conda_list.pdf)

**Comment by ncpathak** [comment]
Soory, in my first message I forget to attached the "job script file "and the "output message" after submitting the job. 

Please, find attached herewith.

[jobscript.pdf](https://github.com/fbpic/fbpic/files/7141338/jobscript.pdf)
[stdout.pdf](https://github.com/fbpic/fbpic/files/7141339/stdout.pdf)

**Comment by RemiLehe** [comment]
Hi @ncpathak 

Thanks a lot for raising this question, and sorry for the very late reply!

I am not sure what exactly is causing this issue, but here are a few elements that you could check:

- In order to run on GPU, FBPIC requires 2 additional packages: `cudatoolkit` and `cupy` (see [this page](https://fbpic.github.io/install/install_local.html) for more info). Looking at your file `conda_list.pdf`, it seems that neither of these packages are in your environment. Could you try installing them in your conda environment, using e.g. the above-mentioned page?

- Are you getting a warning message of the form 
```
UserWarning: /home/rlehe/Documents/codes/fbpic/fbpic/main.py:240:
GPU not available for the simulation.
```
This should appear in `stderr` or `stdout` and it should tell you more about the reasons why FBPIC was unable to run on GPU. If you are not getting this message, please check that you are passing `use_cuda=True` to the `Simulation` object, in your input script.

**Comment by ncpathak** [comment]
Dear Remi, 

Thank you for pointing out the problem. Following your suggestions, I installed the required packages. The conda list now shows the cudatookit and cupy. (Please, see the attached "conda_list.pdf" file.)

However, the problem is not fixed yet. There is an error message, but I am not sure if this is related to raising it further here or I should consult to our system administrator.  Please, could you give a look on the "errout.pdf" file, and suggest what I should do. 

Thank you. 

[conda_list.pdf](https://github.com/fbpic/fbpic/files/7182786/conda_list.pdf)
[errout.pdf](https://github.com/fbpic/fbpic/files/7182789/errout.pdf)

**Comment by ncpathak** [comment]
Dear Remi,

I consult the system administrator of the supercomputer team. They said :  "probably because scheduler has any limit, the MPI you prepared yourself (conda install or pip install , etc.) will not be able to perform calculations using multiple nodes. If it is only within 1 node, it should work fine".

Following there suggestion, I tried to run the simulation on single node. However, still I am getting an error, and this time it seems to be pointing towards the "h5py" problem. (Please, see the attached error file)

The openPMD-viewer was installed successfully in the environment. 

Do you think you could suggest something to fix this error ?

Thank you.

[errout.pdf](https://github.com/fbpic/fbpic/files/7185435/errout.pdf)

**Comment by ncpathak** [comment]
Dear Remi, 

I consulted the system administrator of the supercomputer team. They said : "Probably because scheduler has any limit, the MPI you prepared yourself(conda install or pip install , etc.) will not be able to perform calculations using multiple nodes. If it is only within 1 node, it should work fine."

Therefore, following their suggestion, now I am trying to run the simulation on single node. There are some error appearing but I am trying to fix them (by hit and trial method). Let me try ... if I will get stuck completely, I may need your help again. 

I will let you know if I succeeded or not.

**Comment by ncpathak** [comment]
Finally working.

**Comment by ncpathak** [comment]
Hi Remi,

On GPU when I run a test simulation with very coarse resolution the simulation start up normally and even the restart was fine. However, when I tried to run with finer resolution (which on CPU occupy only ~ 15 GB memory) there is always an error. The memory associated with the GPU node I am working is 256 GB. 

Please, find attached the error file. Please, could you help me to understand why it is so, and how to fix it.  

Thank you.

[GPU_error_msg.pdf](https://github.com/fbpic/fbpic/files/7192187/GPU_error_msg.pdf)

**Comment by MKirchen** [comment]
Hey, 

when running on GPU, the entire simulation data needs to fit into the GPU device memory, which is usually much smaller than the standard host (CPU) memory. Could it be that in your case, the GPU has 16 GB of memory? 

This would explain that you get an error when trying to run a simulation that has a similar or exceeds this size (~15GB as you mentioned). 

It is unfortunate, however, that the specific error message that you see does not say anything about exceeding the memory.

If you want to run larger simulations, you would need to use a different GPU model with more memory or use more than one GPU with MPI.

Hope that helps solving your issue,
Manuel

**Comment by ncpathak** [comment]
Hi Manuel,

Thank you so much for very swift reply even on Sunday. Thank you for the explanation. Based, on my desktop computer configuration, I was expecting something similar on the cluster also (exactly as you mentioned). However, I have no clear idea how much memory is associated with each GPU in the cluster. I will ask the system administrator. 

Just for a reference, I have attached the information about the GPU nodes I can access. Do you think I can solve my problem with such configuration ? 

Thank you. 

[GPU_information.pdf](https://github.com/fbpic/fbpic/files/7192230/GPU_information.pdf)

**Comment by MKirchen** [comment]
Hey,

okay yes that should be enough GPU memory - maybe your issue is not related to a memory limitation. Each Nvidia A100 GPU has at least 40 GB of memory and if you scale to all 8 GPUs on a single node, you can run very large simulations.

Could you run the simulation again while passing the parameter `verbose_level=2` to the `Simulation()` object and post the output here? 
Moreover, you can try to double-check the GPU configuration by running the command `nvidia-smi` in the terminal on the GPU node. It would also be useful if you post the output here.

Manuel

**Comment by ncpathak** [comment]
Hi Manuel,

Thank you so much for the feedback. Please, find attached the output of the commands you suggested. 

[GPU_debug.pdf](https://github.com/fbpic/fbpic/files/7192270/GPU_debug.pdf)

**Comment by MKirchen** [comment]
Hey, could you please also post the entire standard output (`stdout`) and not only the error message?

**Comment by ncpathak** [comment]
Please, find attached the stdout message. 

[stdout.pdf](https://github.com/fbpic/fbpic/files/7192318/stdout.pdf)

**Comment by MKirchen** [comment]
Hey,

so it seems that FBPIC correctly chooses a single A100 GPU for the simulation. (The output of `nvidia-smi` suggests that there is another GPU installed, did you maybe run the command on a different node/computer by mistake?)

Would you mind sharing an input script that reproduces the issue? Then we could test if the issue also appears on our side when using the same GPU model.

Also, you could maybe contact your system administrator and ask if they recommend to load specific pre-installed modules/settings before installing FBPIC. You could then try to do a fresh reinstall of all packages (including the most recent versions cudatoolkit and cupy) - maybe this solves the issue.

**Comment by ncpathak** [comment]
Hi Manuel,

Please, find attached the input script file. Sorry, it is in PDF because uploading accept only pdf or images. 

Thank you so much for your help. I will also contact the system administrator. 

[lwfa_script.pdf](https://github.com/fbpic/fbpic/files/7193079/lwfa_script.pdf)

**Comment by ncpathak** [comment]
Hi Manuel, 

Finally, the problem fixed following your "second suggestion". 

After sending my input script to you, I also tried to reinstall the cuda-toolkit to the latest version. Now, what I did is instead of  

conda install cudatoolkit=10.0
pip install cupy-cuda100

I used "conda install -c conda-forge cupy cudatoolkit=11.0".  

This fixed the problem, and now I can run the simulation even with quite high resolution. The cluster have CUDA 11.2 and that may be the reason (just a guess) why it was not working previously (but with poor resolution it did !! ).

I am now closing this issue. If there will be any problem I may consult you again. 

Thank you once again to both of you.

**Comment by MKirchen** [comment]
Perfect, glad that you could solve it!

Please also consider asking future questions in the #support channel of our Slack chat [(join here)](https://slack-fbpic.herokuapp.com/), where other users of FBPIC might be able to help you as well.

**Comment by ncpathak** [comment]
Hi Manuel,

Sure, next time I will post question(s) on slack chat. I will join it today.

Thank you.
