### ISSUE TITLE
FBPIC-trajectory of electron 

### ISSUE THREAD

**Issue by mehdiabedi1234** [fbpic/fbpic#563]
Dear all,
I used FBPIC for LWFA, I wanna plot trajectory of electron for 2D or 3D (vertical (z)- horizontal (x)). How can do it? I have so many thanks for your response in advance.

**Comment by RemiLehe** [comment]
Sorry for the very late reply!
This can be done by dumping the particle IDs in the output in FBPIC. (This is done by using the `track` method ; see [this example](https://fbpic.github.io/example_input/lwfa_script.html).) and then post-processing it to reconstruct the trajectories: see [this tutorial](https://github.com/openPMD/openPMD-viewer/blob/dev/tutorials/4_Particle_selection.ipynb) to see how to do this.

**Comment by HaoPengYY** [comment]
Dear all,
Hi. Thanks for your wonderful code!

Is it possible to track the electron trajectories with a smaller time resolution, even close to `sim.dt`? Sometimes the electron may interact with the  driving laser, or other user-defined laser.  I notice that one can define the iteration span to do particle diagnostic in `ParticleDiagnostic` by specifying `iteration_min` and `iteration_max`. Maybe we can just set two particle diagnostics, one with large iteration interval and going through all the simulation, the other one in narrow iteration span(we are interested in the electron trajectories in this iteration span) and with small time resolution?

But I don't find the counterpart of `iteration_min` and `iteration_max` in the `BackTransformedParticleDiagnostic` class, so maybe it is not possible to define the diagnostic iteration span in the boosted-frame simulation?

**Comment by RemiLehe** [comment]
@HaoPengYY These are good points.
You can indeed define two different diagnostics (with different output frequency) and use `iteration_min` and `iteration_max` to do this.
In the case of back-transformed diagnostics, this is not currently possible, but we are thinking of implementing a similar option in the near future.

**Comment by HaoPengYY** [comment]
@RemiLehe Thanks a lot for your reply. I got it. Please close the issue.

**Comment by MKirchen** [comment]
Hey @HaoPengYY,

you could also create many diagnostic snapshots and remove the ones you don't need during initialization of the simulation.

You can find some details in the description of PR#592.

Manuel
