### ISSUE TITLE
LWDA

### ISSUE THREAD

**Issue by mehdiabedi1234** [fbpic/fbpic#564]
Dear all,
IS it possible simulation of LWDA (Synergistic Laser Wakefield and Direct Laser Acceleration) in bubble regime by using FBPIC?
Thank you for your response in advance,
Cheers,
Mehdi

**Comment by RemiLehe** [comment]
Sorry about the very late reply! 
Yes, FBPIC does automatically capture the direct interaction between the laser and the accelerated beam. Therefore, it should be possible to simulate LWDA.

**Comment by mehdiabedi1234** [comment]
> 

Thank you dear Dr. Remilehe for your response.
