### ISSUE TITLE
BG laser beam

### ISSUE THREAD

**Issue by mehdiabedi1234** [fbpic/fbpic#568]
Dear all,
I want to work about Bessel-Gaussian laser beam in FBPIC. Is there this profile in FBPIC?I search in library of FBPIC but I could not find this class. Anyone can help me. Thanks so much for your help in advance.
Cheers,

**Comment by RemiLehe** [comment]
Thanks for the question.
Bessel-Gaussian laser beams are not currently implemented in FBPIC. However, you could potentially implement it yourself (e.g. in your input script directly) following the instructions here: https://fbpic.github.io/api_reference/lpa_utilities/laser.html#creating-your-own-custom-laser-profile
Does that answer your question?

**Comment by mehdiabedi1234** [comment]
Thank So much for your response Dear Dr. Remi. 
All the best,
Mehdi
