### ISSUE TITLE
Move grids by shifting fields in spectral space

### ISSUE THREAD

**Issue by MKirchen** [fbpic/fbpic#57]
We recently changed the code, such that the moving window updates and shifts the fields each timestep. However, this is currently done in spatial space and involves several extra kernels and also expensive allocation and deallocation of CUDA device memory. To get a better performance for the shifting of the fields, we should implement the shifting in spectral space. Furthermore, we then would want to also shift the "previous" charge density rho in spectral space, which we currently redeposit every time step.

**Comment by RemiLehe** [comment]
Closed by PR #65
