### ISSUE TITLE
Externally injected beam

### ISSUE THREAD

**Issue by ncpathak** [fbpic/fbpic#572]
Dear All, 

I am running a test simulation of PWFA. 

In the code the external electron beam is read by file and is included in the diagnostic as follows:

sim.diags = [ FieldDiagnostic( diag_period, sim.fld, comm=sim.comm, write_dir=datapath ),ParticleDiagnostic( diag_period, {“electrons” : elec, **“beam” : beam_species**}, write_dir=datapath, select={“uz” : [1., None ]}, comm=sim.comm ) ]

where beam is the “beam_species” user defined electron beam in the main python script.

Now, using:   

ts = OpenPMDTimeSeries(datapath),  and

rho = ts.get_field(iteration=it_no,  field=‘rho’, plot=True, vmax=0.0, vmin=-6.e6, cmap=‘Grey’) 

I can make a plot of number density of all the species in the simulation (both external electron beam and plasma together). 

However, I would like to plot the external beam alone. For this I tried like:  

rho = ts.get_field(iteration=fno,  field=‘rho’, species=‘beam’, plot=True, vmax=0.0, vmin=-6.e6, cmap=‘Grey’), but it didn’t work.

Please, could someone let me know how I can see only the externally injected electron beam and also how to get its parameters like position, momentum and charge. 

Thank you.

**Comment by RemiLehe** [comment]
Hi,
Thanks for the question.
As mentioned by @soerenjalas on our Slack channel, you can specifically output the density of a single species with this function: https://fbpic.github.io/api_reference/diagnostics.html#fbpic.openpmd_diag.ParticleChargeDensityDiagnostic
Let us know if you have any question on the above.
