### ISSUE TITLE
PICMI in FBPIC : need to mention periodictable and numexpr

### ISSUE THREAD

**Issue by RTSandberg** [fbpic/fbpic#574]
I had to install periodictable and numexpr to run FBPIC using PICMI; maybe these should be listed in the dependencies

**Comment by RemiLehe** [comment]
Thanks for reporting this!
I think that those dependencies will be automatically installed when doing:
```
pip install fbpic[picmi]
```
However, this is indeed not documented currently. I will add this to the documentation.

**Comment by RTSandberg** [comment]
Ok, useful to know.  Thanks!
