### ISSUE TITLE
Question on HDF5 structure

### ISSUE THREAD

**Issue by Andrewlongman** [fbpic/fbpic#576]
Hi, I am trying to write my own implementation of a hdf5 reader/plotter in matlab for fbpic. I am able to load the files into matlab and can read E,B,J,rho etc. However I am confused on the structure. 

Running a simulation with m=4, I get a 7 element matrix in the output? (See attached image) I know that I have to rebuild the total field profile using the function: 
![image](https://user-images.githubusercontent.com/25441489/158905854-051068b1-9f02-4428-8e7a-166f1295144c.png)
so are these additional elements the complex parts? If so, how do I know which is which? 

I am also wondering what the unit dimensions represent? 

Thanks, Andrew

![image](https://user-images.githubusercontent.com/25441489/158905991-475ee227-cff5-4f42-9889-d7dc8a4ef2b5.png)

**Comment by RemiLehe** [comment]
Yes, you are correct, the 7 elements are the real and imaginary components of the 4 modes. (For the first mode, i.e. m=0, we only store the real part, hence 7 and and not 8.)

The ordering of the data is specified in the [openPMD standard](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md):
![Screen Shot 2022-03-17 at 3 52 20 PM](https://user-images.githubusercontent.com/6685781/158907268-faa50e49-9f53-44c7-9848-a6aa7367a904.png)

For instance, here is a Python code snippet that reads the data accordingly (using the formula that you pasted above):
https://github.com/openPMD/openPMD-viewer/blob/dev/openpmd_viewer/openpmd_timeseries/data_reader/h5py_reader/field_reader.py#L259

Does that answer your question?

**Comment by Andrewlongman** [comment]
Hi Remi, 

Yes this is exactly what I was after!

Thanks, Andrew
