### ISSUE TITLE
Error in using boosted frame example script

### ISSUE THREAD

**Issue by zhangli28** [fbpic/fbpic#578]
Hi, I am trying to run boosted frame example given in documentation. But when I was trying to use the script, there was a error message 

Traceback (most recent call last):
  File "boosted_frame_script.py", line 173, in <module>
    plasma_elec = sim.add_new_species( q=-e, m=m_e, n=n_e,
TypeError: add_new_species() got an unexpected keyword argument 'boost_positions_in_dens_func'

I am using Fbpic version (0.20.4) but the same error also come in version (0.20.3)

Can you tell me what is wrong or why I am geting this error message ?

Thanks in advance.

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!
It seems that I failed to release the latest changes in FBPIC, which are needed in order to take into account the new argument `boost_positions_in_dens_func`. I now just released these changes, in FBPIC 0.21.0.

Could you do:
```
pip install --upgrade fbpic
```
in order to get that latest release, and then try to run this script again?

**Comment by zhangli28** [comment]
Thanks for quick answer. After upgrade to version 0.21.0, the code is running.

**Comment by zhangli28** [comment]
Hi, I am progressing in using boosted frame script (with my changes), but I want to ask some question on output in boosted frame. Like, as shown below

(1) In lab. frame script:  diag_period = 50  # period of diagnostics in number of timesteps, this is very clear, but definition of N_boosted_diag and N_lab_diag in boosted frame script is not clear. 
For example, why N_boosted_diag = 15+1 ( what is 15 and why +1), similarly, why N_lab_diag = 20+1 ( what is 20 and why  +1). 

What is the criteria to set their values  ? 

(2) What is "write_period" and how to set its value.

Thank you very much in advance.

**Comment by zhangli28** [comment]
Hi @RemiLehe, I am progressing in using boosted frame script (with my changes), but I want to ask some question on output in boosted frame. Like, as shown below

(1) In lab. frame script: diag_period = 50 # period of diagnostics in number of timesteps, this is very clear, but definition of N_boosted_diag and N_lab_diag in boosted frame script is not clear.
For example: why N_boosted_diag = 15+1 ( what is 15 and why +1), same way, why N_lab_diag = 20+1 ( what is 20 and why +1).

What is the criteria of setting their values ?

(2) What is "write_period" and how to choose its value.

Thank you very much in advance.

**Comment by MKirchen** [comment]
Dear @zhangli28, sorry for the late reply. The information can be found in the documentation of the `BackTransformedFieldDiagnostic` [class](https://fbpic.github.io/_modules/fbpic/openpmd_diag/boosted_field_diag.html#BackTransformedFieldDiagnostic).
