### ISSUE TITLE
Some error problem

### ISSUE THREAD

**Issue by zhangli28** [fbpic/fbpic#580]
Hi, I got a error mesage. Please, see below:

#######
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 1,344,278,528 bytes (allocated so far: 40,073,334,272 bytes).
#######

Total memory use by the simulation was between 6.5 GB to ~27 GB. The memory was low (6.5 GB) when simulation was doing calculations and high (27 GB) when output data was dumped or saved in hdf5 files.

In simulation diag_period = 1000. But if I reduced the diag_period to 100 or less, no such error appear. 

Is this normal behavior.

Thanks in advance.

**Comment by RemiLehe** [comment]
Thanks for reporting this issue.

Could you post the input script (or a modified version thereof) that reproduces the error?
Also, do you have Python Traceback that shows exactly in which function this error occurs (within the FBPIC source code)? If yes, could you post it here?

Thanks again.

**Comment by zhangli28** [comment]
Hi, thanks for answering this issue. I am attaching the input script and error file.

[errout_msg.pdf](https://github.com/fbpic/fbpic/files/8494423/errout_msg.pdf)
[lwfa_script_RA.pdf](https://github.com/fbpic/fbpic/files/8494424/lwfa_script_RA.pdf)

**Comment by zhangli28** [comment]
Thanks, this perhaps help. we have 2 gpu system and we want to run on it.
