### ISSUE TITLE
Possible Bug w/ Diagnostics on many MPI processes (vs. one MPI process)

### ISSUE THREAD

**Issue by EZoni** [fbpic/fbpic#587]
While doing some benchmark comparisons between WarpX and FBPIC, we encountered the following issue.

It seems like there might be a problem with diagnostics when running on many MPI processes as opposed to one single MPI process. I attach a PICMI input script for a laser-driven plasma wakefield test and a plotting script to plot the Ex field in the RZ plane as well as a lineout of Ex at a given radius.

Not 100% sure at this point whether it is an issue on the FBPIC side or on the post-processing side.

Here's the PICMI script (cannot attach `.py` files): [PICMI_inputs_issue.txt](https://github.com/fbpic/fbpic/files/8632799/PICMI_inputs_issue.txt)
(run with `mpirun -np  1 python PICMI_inputs_issue.py` or `mpirun -np  8 python PICMI_inputs_issue.py`).

Here's the plotting script (cannot attach `.py` files): [plot.txt](https://github.com/fbpic/fbpic/files/8632801/plot.txt)
(run from within IPython terminal with `run plot.py 1000` to plot data after 1000 time steps).

Here's the results on 1 MPI process:
![figure_Ex_time=1000_ranks=1](https://user-images.githubusercontent.com/59625522/166964935-3b50e32b-36d7-4a36-9026-d607c029c0ed.png)

Here's the results on 8 MPI processes (looks like there is a sharp cutoff in the data, the sign is different too):
![figure_Ex_time=1000_ranks=8](https://user-images.githubusercontent.com/59625522/166965025-63485f7f-a72f-4e50-a023-d454d598337b.png)

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this.
I should have some time to investigate this tomorrow.

**Comment by RemiLehe** [comment]
Thanks again for reporting this issue.
Could you let me know which version or branch of FBPIC you are using? 
It seems that the latest version of FBPIC (0.21.0) raises errors when run with the above script...

**Comment by EZoni** [comment]
I installed FBPIC from source from the `dev` branch, latest commit `b50bfcdfba37a90af174d9febbe14f92338b0315`.

**Comment by RemiLehe** [comment]
OK, thanks a lot for reporting this.
It seems that this was an issue specific to the implementation of the PICMI interface in FBPIC. (i.e. it does not happen when using the native interface). It should be fixed by  #588
