### ISSUE TITLE
Plasma density diagnostic in boosted frame

### ISSUE THREAD

**Issue by HaoPengYY** [fbpic/fbpic#590]
Dear all,

Hi. I noticed that there is a particle density diagnostic in the regular diagnostic in which one can use `get_field(field='rho_electrons')` to get the electron density, but there is no such a Back-transformed particle density diagnostics for boosted-frame simulations.  The field `rho` seems like a net charge density for both electrons and ions, because it is usual 0 in neutral plasma and it is positive in the cavity, which gives not enough information for the wakefield. Do you have any suggestions for getting the electron densities in a boosted-fram simulation?

**Comment by HaoPengYY** [comment]
OK, I realized I can get `rho_electrons` from `rho` by assuming the ions are immoblie and they just form a static background positive charge density, it is not precise but close.

**Comment by RemiLehe** [comment]
@HaoPengYY Thanks for raising this issue.
You are correct that there is currently no way to get the per-particle density (e.g. `rho_electrons`) in the back-transformed diagnostics. I think that the methods you used (i.e. assuming that the ions are immobile) is the best that you can do for now.

I will close this issue, but feel free to re-open it if needed.
