### ISSUE TITLE
Weird results when running on several GPUs

### ISSUE THREAD

**Issue by HaoPengYY** [fbpic/fbpic#594]
Dear Developers,
Hi. I enjoyed a lot using FBPIC. But when I tried to run my simulation across several GPUs, I got weird, unphysical results. I have performed the same simulation with one, two and four GPUs. Enclosed please find the input script: [input.txt](https://github.com/fbpic/fbpic/files/8784659/input.txt), which are completely same for the single GPU case and multiple GPU cases, and submission file for the simulation with 4 GPUs: [submission.txt](https://github.com/fbpic/fbpic/files/8784664/submission.txt). On a single GPU, the electron charge density and drive laser after the window moves 50 um are like:
![image](https://user-images.githubusercontent.com/81665726/170645391-ef80b2a0-23f5-42ec-8b76-7a8538deb5fc.png)
![image](https://user-images.githubusercontent.com/81665726/170647465-703c9208-1675-4e85-9d0c-d0de70034956.png)
which seems quite reasonable. While in the two GPUs and four GPUs cases, they are like:
![image](https://user-images.githubusercontent.com/81665726/170646926-0bc48c48-7b96-4536-a4eb-8b6751c64be4.png)
![image](https://user-images.githubusercontent.com/81665726/170647509-2b4c13e3-53cf-4e46-87ef-649c68439b23.png)
and 
![image](https://user-images.githubusercontent.com/81665726/170646971-ffa7ed83-cfe7-4321-b377-b9729f230c92.png),
![image](https://user-images.githubusercontent.com/81665726/170647698-ace87944-eb74-45c7-a4f4-400402ee9771.png)
, respectively. 

Other informations:
Basic informations of the HPC I run my simulations on:
CPU： AMD EPYC 7402 48@2.8GHz
RAM：512GB
GPU：8 * NVIDIAGeForceRTX 3090
Video Memory：8 * 24GB(936.2 GB/s)
Nodes Interconnection：RoCE 2 * 25Gbps(RDMA protocol)
System：CentOS7.9
For every GPU, we have 6CPUs: 6CPU/60GB/1 * RTX3090-24GB.

**Comment by RemiLehe** [comment]
Thanks for reporting this issue. This is quite strange indeed.
For more information, would be okay to do
``` 
module load anaconda/2020.11
module load cuda/11.1

source activate fbpic_bk
conda list
```
and paste the content of `conda list` into a file that you upload. This would help identify whether any of the dependencies of fbpic might cause a problem here.

**Comment by RemiLehe** [comment]
I just ran the above input script on 4 GPUs (Nvidia A100 GPUs, connected to AMD EPYC Milan CPUs), and got the correct result:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/6685781/170763059-0665f37c-c23b-4f62-a909-234d7c3ceb9f.png">

This suggests that the issue observed by @HaoPengYY  is either due to the hardware or to the exact version the dependencies. (In particular, the exact version of MPI and `mpi4py` might matter here.)

@HaoPengYY Again if you are able to share the content of `conda list`, I think that this could help debug the above issue.

**Comment by HaoPengYY** [comment]
@RemiLehe Hi. Thanks for your quick reply. 

I found that the engineers actually  build two different environments for me to run fbpic. For the simulation on just one GPU, I used an environment called `fbpic`, here is the `conda list`:
[conda_list_oneGPU_fbpic.txt](https://github.com/fbpic/fbpic/files/8792841/conda_list_oneGPU_fbpic.txt)

For the simulations(two and four GPUs), I used the environment called `fbpic_bk`， here is the `conda list`: 
[conda_list_multple_GPUs_fbpic_bk.txt](https://github.com/fbpic/fbpic/files/8792842/conda_list_multple_GPUs_fbpic_bk.txt)
