### ISSUE TITLE
Laser absorption

### ISSUE THREAD

**Issue by Andrewlongman** [fbpic/fbpic#596]
Hi, 

I am trying to calculate the energy absorbed by the plasma from a laser. So far I am just integrating over the modes of the laser and can get the total field energy in the simulation as a function of time. My question is if whether it i possible for fbpic to record the field/particle energy passing through the boundary conditions for each mode? I am using open boundaries in all directions. 

Thanks, Andrew

**Comment by RemiLehe** [comment]
Thanks for the question.
Unfortunately, we currently do not have the option to record the field/particle energy passing through the boundary condition. In principle, you could do this by hand, approximately, by computing the Poynting vector at the boundary (from the regular output of the fields in the full space), and by assuming that this is roughly constant in-between the different output times.
This is of course not ideal, but would that work for you?

**Comment by Andrewlongman** [comment]
Thanks Remi, 

I think I can work around this, I have written a Poynting vector diagnostic so calculating the average energy flow radially outwards should be possible. 

Thanks, Andrew
