### ISSUE TITLE
Issue with guard region larger than physical domain size

### ISSUE THREAD

**Issue by Andrewlongman** [fbpic/fbpic#597]
Hi, 

I ran into an error when increasing the number of mpi processes above 16 nodes - 40c/80t per node and get the following error: 

ValueError: The boundary guard region is larger than the physical domain size. Use fewer MPI processes 

Any ideas on how to work around this? 

Thanks, Andrew

**Comment by kookjine** [comment]
I guess you need to increase the simulation box length or the longitudinal resolution.

**Comment by RemiLehe** [comment]
Sorry for the late reply.
I think that @kookjine's answer is indeed an option.
Another option would be to reduce the parameter `n_order` which is passed to the `Simulation` object.
