### ISSUE TITLE
Non-uniform resolution and particles

### ISSUE THREAD

**Issue by alexanatoly** [fbpic/fbpic#600]
Dear Developers,

I am doing some simulation with plasma density structures. To do so, I need high resolution to ensure that everything is resolve properly and with necessary number of particles. The problem doesn't allow me to fit the required memory with the system access I have. 

Fortunately, few days ago I saw a paper about using FBPIC with different resolution / particle along the simulation box. It fits exactly with my requirement. But I don't know how to use this in FBPIC.

You may see the attached article and reference to section III, sub-section C, figure S8.

If you let me know how to use this in FBPIC, it will solve my problem amazingly !

Thanks in advance,
Alex

[Supplemental.pdf](https://github.com/fbpic/fbpic/files/9146231/Supplemental.pdf)

**Comment by alexanatoly** [comment]
Dear @hightower8083 

Thanks for answering my query. The code WarpX is a good choice. However, I could not access to the other link. It require an account. 

By the way, the density function should remain same for both r > r0 and r <=0, and only p_nz, p_nr, and p_nt will differ.

Making two density function (even though they are same) makes no sense. p_nz, p_nr, and p_nt change as a function of radial coordinate is understood. 

For my simulation, I will prefer to check with WrapX. 

Thanks,
Alex.

**Comment by hightower8083** [comment]
Glad it helped @alexanatoly 

The second link leads to the [fbpic slack channel](https://slack-fbpic.herokuapp.com/) which you may also join any time for quick questions.

Note that in above example the functions `dens_func_hi_res` and `dens_func_low_res` are not actually same as they contain logical operators  that get translated to numerical (`(r<=r0)` is `1` below `r0` and `0` above ) and are needed to separate the numerical species spatially. Depending on your needs you may localise a more resolved specie anywhere in `z, r` or `x, y, z` space, considering proper density functions. But make sure that that numerical species corresponding to the same physical one do not overlap (or you'll have twice higher density there).
