### ISSUE TITLE
ptx module error with cupy

### ISSUE THREAD

**Issue by kli-jfp** [fbpic/fbpic#602]
I tried installing other programs earlier and managed to break something. Perhaps someone here has run into a similar issue.In fbpic/utils/cuda.py...

    module = cupy.cuda.function.Module()
    if numba_version[1] >= 53:
      ptx = next(iter(numba_kernel.overloads.values())).ptx
      module.load(bytes(ptx, 'UTF-8'))
    else:
      module.load(bytes(numba_kernel.ptx, 'UTF-8'))

When I run my python input script I get this error

    AttributeError: '_Kernel' object has no attribute 'ptx'

I tried reinstalling fbpic, cupy, numba, scipy, numba-scipy... to no use. (edited) 

cupy.show_config()
OS                           : Linux-5.15.0-41-generic-x86_64-with-glibc2.35
Python Version               : 3.10.4
CuPy Version                 : 11.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.4
SciPy Version                : 1.7.3
Cython Build Version         : 0.29.28
Cython Runtime Version       : 0.29.28
CUDA Root                    : /usr/local/cuda-11.7
nvcc PATH                    : /usr/local/cuda-11.7/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 3, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101500
CUB Build Version            : 101500
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3050 Ti Laptop GPU
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0

I installed these earlier

    sudo apt install build-essential ccache cmake g++ git libfftw3-mpi-dev libfftw3-dev libhdf5-openmpi-dev libopenmpi-dev pkg-    config python3 python3-matplotlib python3-numpy python3-pandas python3-pip python3-scipy python3-venv

Can this be creating some conflicts maybe?

**Comment by kli-jfp** [comment]
I have reinstalled everything I can think of and I have also reinstalled everything in a conda environment. I'm still getting the ptx issue.

**Comment by kli-jfp** [comment]
I think the new version of numba has removed ptx as an attribute of _Kernel.

**Comment by MKirchen** [comment]
Thanks for reporting and investigating this issue! We will try to find and implement a permanent fix.

Manuel
