### ISSUE TITLE
(add_particle_bunch_gaussian) question about emittance equation 

### ISSUE THREAD

**Issue by zhangli28** [fbpic/fbpic#610]
Dear developers
I am doing plasma wakefield simulation. Can you tell which equation is considered for emittance when preparing the electron beam  with 

**add_particle_bunch_gaussian** 

Can you tell if the equation of emittance is the same as given in equation. 11 of the attached paper. In this equation, normalization is done with "m0c". But some people say the normalization is by "pz".

Can you explain how it is done in FBPIC.

Thank you very much.

[PhysRevSTAB_emittance_definition.pdf](https://github.com/fbpic/fbpic/files/9368294/PhysRevSTAB_emittance_definition.pdf)

**Comment by RemiLehe** [comment]
Thanks for your interest in the code.
Yes, in FBPIC we use the same convention as equation 11 of the above paper.

**Comment by zhangli28** [comment]
Dear Remi Lehe thanks for the explanation.
