### ISSUE TITLE
CALDER-CIRC and FBPIC results mis-match

### ISSUE THREAD

**Issue by koesterf** [fbpic/fbpic#611]
Hi,

Great work !!  

I am wondering if there is some bench marking available with already published results or not. Recently, I found that some results strongly mis-match with published one using CALDER-CIRC code. 

I guess, FBPIC is somewhat similar to CALDER-CIRC. I also think that the results from both code should not differ very much. But seems that this is not the case and there is quite big difference sometime. 

Could you please see the attached pdf file where I tried to reproduce one particular results with FBPIC code. This is not the only case, but would like to know what do you think about such differences. How to check which is more correct. 

Best,
F. Koester

[Bench_mark_calderCirc.pdf](https://github.com/fbpic/fbpic/files/9400464/Bench_mark_calderCirc.pdf)

**Comment by koesterf** [comment]
Thanks.
BTW, the critical thing here is particle shape. A correct particle shape gives same result.
Cheers

**Comment by koesterf** [comment]
Hi Remi,
Thanks for your explanation on basic differences between Calder and FBPIC. But may be just Nm will not fix the problem. I would also like to point-out the effect of particle shape on electron injection process. Could you check the attached file.
Do you have any suggestion what care one should take when using a default particle shape and higher order particle shape. 

Thanks a lot.

[Bench_mark_calderCirc_cubic.pdf](https://github.com/fbpic/fbpic/files/9544393/Bench_mark_calderCirc_cubic.pdf)

**Comment by RemiLehe** [comment]
Hi,
Thanks a lot for sharing these additional details. 
The fact that the injection varies so much with the particle shape is indeed quite intriguing. Would you be willing to share your full input script so that I could have a more detailed look at this issue? Thanks.

**Comment by koesterf** [comment]
Thanks for quick response. But, the python file cannot be uploaded on github (no option to upload such files).

I will send you by email (I don't understand why I cannot upload the file when trying to upload). 

Sorry for the inconvenience.

**Comment by koesterf** [comment]
Hi Remi,

Did you get some time to check the script ?
Is it OK or I did something wrong ?

Thanks.

**Comment by RemiLehe** [comment]
Hi,

The script looks valid. 
The fact that the distribution of the beam is different with linear and cubic is indeed strange. I guess I have a few more questions:
- From the simulations that you ran: are you able to tell whether the charge and emittance of the beam is also significantly different between the linear and cubic shape case.
- Do the results with linear and cubic shape look more similar if you increase the resolution in `z`? (The observed difference with linear and cubic shape could be an indication that the simulation is not yet converged at the current resolution.)

**Comment by koesterf** [comment]
Hi,

Thanks for the suggestion. You are right, when I increased the axial resolution from λ/32 to λ/64 the injection process starts converging to cubic one. 

Before I close the issue, could you suggest, like n_pt = 4*Nm, what is the good value of Nm, n_pr, and n_pz one should consider in the simulation to be sure that the results are physical and less prone to numerical heating / error.

Thanks.

**Comment by RemiLehe** [comment]
Hm, I not sure that there are any good rule of thumb, but I usually use `n_pr = 2`, `n_pz = 2`. 
Regarding `Nm`: it really depends on the physics being simulated. For instance, PWFA with an axisymmetric driver and witness beam can be simulated with `Nm = 1`. But for LWFA, one usually needs `Nm = 2` or `Nm = 3` (when simulating self-injection). In some special cases, one may need even higher `Nm`.

**Comment by koesterf** [comment]
OK. Thanks. 
sometimes I also see differences in Nm=2 and Nm=3 (for rest of the things same). But may be I will discuss about it later.
Thank you very much for the discussion.
