### ISSUE TITLE
Conducting boosted frame simulation on self-modulated LWFA with Gaussian-like transverse density

### ISSUE THREAD

**Issue by ycaophysics** [fbpic/fbpic#619]
Hi. I was trying to do a boosted frame simulation on self-modulated LWFA with Gaussian-like transverse density. However, there seems to be a very large boundary reflection effect after the density peak even when I set the boundary condition to "open", and used a far wider "rmax" size(500um) than w0 of the laser(38um). I'm not sure it's due to the plasma density computation during boosted frame. (Or due to the laser being not inside the box or something else)
Here is an animation of the density plot I made:

https://user-images.githubusercontent.com/70364621/194418856-332e60f3-3cff-4d73-99c3-701225a84b9d.mp4

Here is the simulation file I had: 
[CO2_rafalPara_center_100122.py.txt](https://github.com/fbpic/fbpic/files/9728753/CO2_rafalPara_center_100122.py.txt)

Thank you
Yuxuan Cao

**Comment by RemiLehe** [comment]
Sorry for the late reply.
It looks like the problem that you are seeing is similar to this one:
https://github.com/fbpic/fbpic/issues/534
To my knowledge, there is unfortunately no good solution to remove this instability. (We are still investigating its causes.)
One way to mitigate it is to leave some vacuum region between the transverse edge of the plasma and the edge of the simulation box (see more details in the above link).

**Comment by MKirchen** [comment]
Closing as this issue is tracked by #534.
