### ISSUE TITLE
anode cathode definition

### ISSUE THREAD

**Issue by RasoulZamani** [fbpic/fbpic#620]
Hi, I recently introduced to your fbpic. I'm working on plasm (beam electron) and its instabilities ,not laser-plasma. can I use your repo or it is just for laser plasma acceleration?

usually my problems has cathode as an emitter and anode , and also I should connect voltage to anode and cathode. this problems can be solved by your code?

 also can we have transparent material in fbpic? for example PEC sheet that electrons can penetrate it but not em waves. 

this is a simplified picture for my problem:
![plasma_gen](https://user-images.githubusercontent.com/99184312/197959560-bc561103-d251-4aa7-894b-fb3ed0115346.jpg)

**Comment by RemiLehe** [comment]
Sorry for the late reply.
FBPIC does not support arbitrarily-shaped metallic boundary and is therefore probably not well-adapted to the problem that you want to simulate.
I would recommend having a look at [WarpX](https://warpx.readthedocs.io/en/latest/), which does use some of the same tools as FBPIC (e.g. openPMD for data output) and does support arbitrary metallic boundaries (see the documentation on "embedded boundaries".)

**Comment by RasoulZamani** [comment]
thanks!
