### ISSUE TITLE
Question about LWFA with ionization

### ISSUE THREAD

**Issue by dmargarone** [fbpic/fbpic#621]
Hi guys ,

Hope you all are doing great !!!

I have one question about LWFA with ionization example script (https://fbpic.github.io/example_input/ionization_script.html). 
In this example script, nitrogen atom is doped with helium atom. Helium is assumed to be pre-ionized up to level 1 (He+) and nitrogen is pre-ionized up to level 5 (N5+).  

Accordingly: 

    atoms_He = sim.add_new_species( q=e, m=4.*m_p, n=n_He,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )

    atoms_N = sim.add_new_species( q=5*e, m=14.*m_p, n=n_N,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )

    atoms_He.make_ionizable( 'He', target_species=elec, level_start=1 )

#====================================================================
**Question: 1**

Now, if I would like to consider **helium is fully ionized** then **do I need to do the following:**

    atoms_He = sim.add_new_species( q=2*e, m=4.*m_p, n=n_He,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )

    atoms_He.make_ionizable( 'He', target_species=elec, level_start=2 )

OR, I have to skip this part  ??
#====================================================================

**Additional question:**

In the test script for LWFA with ionization (https://fbpic.github.io/example_input/ionization_script.html) 
it is written that "elec_from_N = sim.add_new_species( q=-e, m=m_e )" but no such line for electrons generating from He+

Thanks a lot in advance for your time and help.

**Comment by RemiLehe** [comment]
Sorry for the late reply and thanks for your interest in the code.

Regarding your first question: if Helium is to be fully ionized, you would do:
```
atoms_He = sim.add_new_species( q=2*e, m=4.*m_p, n=n_He,
    dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )
```
(no need to call `make_ionizable` in this case, since there is ionization physics that needs to be computed by the code - He is already fully ionized.)
In addition, it is important change this line:
```
n_e = n_He + 5*n_N
```
and make it instead
```
n_e = 2*n_He + 5*n_N
```
(so that you have the right amount of electrons, corresponding to the fully ionized Helium)

**Comment by RemiLehe** [comment]
Regarding your second question: in the example script, we chose to add the electrons created from Helium to the species `elec` and to add the electrons created from Nitrogen to a separate species (`elec_from_N` - isolating the electrons from Nitrogen in this way can be useful for understanding the physics, when analyzing the simulation).

However, this is purely optional, and was meant to illustrate the flexibility of the script. You can also chose to add the electrons ionized from Nitrogen into the species `elec` (in which case, you do not need to create `elec_from_N` at all, and the line `elec_from_N = sim.add_new_species( q=-e, m=m_e )` could be removed in this case).

**Comment by dmargarone** [comment]
Hi @RemiLehe 

Thank you so much for explaining so nicely.

With lots of love and best wishes.
DM
