### ISSUE TITLE
issue of running fbpic by multi-cores 

### ISSUE THREAD

**Issue by pistachio-xin** [fbpic/fbpic#622]
When I run the scripts by fbpic, I found that the utillization of CPU is so higher than 100% like the fllowing picture, which means that this task used more than one core. I didn't use the mpi to run the code. So I wonder that how to set the number of using cores in the code.
![Uploading 批注 2022-10-28 221612.jpg…]()

**Comment by pistachio-xin** [comment]
maybe the picture is not uploaded right! Here I upload it again.
![批注 2022-10-28 221612](https://user-images.githubusercontent.com/81011698/198645094-c15761d3-defe-44f4-952b-86bfb9c00536.jpg)

**Comment by RemiLehe** [comment]
Thanks for your interest in the code.
Even without MPI, you can still use multiple cores by using multiple threads, which is activated by default in FBPIC. This is controlled by the environment variable `NUMBA_NUM_THREADS` ; you can find more information here:
https://fbpic.github.io/how_to_run.html
https://fbpic.github.io/overview/parallelisation.html

**Comment by pistachio-xin** [comment]
@RemiLehe Thank you very much! I have solved my issue by the method you mentioned.
