### ISSUE TITLE
Error in running the simulation

### ISSUE THREAD

**Issue by koesterf** [fbpic/fbpic#624]
Hi,

I stuck with an error while running a test simulation file. 
I have attached the simulation file (lwfa_script.txt) and the error message file (errout.txt).
I could not figure out what is wrong with the script and why I am getting this error message. 

Any help will be greatly appreciable. 

Best,
F. Koester

[errout.txt](https://github.com/fbpic/fbpic/files/9971146/errout.txt)
[lwfa_script.txt](https://github.com/fbpic/fbpic/files/9971148/lwfa_script.txt)

**Comment by RemiLehe** [comment]
Hi @koesterf 
Thanks for your interest in the code and for raising this issue.
Could you try to remove the `diags` folder (`rm -rf diags`) and then rerun the simulation?

**Comment by koesterf** [comment]
Hi,

Thanks for the suggestion. It works.

One more thing, the data file size is relatively quite big (7 GB) compared to same simulation with no ionization. 
Do you think it is because of the following line in the "sim.diags"

ParticleChargeDensityDiagnostic( diag_period, sim,
                    {"electrons": elec} )

Thanks.

**Comment by RemiLehe** [comment]
Yes, this quite likely. In general, ionization will produce a lot of macroparticles in the `elec` species, which is probably why the data is so large.

**Comment by koesterf** [comment]
Hi,

Thanks for the clearing the doubt. 

Best,
F. Koester
