### ISSUE TITLE
Transverse focusing field

### ISSUE THREAD

**Issue by dmargarone** [fbpic/fbpic#626]
Hi guys,

Hope you all are doing great !
I can plot the longitudinal plasma field (Ez) [accelerating field], but how I can plot the transverse plasma field [focusing field] ?

Thanks a lot.
DM

**Comment by dmargarone** [comment]
Hi !!

Does it like: "e(Ey-cBz)"  ??  

[e: electron charge, c: speed of light]

**Comment by hightower8083** [comment]
hi @dmargarone 

It depends on what you wish to plot. For example, electric field of the plasma cavity you may plot as `Ey` for any `theta` or `Ex` for non-zero `theta` (to exclude laser). With `e(Ey-cBz)` you rather obtain focusing **force** on electrons and not a field.

I think this question rather concerns data analysis with **openpmd_viewer** than **FBPIC** code itself (same question would appear for **warpx** or **smilei** RZ solvers). I would recommend to move the discussion to the [slack](https://slack-fbpic.herokuapp.com/) which is more oriented to user experience exchange.

**Comment by dmargarone** [comment]
Hi @hightower8083 

Thanks for the reply. Yes, I am looking for the transverse focusing force of the plasma wave on the electron beam. 
Sorry, I used the wrong word (transverse field) instead of (transverse force).

Also, thanks for the slack suggestion. How to join it ?

**Comment by hightower8083** [comment]
@dmargarone you should simply follow the [link](https://slack-fbpic.herokuapp.com/) and register with your email. 
after that, you'll be able to use either browser version or a dedicated app to access the channel chat-room.

**Comment by dmargarone** [comment]
@hightower8083 Thank you.

**Comment by JBGuan** [comment]
@dmargarone Have you solved this problem? I had the same problem recently.
