### ISSUE TITLE
plotting rho in x and z axis

### ISSUE THREAD

**Issue by ehsangholi** [fbpic/fbpic#628]
Hello 
I want to plot `rho` in arbitrary  directions (e.g x and z)  but when I use the command `Ez1, info_Ez1 = ts_3d.get_field( field='rho', coord='z', iteration=500,  slice_across='x', plot=True )` I get the following error
**`OpenPMDExcption: The 'slice_across' argument is erroneous: contains x the available axes are: r , z`**
how can I solve this problem?
Thanks.

**Comment by hightower8083** [comment]
@ehsangholi, as FBPIC is a quasi-cylindric code, and in the documentation of  **openpmd_viewer**'s `get_field` method for the `slice_across` argument you may find
>    + In cylindrical geometry, elements can be 'r' and/or 'z'
>    Returned array is reduced by 1 dimension per slicing.
>    If slicing is None, the full grid is returned.

Actually for 2D maps, like `(z,x)` and `(z,y)` you don't need any slicing -- in cylindrical geometry `get_field` already gives you 2D slice and you set the transverse axis by choosing proper `theta`: `0` is for `(z,x)` and `pi/2` for `(z,y)`

I think this question rather concerns data analysis with openpmd_viewer than FBPIC code itself (same question would appear for warpx or smilei RZ solvers). I would recommend to move the discussion to the [slack](https://slack-fbpic.herokuapp.com/) which is more oriented to user experience exchange.

**Comment by ehsangholi** [comment]
Ok
Thanks for your answer.
