### ISSUE TITLE
Strong density filaments in underdense plasma

### ISSUE THREAD

**Issue by leczzsolt** [fbpic/fbpic#634]
We found a strange numerical artifact in FBPIC, which should be explained.  At some parameters (usually at low a0 values) strong filaments appear in the plasma density, which  do not disappear by using higher resolution or higher m values (azimuthal modes).
![FBPIC-test-sample](https://user-images.githubusercontent.com/59912530/216258173-89f19a59-38c9-4bc3-850a-437ee227c5fd.png)

![FBPIC-test-sample-err](https://user-images.githubusercontent.com/59912530/216258200-603e7373-da6f-4d3f-a7dc-9a956074e028.png)

[lwfa_script_err.zip](https://github.com/fbpic/fbpic/files/10566185/lwfa_script_err.zip)

Here are the pictures of plasma density. The first picture is made by using the sample file given with the code.  The second pic is generated using the modified input file.
Please, let me know if you can reproduce the filaments or if you know what is the reason for seeing such things.

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

At this point, I am not yet sure what is causing this ; however, I noticed that using higher-order shape factor (`particle_shape='cubic'`, when initializing the `Simulation` object) did fix the issue:

**Linear shape factor**
<img width="437" alt="Screen Shot 2023-02-02 at 8 56 51 AM" src="https://user-images.githubusercontent.com/6685781/216390815-c7e398cf-8150-44b6-b127-270ade85d738.png">

**Cubic shape factor**
<img width="444" alt="Screen Shot 2023-02-02 at 8 57 08 AM" src="https://user-images.githubusercontent.com/6685781/216390883-0ba02e01-d0cb-4e5e-92de-58851d261a88.png">
