### ISSUE TITLE
Problem about particle tracking in ionization injection

### ISSUE THREAD

**Issue by AAyanami** [fbpic/fbpic#637]
Hello, developer!

I have one question about LWFA with ionization example script (https://fbpic.github.io/example_input/ionization_script.html).
After the calculation is completed, I hope to track the electron trajectory of nitrogen ionization:
`pt = ParticleTracker( ts, iteration=1750, select={'uz':[10,None]}, 
                     species='electrons from N' ,preserve_particle_index=True)`
But it prompts an error:
`OpenPMDException: The argument 'var_list' is missing or erroneous.
It should be a list of strings representing species record components.
 The available quantities for species 'electrons from N' are:
 - charge
 - mass
 - x
 - y
 - z
 - ux
 - uy
 - uz
 - w
Please set the argument 'var_list' accordingly.`

Then I check the list of variables, `ts.avail_record_components`, and find that the variable 'id' is not available for 'electrons from N'.
What should I do in order to track these electrons ('electrons from N')?

FBPIC version: 0.22.0 ;   openpmd_viewer version:  1.6.0 ;  python version:  3.10.9

Thank you very much.

**Comment by AAyanami** [comment]
thanks a lot!

**Comment by AAyanami** [comment]
Thanks again.
I am a beginner, and I have another question:  
Does the single/double precision of the GPU significantly affect the calculation results?
For example, is there a significant difference in the calculation results between the single-precision 4090 and the double-precision A100?

Thank you for your answer!

**Comment by MKirchen** [comment]
Dear @AAyanami, sorry for the late reply. FBPIC always uses double precision for the calculation. GPU models that are optimized for single-precision calculations (such as consumer GPUs) will just be slower. I am closing this issue now.
