### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by koesterf** [fbpic/fbpic#639]
Dear FBPIC developers, I have a feature request in the code. 

I would like to simulate very long plasma simulation ( ~ 50 cm ) ....  the time limitation on the computing facility doesn't allow to do this in a single run with Boosted Frame  ....  a restart feature in Boosted Frame simulation is required. 

It would be great to implement re-start in the Boosted Frame.

Thanks,
Frank

**Comment by hnakahara79** [comment]
@RemiLehe @MKirchen 

Hi Remi, Manuel,  as far as I understand restart option is not available for boosted frame in FBPIC. If I am correct, do you have any plan to implement it in near future ?

Thanks.

**Comment by MKirchen** [comment]
Hey @hnakahara79 and @koesterf,

unfortunately, implementing a restart option for boosted frame simulations is not trivial. It is not planned to support this in the near future, sorry. I would recommend to get in touch with the computing facility and ask them if its possible to lift the time requirements for selected jobs.

Cheers,
Manuel

**Comment by koesterf** [comment]
Dear @MKirchen , 

Thanks for the update.
