### ISSUE TITLE
About ionization elements in FBPIC

### ISSUE THREAD

**Issue by ilikeelec** [fbpic/fbpic#641]
Recently, I try to do some different element ionization in FB. But, I find that only a few elements to choose from FB. Is there any way I can introduce other elements into FB

**Comment by RemiLehe** [comment]
Thanks for the question.
We could easily add more elements in this file:
https://github.com/fbpic/fbpic/blob/dev/fbpic/particles/elementary_process/ionization/atomic_data.txt
Which elements would like to introduce?
