### ISSUE TITLE
Question for X-FEL

### ISSUE THREAD

**Issue by kookjine** [fbpic/fbpic#647]
Hello,

I am trying to check the laser-electron beam interaction during passing wiggler section for ESASE scheme of X-FEL [Phys. Rev. ST Accel. Beams 8, 040701 (2005)].
Could FBPIC properly simulate the wiggling of the electron bunch? 
If that's possible, within what physical limit?

Thans a lot for reading!
Kook-Jin

**Comment by MKirchen** [comment]
Dear @kookjine, sorry for the late reply. Modelling the asymmetry that is introduced by the oscillating beam is difficult in quasi-3D codes. We have very limited experience with such simulations using FBPIC and cannot give a simple answer whether or not this is possible.
