### ISSUE TITLE
rho value dispalyed inconsistent with and without ionization

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#652]
Hi, I am doing the LWFA with ionization. I first used the ionization example [https://fbpic.github.io/example_input/ionization_script.html](url). I compared the rho results with and without ionization and I found that the rho value is inconsistant as follows:
 
![image](https://github.com/fbpic/fbpic/assets/31507149/3acc9a66-daaa-46d9-838b-d8fbbe288a1c)
![image](https://github.com/fbpic/fbpic/assets/31507149/ca6ffc34-6736-4acd-a3cf-ab37c9dc50ed)
The figure above is the rho results with ionizaiton just by running the ionizaiton example, and the bottom figure is the rho results without ionizaiton by changing the script as follows:
` atoms_He = sim.add_new_species( q=e, m=4.*m_p, n=0*n_He,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )
    atoms_N = sim.add_new_species( q=5*e, m=14.*m_p, n=0*n_N,
        dens_func=dens_func, p_nz=p_nz, p_nr=p_nr, p_nt=p_nt, p_zmin=p_zmin )`

That is to say, I just changed the He and N atoms to zero but maintain the electron density unchanged. But the rho results looks different. The density with ionizaiton is much lower than that without ionization. Does it just a dispaly issue in the ionization case that the initial true density is actually the same as that without ionization?

**Comment by MKirchen** [comment]
Hi, sorry for the late reply. In your adapted script, you set the ion density to zero which is the reason for observed differences in the charge density.
