### ISSUE TITLE
hwo to restart a simulation with saved checkpoints

### ISSUE THREAD

**Issue by rav-ina** [fbpic/fbpic#660]
Hello,
I am Ravina, just started working on fbpic for my work.
My simulation somehow break in between and now i am stuck here, Please let me know how to restart this simulation from saved checkpoints.
Do I need to change the  folder or i can run in the same folder so that my older files do not overwrite.
What changes in my input files, i must do in order to restart the simulation from where it left.
Thanks

**Comment by alexanatoly** [comment]
Hi,
to restart the simulation just change the following line in your script file:

use_restart = False  
to
use_restart = True 

This will work if you have used "save_checkpoints = True".
