### ISSUE TITLE
An MPI running warning occurs when fbpic is installed

### ISSUE THREAD

**Issue by yth8588** [fbpic/fbpic#664]
Hello, I ran a sample program after trying to install fbpic code, it works, but there are two warnings, it seems that mpy4py is not configured correctly, I want to know if this affects my program to run, now I can generate the sample code hdf5 file and plot.
Here is my run log：
（base) [sztu ep youtenghuigln01 example input]s python iwfa script.py
UserWarning: /lustre/home/sztu ep youtenghui/min iconda3/lib/python3.11/site-packages/fbpic/utils/mpi.py:47:MPI is not properly installed.Simulations without domain decomposition will still run properly.In order to diagnose the problem, type:mpirun -np 2 python -c "from mpi4py.MPI mport COMM WORLD"
UserWarning: /lustre/home/sztu ep youtenghui/miniconda3/lib/python3.11/site-packages/fbpic/main.py:241:GPU not available for the simulation .(This is because the numba' package was not able to find a GPU.)Performing the simulation on CPU.
FBPIC (0.24.0)
Running on CPU (48 threads per process)
Initializing laser pulse on the mesh...

**Comment by MKirchen** [comment]
Hi, sorry for not answering this earlier. The code will run fine without `mpi4py` as long as you run it on a single CPU or GPU. It also seems that you are running the code on the CPU. Keep in mind that the performance is significantly better when executing the code on a GPU.
