### ISSUE TITLE
how to make wakefield smoother

### ISSUE THREAD

**Issue by JBGuan** [fbpic/fbpic#668]
Use fbpic to simulate the laser wakefield acceleration process. The wakefield distribution does not look smooth and there are many fluctuations. How can I reduce this fluctuation and make the wakefield smoother?
![image](https://github.com/fbpic/fbpic/assets/81011698/ae8abd63-04e4-4b10-81fb-f6ea432e4f34)

**Comment by RemiLehe** [comment]
Thanks for the question @pistachio-xin.
Here some ways that could make the fields smoother:
- Using more macroparticles per cell (e.g. increasing `n_pr`, `n_pz`)
- Using cubic particle shape (see the parameter `particle_shape` here: https://fbpic.github.io/api_reference/simulation.html)
- Using more passes of smoothing (see `smoother`, here: https://fbpic.github.io/api_reference/simulation.html)

**Comment by JBGuan** [comment]
Thanks for your reply. 
Based on your suggestion, I have solved this problem and got a smoother wakefield. I'll close this issue and thank you very much for your help.
