### ISSUE TITLE
large laser centroid position "removes" particles

### ISSUE THREAD

**Issue by PrometheusPi** [fbpic/fbpic#669]
This is probably a beginner question:
If I start from the [example script](https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/lwfa_script.py) and increase the laser centroid (focus in vacuum?) position, there are no particles in the diagnostic output if `z0 = 38.e-6` or larger. 

What is the reason, that particles vanish, if the laser centroid is shifted?

I am using fbpic 0.24.0 installed via conda on an M1 Mac using 8 cores of the CPU.
I could reproduce this problem on Linux with AMD CPUs.

**Comment by RemiLehe** [comment]
Thanks for the question.

The laser centroid `z0` corresponds to the position of the laser centroid at `t=0`. (Note that this example uses the default `direct` laser injection, whereby the laser is initialized entirely in the box at `t=0` - as opposed to being emitted from one of the boundaries of the simulation as is often the case in other PIC codes. More details here: https://fbpic.github.io/api_reference/lpa_utilities/laser.html)

When using `z0 = 38e-6`, the laser centroid is **outside** of the simulation box (which goes from `-10e-6` to `+30e-6` here) by a good margin (`8e-6`). In this case, the laser intensity **in the box** corresponds to the wings of the Gaussian intensity distribution and is probably very weak (and is clipped by the righthand side of the box).

Regarding the particles in the diagnostics: in this particular example, only particles with [`uz` higher than `1.`](https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/lwfa_script.py#L142) (i.e. energetic electrons) are written in the diagnostics. In the case `z0 = 38e-6`, I am guessing that the laser intensity too weak for any of the electrons to reach this kind of energy. Does that seem to be the case here?

**Comment by RemiLehe** [comment]
Btw, here is a nice image that @MKirchen made, in order to illustrate the distinction between `z0` (centroid position) and `zf` (focal position):
<img width="667" alt="Screenshot 2023-11-17 at 3 59 17 PM" src="https://github.com/fbpic/fbpic/assets/6685781/61ca4993-00bc-4f5c-81ab-af1dca353bfd">

**Comment by PrometheusPi** [comment]
Thank you @RemiLehe for providing an explanation of what happens. 

I see, that I should have set `zf` and not `z0` for the focal plane position.
