### ISSUE TITLE
how to backpropagated simulation in fbpic

### ISSUE THREAD

**Issue by JBGuan** [fbpic/fbpic#671]
I want to simulate the backpropagated process of laser wakefield acceleration in fbpic. The 'direction' in 'get_gaussian_bunch' can be set as 'backward' and the 'propagation_direction' in 'GaussianLaser' can be set as '-1'. But I can not got the right results. 
Example: 
![image](https://github.com/fbpic/fbpic/assets/81011698/e7ab9ec7-e6d2-4c2b-8ad4-a5db9361ee32)
I want to simulate a bunch backpropagated from the entrance of the plateau until the beginning of the plasma upramp then get a beam with the required Twiss parameters at the ramp entrance. 
So I would like to ask for advice of how to simulate the backpropagated process of laser wakefield acceleration in fbpic and where have a simple code of backpropagated process?

**Comment by MKirchen** [comment]
Hi, sorry for the late reply. In principle, it would be possible to run a particle-in-cell simulation of laser-wakefield accceleration in reverse. However, to do this one needs to know the exact initial conditions, which are usually only well defined before the interaction the plasma.
