### ISSUE TITLE
Issue in summing two custom lasers

### ISSUE THREAD

**Issue by mishradinkar** [fbpic/fbpic#677]
I am trying to create a circularly polarized laser pulses using two custom laser profiles but the terminal says 
![Screenshot_3](https://github.com/fbpic/fbpic/assets/59868293/ca533495-a4e3-4a79-9b24-a90d2fc9f753)
any help will be appreciated. However, simulation is working perfect with single custom laser. Issue is only when I am trying to add the two laser profiles.

This is the custom laser profile I am using [https://github.com/fbpic/fbpic/issues/674]

**Comment by mishradinkar** [comment]
I wanna add one more thing that summed laser profiles are also working perfect with laser profiles already defined in fbpic the issue is only with my custom laser profiles I have created using the structure suggested

**Comment by RemiLehe** [comment]
Thanks for raising this issue.

In your Python script, could you replace this block of code:
```
class LaserProfile( object ):
    def __init__( self, propagation_direction, gpu_capable=False ):
        assert propagation_direction in [-1, 1]
        self.propag_direction = float(propagation_direction)
        self.gpu_capable = gpu_capable

    def E_field( self, x, y, z, t ):
        return( np.zeros_like(x), np.zeros_like(x) )
```

by
```
from fbpic.lpa_utils.laser.laser_profiles import LaserProfile
```

**Comment by mishradinkar** [comment]
kudos @RemiLehe Its working perfect Now. Many Thanks
