### ISSUE TITLE
Issue with Plasma Channel formation

### ISSUE THREAD

**Issue by mishradinkar** [fbpic/fbpic#678]
Can anyone suggest me any example code where any type of plasma channel is created. I am trying to create a simple parabolic plasma channel by altering 

 `def dens_func( z, r ) :
    """Returns relative density at position z and r"""
    # Allocate relative density
    n = np.ones_like(z)
    # Make linear ramp
    n = np.where( z<ramp_start+ramp_length, (z-ramp_start)/ramp_length, n )**(1+0.3*r**2/r_ch**2)
    # Supress density before the ramp
    n = np.where( z<ramp_start, 0., n )
    return(n)`

But I cannot see the channel in phase diagrams as per the parameters. If anyone can suggest any example it will be really greatful.

**Comment by RemiLehe** [comment]
Thanks for your question.

This FBPIC example has a plasma channel here:
https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/boosted_frame_script.py#L119
If you use the [per-species charge density diagnostics](https://fbpic.github.io/api_reference/diagnostics.html#particle-density-diagnostic), you should be able to see the plasma channel in the density of the electron, as well as in the density of the ions.
Does that work for you?

**Comment by MKirchen** [comment]
Hi @dinkarm, could you solve your problem and can we close this issue?

**Comment by mishradinkar** [comment]
Yes I already got it. Thanks for responding
