### ISSUE TITLE
Guard Cell box edge Ionization-PWFA driver

### ISSUE THREAD

**Issue by David-camj** [fbpic/fbpic#680]
Attached is a summary of the findings including graphical, movie and also prefiles(included as text files to replicate solution and initial issue)

PWFA driver ionization tests were conducted using both reflective and open edge boundaries which were showing non-physical box edge ionization seemingly seeded by fields persisting in the region where the sin^2 damping is applied. This can be observed in e.g curl-free.mp4 corresponding to the following pre-ion.txt prefile for replication purposes. In this test the current-correction was set as curl-free and tested with many permutatuions. 

[pre-ion-error.txt](https://github.com/fbpic/fbpic/files/14480235/pre-ion-error.txt)
https://github.com/fbpic/fbpic/assets/57441088/5d366880-84f5-47cc-a51a-7f450ad49b7f
[curl-free-gal-off.pdf](https://github.com/fbpic/fbpic/files/14480238/curl-free-gal-off.pdf)

The field seeding this ionization can be seen in the following with the regular simualtion box overlayed in grey(see fields> 2000 microns z region):
[curl-free-gal-off.pdf](https://github.com/fbpic/fbpic/files/14480249/curl-free-gal-off.pdf)
which is in total agreement both to the movie and simulation 0th cell normalised radial ionization lineout:
![curl-free-edge_ion-sim-0th-cell-2000um](https://github.com/fbpic/fbpic/assets/57441088/144a9506-6c05-44f9-9dc7-028c3d577513)

In finiding a solution to eliminating this field larger boxes were attempted as well as using both reflected and open boundaries and various other meassures e.g truncating the electron driver , using different transform and other permutations. In all cases the instability was able to persist.

The instability was for all simualtion set-ups tested fully eliminated, using cross-depositon regardless of number of MPI ranks tested , n-order or number of modes used in the simualtion set-up as seen in the following comparison to above:
[pre-ion-fix.txt](https://github.com/fbpic/fbpic/files/14480343/pre-ion-fix.txt)
https://github.com/fbpic/fbpic/assets/57441088/ef9fa52a-731b-4e3b-8065-c0e8971f0a7e
[cross-deposition-gal-off.pdf](https://github.com/fbpic/fbpic/files/14480344/cross-deposition-gal-off.pdf)

This issue can be considered under the conditions tested to be solved but could exist for more exotic configurations outwith what was simulated for these purposes.

**Comment by RemiLehe** [comment]
Great, thanks a lot for reporting this issue with all of these details, and for posting the solution.

I think that the ionization that you observed with the `curl-free` current correction is due to the non-local nature of the algorithm, and at this point, I don't see any easy solution to fix the `curl-free` case. 
So, I agree that the best solution for now is to use the `cross-deposition` current correction.

Thanks again for taking the time to do all these tests and for reporting them here. Since you posted the solution here, I will consider this issue closed.
