### ISSUE TITLE
Discrepancy between RZ/3D (FBPIC/HiPACE++) for beam-driven wakefield

### ISSUE THREAD

**Issue by jameschappell** [fbpic/fbpic#689]
Hi,

I've been comparing the results of FBPIC (and Wake-T) to HiPACE++ for a gaussian electron-beam-driven wakefield and am seeing significant differences in the resulting field structure between the RZ codes and full 3D. I attach some minimal reproducible example input scripts and some more plots from my testing. Is this behaviour expected due to the different geometry? Am I initialising the bunch incorrectly in some way? I would expect slight differences given the different approximations and algorithms used in each code, but the significantly different wake structure between the different geometries was a little surprising to me, especially given that the laser-driven cases agree well.

Thanks in advance for your help. Please let me know if there's any other information you need from me or if I should be posting this to the HiPACE++ GitHub instead/aswell.

[code_comparison.zip](https://github.com/fbpic/fbpic/files/15248087/code_comparison.zip)
![HP_vs_Wake-T_vs_FBPIC_beam](https://github.com/fbpic/fbpic/assets/36411543/9ca6b004-3dd3-4ac1-ae93-0f2bf5d28a8d)
![HP_vs_FBPIC_beam_Ezslices](https://github.com/fbpic/fbpic/assets/36411543/8d41cbb6-c26f-475e-839a-797a860eaa2b)

### Additional notes:
- I've convergence tested all three codes.
- I'm loading the gaussian drive bunch (generated via Wake-T's `get_gaussian_bunch_from_twiss` function) from an OpenPMD file to ensure it is identical in all simulations.
- I've also checked the comparison for a laser-driven setup in Wake-T and HiPACE++ (results in the attachment) and they are agreeing well with each other, despite the difference in geometry. I've seen plots with good agreement between Wake-T and FBPIC in the laser-driven case so didn't think it necessary to reproduce these.
- The `x-` and `y-` slices of the 3D HiPACE++ simulation are identical (as expected).
- I've checked lab vs. boosted frame in FBPIC and they give identical results (and different to HiPACE++). I've also changed the number of modes and see little effect.
- As far as I'm aware, all the codes are up-to-date.
- I wanted to check WarpX (RZ & 3D) too for comparison in the beam-driven case but am waiting for some help from my cluster administration to finish the compilation. Has this been done previously? 
- I tested adding an identical backwards-propagating electron bunch at the first timestep of the FBPIC simulation (I saw this in some of the WarpX examples) but this didn't seem to help.

### Code setup:
- Both FBPIC and HiPACE++ are run on Nvidia A100s, compiled with `CUDA v11.8.89`. Wake-T (`v0.7.1` but built from latest GitHub repository) is run locally on my laptop.
- `HiPACE++ (v24.03-23-gcb94a319796c) running in double precision` with `AMReX (24.05-2-gee11254ffc7c)`
- `FBPIC v0.26.0`

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this! 
This discrepancy is indeed not expected. The fact that Wake-T and HiPACE++ do not have agreement is maybe the most surprising, since they both use the quasistatic approximation (unlike FBPIC). 
@MaxThevenet @AngelFP @AlexanderSinn Have you seen a similar effect in the past? Are you able to reproduce the issue? And should we post the same issue on the Wake-T/HiPACE++ repository?

**Comment by AlexanderSinn** [comment]
Thanks for bringing up this issue. It looks very interesting. One suspicion I have is that the x,y boundary in HiPACE++ is too close to the wake, causing it to be shorter. HiPACE++ uses Dirichlet boundary conditions, while the RZ codes allow a 1/r field to go to infinity (is this correct, Remi?). Thanks to the inclusion of the input scripts in the issue, I will be able to do further HiPACE++ simulations to verify/falsify my suspicion about the boundary shortly.

**Comment by AngelFP** [comment]
Hi all,
It's good to see that FBPIC and Wake-T agree so well, but in principle there is no reason why Hipace should be giving different results here.

I've done similar convergence tests with Wake-T and hipace (beam driven case) and they both agree extremely well.

How many particles do you have in the driver? That's something where hipace might need more due to the 3d grid.

**Comment by jameschappell** [comment]
Thanks all for the suggestions!

> How many particles do you have in the driver? That's something where hipace might need more due to the 3d grid.

@AngelFP I only used `1e5` particles in the driver for these tests, so can try increasing this.

**Comment by AlexanderSinn** [comment]
I used HiPACE++ to run the provided input script unchanged (blue) and with
```
amr.n_cell = 2047 2047 1024
geometry.prob_lo     = -100.e-6 -100.e-6 -155.e-6
geometry.prob_hi     =  100.e-6  100.e-6  0.e-6
```
to extend the domain transversely by 2x (orange). This now looks closer to the RZ codes.

![image](https://github.com/fbpic/fbpic/assets/64009254/faab1741-ec00-43dc-8816-ce70f093c252)

**Comment by jameschappell** [comment]
@AlexanderSinn thanks! Such a simple fix, sorry! I also re-ran with the wider box and got much better agreement between the codes. Thanks all for your help! @RemiLehe @AngelFP 

![HPwider_vs_Wake-T_vs_FBPIC_beam](https://github.com/fbpic/fbpic/assets/36411543/1036fec3-844f-47d2-a5f2-331eafaec669)

**Comment by AngelFP** [comment]
Looks great!
