### ISSUE TITLE
running on perlmutter

### ISSUE THREAD

**Issue by dmargarone** [fbpic/fbpic#693]
Dear Developers,

Does the installation instructions for fbpic on Perlmutter is still valid or it is outdated [(given here)](https://fbpic.github.io/install/install_perlmutter.html) ?
Can I exactly follow the instructions to install and run fbpic ?

**Comment by RemiLehe** [comment]
Hm, I have not tested these instructions in a while. 
Feel free to try them and to report any issue. If it turns out that exactly following these instructions does not work, I can work on fixing them.

**Comment by dmargarone** [comment]
Thanks @RemiLehe. I will try and let you know if any problem appears.

**Comment by dmargarone** [comment]
Hi @RemiLehe , I would like to confirm about cuda version. Should I use ```cudatoolkit=11.7``` or there is any change (e.g. 12.2) ?

If I use ```module list``` it shows me ```cudatoolkit/12.2```

**Comment by RemiLehe** [comment]
I think that `cudatoolkit=11.7` should work in principle (`conda` download its own version of `cuda` and does not use the one from NERSC, I think).
But, by the same token, `cudatoolkit=12.2` should also work, so I think that there is no harm in trying it out.

**Comment by dmargarone** [comment]
Hi @RemiLehe, thanks. I agree with your suggestion.

**Comment by dmargarone** [comment]
Hi @RemiLehe , I have one more question about the Job submission file given in the document [Link](https://fbpic.github.io/install/install_perlmutter.html). When I use the job script file as (shown minimal)
```
#SBATCH -q regular
#SBATCH -J test
#SBATCH -C gpu
#SBATCH -N 1
#SBATCH -G 4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1
#SBATCH --time 00:20:00


module load python cudatoolkit

source activate fbpic

export MPICH_GPU_SUPPORT_ENABLED=0
export FBPIC_ENABLE_GPUDIRECT=0

srun -n 4 python fbpic_test_script.py
```

it gave me an error: ```srun: Job step aborted: Waiting up to 32 seconds for job step to finish. ```

Is this line is correct enough: ```srun -n 4 python fbpic_test_script.py``` ?

How this error can be fixed ?

**Comment by RemiLehe** [comment]
Thanks for reporting this.
Do get any additional message related to this error?

`srun` is indeed the correct command to use (see [this NERSC page](https://docs.nersc.gov/systems/perlmutter/running-jobs/)), but you can optionally skip `-n 4`.

**Comment by dmargarone** [comment]
Hi @RemiLehe , thanks for answering. I will try again without ```-n 4``` . 
I don't remember if there was any other error message (as I was experimenting with different options). However, I will check it again.

**Comment by dmargarone** [comment]
Hi @RemiLehe, now I get a different error. Minimal job script and error message are below.

```
#SBATCH -q regular
#SBATCH -C gpu
#SBATCH -N 1
#SBATCH -G 4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1
#SBATCH --time 00:20:00
#SBATCH --output stdout
#SBATCH --error errout

module load python
module load cudatoolkit

source activate fbpic

export MPICH_GPU_SUPPORT_ENABLED=0
export FBPIC_ENABLE_GPUDIRECT=0

srun python fbpic_test.py
```

The error message was:  ```Failed to detect UUID of GPU 0 (invalid UUID length: 6)```

**Comment by dmargarone** [comment]
Hi @RemiLehe, I even tried generating a job script from ```Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html``` but this also didn't helped. I don't know what's going wrong. 

If you don't mind, could you like to share your job script file you are using to run program on Perlmutter.

**Comment by RemiLehe** [comment]
Sure, here is a job script that I just tested today and that worked for me (make sure to replace `<account_number>` by your own account number, appended with `_g` at the end, as mentioned [here](https://docs.nersc.gov/iris/iris-for-users/#gpu))
```
#!/bin/bash
#SBATCH -J my_job
#SBATCH -A <account_number>
#SBATCH -C gpu
#SBATCH --time 00:10:00
#SBATCH --ntasks 4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1

module load python cudatoolkit
source activate fbpic

export MPICH_GPU_SUPPORT_ENABLED=0
export FBPIC_ENABLE_GPUDIRECT=0

srun -n 4 python fbpic_script.py
```
Does this work for you?

**Comment by dmargarone** [comment]
Hi @RemiLehe , thanks a lot. I will re-check with this script once again.

**Comment by dmargarone** [comment]
Hi @RemiLehe , thank you the job is running now.

**Comment by dmargarone** [comment]
Hi @RemiLehe,  when I used your job script file and the standard LWFA simulation [LWFA](https://fbpic.github.io/example_input/lwfa_script.html), it worked perfectly. 

But when I am using my customize LWFA script, which is of course with high resolution, it is neither showing any error nor dumping any data. Later I figure out that this is due to quite high resolution (when resolution is reduced, the program starts saving data files).

```Do you think I have to increases the number of GPUs to fix the problem of memory ?```

**Comment by dmargarone** [comment]
Hi @RemiLehe, maybe I found the way of using GPUs with 2 nodes

```
#SBATCH -C gpu
#SBATCH -N 2
#SBATCH -G 8
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1
#SBATCH --time 00:20:00

module load python
module load cudatoolkit

source activate fbpic

export MPICH_GPU_SUPPORT_ENABLED=0
export FBPIC_ENABLE_GPUDIRECT=0

srun -n 8 python fbpic_script.py
```

But I am surprise to notice that same simulation, even with higher resolution, was easily run on 1 node 4 GPUs (A100) elsewhere and very efficiently. 

However, I notice a strange thing that may be Perlmutter is not using the memory properly in my case. Is there any memory controlling argument ? ```Like #SBATCH --mem=250G```

**Comment by dmargarone** [comment]
Hi @RemiLehe , my simulation domain is

```
Nz = 12000
zmax = 100.0e-6
zmin =  -100.0e-6
Nr = 3000
rmax = 100.0e-6
Nm =3

p_nz = 2
p_nr = 2
p_nt = Nm*4
```

```Does such simulation fits with 1 node and 4 GPUs ?```
