### ISSUE TITLE
What kind of gpu is suitable for running fbpic？

### ISSUE THREAD

**Issue by JBGuan** [fbpic/fbpic#695]
Recently, I want to buy a gpu to run fbpic, what kind of gpu is suitable for fbpic, any suggestions? Or does fbpic have requirements for the gpu model? Thank you very much。

**Comment by RemiLehe** [comment]
Sorry for the late reply.
Any NVIDIA GPU will work (but not AMD GPUs or GPUs from other vendors). Most recently, I think that users of FBPIC have mostly used V100 and A100 GPUs.

**Comment by JBGuan** [comment]
@RemiLehe Thank you for your reply. I recently encountered some problems when testing GPU running FBPIC. Could you please help me find out what the problem is? I encountered two problems as shown in the following figure:
![image](https://github.com/user-attachments/assets/30349fd4-7cf9-45cb-a5a8-0c1496ee2d46)
![image](https://github.com/user-attachments/assets/503bcc47-6e92-45bc-90be-f01da4de657e)
My GPU is Nvidia Tesla V100 16GB NVLink, there have two cuda driver: cuda12.2; cuda11.6.
I have tried to install the corresponding cuda-version for both CUDAs: 
conda install -c conda-forge cupy cuda-version=11.6
conda install -c conda-forge cupy cuda-version=12.2 cuda-nvcc cuda-nvrtc
Before running fbpic, I will load the corresponding cuda: module load nvidia/cuda/11.6 and module load nvidia/cuda/12.2
However, in both cases, the error shown in the first picture will occur. I don’t know where the problem is?
The following is the relevant version of cuda11.6:
![image](https://github.com/user-attachments/assets/96158f32-9bb0-4a64-afcd-fb616a17dbec)

**Comment by JBGuan** [comment]
Sorry, there is something wrong with my permission settings. I had no problem installing FBPIC by following the installation tutorial. I'll close the issue, thank you very much.
