### ISSUE TITLE
laser pulse energy

### ISSUE THREAD

**Issue by dmargarone** [fbpic/fbpic#699]
Hi,

I was asked by one reviewer to plot the laser pulse energy as it goes into the plasma. 
How I can calculate laser pulse energy ?

Thank you.
DM

**Comment by dmargarone** [comment]
Hi @RemiLehe 
If my laser pulse is somewhere 2 mm inside the plasma is there any way to calculate its energy ?
or, can we calculate the laser pulse energy at any time in the simulation ?

**Comment by dmargarone** [comment]
Hi @RemiLehe 

May be we can use ```Poynting vector``` to estimate energy of the laser pulse at instant during the simulation ?
If you have time, please, could you see the attached PDF file and the expression under the red rectangle. 
Do you think this expression could be used to estimate laser pulse energy ?

Thanks a lot.

DM

[Poynting_vector.pdf](https://github.com/user-attachments/files/17483201/Poynting_vector.pdf)

**Comment by RemiLehe** [comment]
Thanks for the questions and sorry for the very late reply! 

I will try to add this functionality in `openPMD-viewer`.

**Comment by RemiLehe** [comment]
Here is a first draft:
https://github.com/openPMD/openPMD-viewer/pull/431

**Comment by dmargarone** [comment]
Hi @RemiLehe, 

Thank a lot for your help. 

Best regards,
DM
