### ISSUE TITLE
Implement several CPU optimizations

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#70]
This includes:
- [x] Generating particles so that they are (initially at least) contiguous in r (and not in z). This would lead to better memory access patterns for current deposition/gathering, since cells are also contiguous in r. (Implemented in PR #79)
- [x] Improve/remove the `weights` function (it is currently taking a substantial fraction of the time and is not optimized). It could be implemented directly in the deposition functions, as it is done for CUDA kernels. (Implemented in PR #80)

**Comment by MKirchen** [comment]
#80 #71
