### ISSUE TITLE
trouble restarting the simulation

### ISSUE THREAD

**Issue by rl3418** [fbpic/fbpic#701]
[ionisation.txt](https://github.com/user-attachments/files/17689364/ionisation.txt)
[log.txt](https://github.com/user-attachments/files/17689365/log.txt)

Hi,

I am trying to run a restart from checkpoint. Here is the job script and log file attached. I ran into an index out of range error with the particle_array.

**Comment by rl3418** [comment]
Seems that if I disable tracking particles, the restart works. Is this suppose to be turned off?

**Comment by RemiLehe** [comment]
Sorry for the late reply!
Yes, tracking is automatically turned on in a restarted simulation (if the original, checkpointed simulation had tracking activated). 
As consequence, turning tracking on in a restarted simulation does create problems. Thus, typically simulation script that are meant for restarting a simulation will have an `if` condition like this one:
https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/lwfa_script.py#L128

Sorry that this is not very clear in the documentation.

**Comment by rl3418** [comment]
Thanks for the clarification.
