### ISSUE TITLE
how to set the Airy laser in FBPIC?

### ISSUE THREAD

**Issue by JBGuan** [fbpic/fbpic#704]
Hi, realistic transverse laser modes are hardly ever Gaussian and rather resemble Airy patterns for typical high-intensity lasers used for LPAs, so I want to know how to set the Airy laser in the FBPIC. Thank you very much.

**Comment by RemiLehe** [comment]
Thanks for your question @JBGuan.

There are two options:
- Using the "flattened-Gaussian" profile: see https://fbpic.github.io/api_reference/lpa_utilities/laser_profiles/flattened.html. This profile produces an intensity pattern similar to an Airy pattern in the laser focal plane.
- Using the `lasy` library (see https://fbpic.github.io/api_reference/lpa_utilities/laser_profiles/from_lasy_file.html) to initialize a Jinc profile (https://lasydoc.readthedocs.io/en/latest/api/profiles/transverse/jinc_profile.html)

Does this answer your question?

**Comment by JBGuan** [comment]
Thank you very much for your answer, it solvers my question very well. I will close the issue.
