### ISSUE TITLE
Launch Travis tests in Docker containers that contain the pre-installed dependencies

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#90]
This would make the tests much faster, as we would avoid reinstalling the dependencies everytime.

**Comment by soerenjalas** [comment]
But would the docker container have to be contained in the repo then or would you host it somewhere else? Otherwise it would probably increase the size of the repository quite a bit.

**Comment by RemiLehe** [comment]
We can host the container on Dockerhub (https://hub.docker.com/). We already use this solution for Warp (using Shippable instead of Travis):
- [Docker container](https://hub.docker.com/r/rlehe/warp/)
- [Yaml file](https://bitbucket.org/berkeleylab/warp/src/ddfc671c1c68d7b08403f52bbc67c2e939635ed8/.shippable.yml?at=master&fileviewer=file-view-default)

In the case of FBPIC, we could still store the source for the container (the Dockerfile) in the repository, since it is just a simple text file.

**Comment by RemiLehe** [comment]
I tested this on a branch on my fork. Unfortunately it does not seem that the Docker container makes the tests significantly faster. This is because the container is quite large (almost a Gb), and is not cached by Travis CI, so it is downloaded for each Travis build.

Therefore I'll close this issue.
