### ISSUE TITLE
Time estimator of the PIC loop: do not use first step

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#94]
The estimator that computes the remaining time uses the time taken in the first step for the calculation. However, the first step is special since it includes JIT compilation. It should not be included.

**Comment by RemiLehe** [comment]
Note: we could also add a message during the first iteration, that lets the user know that Just-In-Time compiling is being performed. (so that the user doesn't think that the first iteration is representation of the time it takes)

**Comment by soerenjalas** [comment]
We also discussed if the time estimation would be better by only averaging over the most recent 100 steps or so, because usually the first time steps don't contain many particles and therefore don't represent the simulation time very well.

**Comment by RemiLehe** [comment]
Yes, actually, we could print the time left only once we have enough iteration to estimate it with a reasonable confidence (e.g. only once we have performed at least Nz timesteps, so that the simulation box is filled with plasma)
